[workspace]
members = [
    "hmux-rt",
]

[workspace.lints.clippy]
disallowed_methods = "deny"
await_holding_refcell_ref = "deny"

[package]
name = "hmux2"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "hmux2"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]
[[bin]]
path = "src/main.rs"
name = "hmux2"
[dependencies]
hmux-rt = { path = "hmux-rt" }
c2rust-bitfields = "0.22.1"
libc = "0.2"

[dev-dependencies]
syn = { version = "2", features = ["full", "visit"] }
