//! All original constant copies must retain both their Rust type and value.
use std::{
    collections::BTreeMap,
    mem::{align_of_val, size_of_val},
};

#[test]
fn migrated_constants_match_original_types_and_values() {
    let mut constants = BTreeMap::new();
    fn same_type<T>(_: &T, _: &T) {}
    macro_rules! constant {
        ($name:ident, [$first:path $(, $copy:path)*]) => {{
            $(same_type(&$first, &$copy); assert_eq!($first, $copy);)*
            constants.insert(stringify!($name), format!("{} {} {:?}",
                size_of_val(&$first), align_of_val(&$first), $first));
        }};
    }
    constant!(
        ALL_MODES,
        [hmux2::src::screen::ALL_MODES, hmux2::src::tty::ALL_MODES]
    );
    constant!(
        ALL_MOUSE_MODES,
        [
            hmux2::src::format::ALL_MOUSE_MODES,
            hmux2::src::input::ALL_MOUSE_MODES,
            hmux2::src::input_keys::ALL_MOUSE_MODES,
            hmux2::src::server_client::ALL_MOUSE_MODES,
            hmux2::src::tty::ALL_MOUSE_MODES
        ]
    );
    constant!(CLEAR, [hmux2::src::screen_write::CLEAR]);
    constant!(
        CLIENT_ALLREDRAWFLAGS,
        [
            hmux2::src::server_client::CLIENT_ALLREDRAWFLAGS,
            hmux2::src::server_fn::CLIENT_ALLREDRAWFLAGS,
            hmux2::src::status::CLIENT_ALLREDRAWFLAGS,
            hmux2::src::tty::CLIENT_ALLREDRAWFLAGS
        ]
    );
    constant!(
        CLIENT_ASSUMEPASTING,
        [hmux2::src::server_client::CLIENT_ASSUMEPASTING]
    );
    constant!(
        CLIENT_ATTACHED,
        [
            hmux2::src::cmd_attach_session::CLIENT_ATTACHED,
            hmux2::src::cmd_new_session::CLIENT_ATTACHED,
            hmux2::src::file::CLIENT_ATTACHED,
            hmux2::src::server_client::CLIENT_ATTACHED,
            hmux2::src::sort::CLIENT_ATTACHED
        ]
    );
    constant!(
        CLIENT_BRACKETPASTING,
        [hmux2::src::server_client::CLIENT_BRACKETPASTING]
    );
    constant!(
        CLIENT_CONTROL,
        [
            hmux2::src::alerts::CLIENT_CONTROL,
            hmux2::src::cfg::CLIENT_CONTROL,
            hmux2::src::client::CLIENT_CONTROL,
            hmux2::src::cmd_attach_session::CLIENT_CONTROL,
            hmux2::src::cmd_capture_pane::CLIENT_CONTROL,
            hmux2::src::cmd_display_menu::CLIENT_CONTROL,
            hmux2::src::cmd_display_message::CLIENT_CONTROL,
            hmux2::src::cmd_list_keys::CLIENT_CONTROL,
            hmux2::src::cmd_new_session::CLIENT_CONTROL,
            hmux2::src::cmd_queue::CLIENT_CONTROL,
            hmux2::src::cmd_refresh_client::CLIENT_CONTROL,
            hmux2::src::cmd_save_buffer::CLIENT_CONTROL,
            hmux2::src::cmd_select_layout::CLIENT_CONTROL,
            hmux2::src::cmd_select_pane::CLIENT_CONTROL,
            hmux2::src::cmd_source_file::CLIENT_CONTROL,
            hmux2::src::control_notify::CLIENT_CONTROL,
            hmux2::src::file::CLIENT_CONTROL,
            hmux2::src::format::CLIENT_CONTROL,
            hmux2::src::resize::CLIENT_CONTROL,
            hmux2::src::server_client::CLIENT_CONTROL,
            hmux2::src::server_fn::CLIENT_CONTROL,
            hmux2::src::spawn::CLIENT_CONTROL,
            hmux2::src::status::CLIENT_CONTROL,
            hmux2::src::tmux::CLIENT_CONTROL,
            hmux2::src::window::CLIENT_CONTROL
        ]
    );
    constant!(
        CLIENT_CONTROLCONTROL,
        [
            hmux2::src::client::CLIENT_CONTROLCONTROL,
            hmux2::src::control::CLIENT_CONTROLCONTROL,
            hmux2::src::tmux::CLIENT_CONTROLCONTROL
        ]
    );
    constant!(
        CLIENT_CONTROL_DISCARD,
        [hmux2::src::control::CLIENT_CONTROL_DISCARD]
    );
    constant!(
        CLIENT_CONTROL_NEWLAYOUTS,
        [
            hmux2::src::cmd_select_layout::CLIENT_CONTROL_NEWLAYOUTS,
            hmux2::src::format::CLIENT_CONTROL_NEWLAYOUTS,
            hmux2::src::server_client::CLIENT_CONTROL_NEWLAYOUTS
        ]
    );
    constant!(
        CLIENT_CONTROL_NOOUTPUT,
        [
            hmux2::src::control::CLIENT_CONTROL_NOOUTPUT,
            hmux2::src::server_client::CLIENT_CONTROL_NOOUTPUT
        ]
    );
    constant!(
        CLIENT_CONTROL_PAUSEAFTER,
        [
            hmux2::src::control::CLIENT_CONTROL_PAUSEAFTER,
            hmux2::src::server_client::CLIENT_CONTROL_PAUSEAFTER
        ]
    );
    constant!(
        CLIENT_CONTROL_WAITEXIT,
        [
            hmux2::src::client::CLIENT_CONTROL_WAITEXIT,
            hmux2::src::server_client::CLIENT_CONTROL_WAITEXIT
        ]
    );
    constant!(
        CLIENT_DEAD,
        [
            hmux2::src::cmd_confirm_before::CLIENT_DEAD,
            hmux2::src::cmd_load_buffer::CLIENT_DEAD,
            hmux2::src::control::CLIENT_DEAD,
            hmux2::src::file::CLIENT_DEAD,
            hmux2::src::format::CLIENT_DEAD,
            hmux2::src::input::CLIENT_DEAD,
            hmux2::src::resize::CLIENT_DEAD,
            hmux2::src::server_client::CLIENT_DEAD,
            hmux2::src::sort::CLIENT_DEAD,
            hmux2::src::window::CLIENT_DEAD,
            hmux2::src::window_client::CLIENT_DEAD
        ]
    );
    constant!(
        CLIENT_DEFAULTSOCKET,
        [
            hmux2::src::server::CLIENT_DEFAULTSOCKET,
            hmux2::src::tmux::CLIENT_DEFAULTSOCKET
        ]
    );
    constant!(
        CLIENT_DOUBLECLICK,
        [hmux2::src::server_client::CLIENT_DOUBLECLICK]
    );
    constant!(
        CLIENT_EXIT,
        [
            hmux2::src::control::CLIENT_EXIT,
            hmux2::src::control_notify::CLIENT_EXIT,
            hmux2::src::format::CLIENT_EXIT,
            hmux2::src::input::CLIENT_EXIT,
            hmux2::src::resize::CLIENT_EXIT,
            hmux2::src::server::CLIENT_EXIT,
            hmux2::src::server_acl::CLIENT_EXIT,
            hmux2::src::server_client::CLIENT_EXIT,
            hmux2::src::server_fn::CLIENT_EXIT,
            hmux2::src::sort::CLIENT_EXIT,
            hmux2::src::window::CLIENT_EXIT,
            hmux2::src::window_client::CLIENT_EXIT
        ]
    );
    constant!(
        CLIENT_EXITED,
        [
            hmux2::src::server_client::CLIENT_EXITED,
            hmux2::src::window::CLIENT_EXITED
        ]
    );
    constant!(
        CLIENT_FOCUSED,
        [
            hmux2::src::server_client::CLIENT_FOCUSED,
            hmux2::src::tty_keys::CLIENT_FOCUSED,
            hmux2::src::window::CLIENT_FOCUSED
        ]
    );
    constant!(
        CLIENT_IDENTIFIED,
        [
            hmux2::src::server::CLIENT_IDENTIFIED,
            hmux2::src::server_client::CLIENT_IDENTIFIED
        ]
    );
    constant!(
        CLIENT_IGNORESIZE,
        [
            hmux2::src::cmd_attach_session::CLIENT_IGNORESIZE,
            hmux2::src::cmd_switch_client::CLIENT_IGNORESIZE,
            hmux2::src::resize::CLIENT_IGNORESIZE,
            hmux2::src::server_client::CLIENT_IGNORESIZE
        ]
    );
    constant!(
        CLIENT_LOGIN,
        [
            hmux2::src::client::CLIENT_LOGIN,
            hmux2::src::tmux::CLIENT_LOGIN
        ]
    );
    constant!(
        CLIENT_NODETACHFLAGS,
        [hmux2::src::server_client::CLIENT_NODETACHFLAGS]
    );
    constant!(
        CLIENT_NOFORK,
        [
            hmux2::src::server::CLIENT_NOFORK,
            hmux2::src::tmux::CLIENT_NOFORK
        ]
    );
    constant!(CLIENT_NOSIZEFLAGS, [hmux2::src::resize::CLIENT_NOSIZEFLAGS]);
    constant!(
        CLIENT_NOSTARTSERVER,
        [
            hmux2::src::client::CLIENT_NOSTARTSERVER,
            hmux2::src::tmux::CLIENT_NOSTARTSERVER
        ]
    );
    constant!(
        CLIENT_NO_DETACH_ON_DESTROY,
        [
            hmux2::src::server_client::CLIENT_NO_DETACH_ON_DESTROY,
            hmux2::src::server_fn::CLIENT_NO_DETACH_ON_DESTROY
        ]
    );
    constant!(
        CLIENT_PASTE_TIME_LIMIT,
        [hmux2::src::server_client::CLIENT_PASTE_TIME_LIMIT]
    );
    constant!(
        CLIENT_READONLY,
        [
            hmux2::src::cmd_attach_session::CLIENT_READONLY,
            hmux2::src::cmd_detach_client::CLIENT_READONLY,
            hmux2::src::cmd_send_keys::CLIENT_READONLY,
            hmux2::src::cmd_switch_client::CLIENT_READONLY,
            hmux2::src::format::CLIENT_READONLY,
            hmux2::src::key_bindings::CLIENT_READONLY,
            hmux2::src::server_acl::CLIENT_READONLY,
            hmux2::src::server_client::CLIENT_READONLY,
            hmux2::src::window_copy::CLIENT_READONLY
        ]
    );
    constant!(
        CLIENT_REDRAWBORDERS,
        [
            hmux2::src::cmd_select_pane::CLIENT_REDRAWBORDERS,
            hmux2::src::screen_redraw::CLIENT_REDRAWBORDERS,
            hmux2::src::server_client::CLIENT_REDRAWBORDERS,
            hmux2::src::server_fn::CLIENT_REDRAWBORDERS,
            hmux2::src::status::CLIENT_REDRAWBORDERS,
            hmux2::src::tty::CLIENT_REDRAWBORDERS
        ]
    );
    constant!(
        CLIENT_REDRAWMENU,
        [
            hmux2::src::screen_redraw::CLIENT_REDRAWMENU,
            hmux2::src::server_client::CLIENT_REDRAWMENU,
            hmux2::src::server_fn::CLIENT_REDRAWMENU,
            hmux2::src::status::CLIENT_REDRAWMENU,
            hmux2::src::tty::CLIENT_REDRAWMENU
        ]
    );
    constant!(
        CLIENT_REDRAWOVERLAY,
        [
            hmux2::src::popup::CLIENT_REDRAWOVERLAY,
            hmux2::src::screen_redraw::CLIENT_REDRAWOVERLAY,
            hmux2::src::server_client::CLIENT_REDRAWOVERLAY,
            hmux2::src::server_fn::CLIENT_REDRAWOVERLAY,
            hmux2::src::status::CLIENT_REDRAWOVERLAY,
            hmux2::src::tty::CLIENT_REDRAWOVERLAY
        ]
    );
    constant!(
        CLIENT_REDRAWSCROLLBARS,
        [hmux2::src::server_client::CLIENT_REDRAWSCROLLBARS]
    );
    constant!(
        CLIENT_REDRAWSTATUS,
        [
            hmux2::src::cmd_select_pane::CLIENT_REDRAWSTATUS,
            hmux2::src::format::CLIENT_REDRAWSTATUS,
            hmux2::src::screen_redraw::CLIENT_REDRAWSTATUS,
            hmux2::src::server_client::CLIENT_REDRAWSTATUS,
            hmux2::src::server_fn::CLIENT_REDRAWSTATUS,
            hmux2::src::status::CLIENT_REDRAWSTATUS,
            hmux2::src::tty::CLIENT_REDRAWSTATUS
        ]
    );
    constant!(
        CLIENT_REDRAWSTATUSALWAYS,
        [
            hmux2::src::server_client::CLIENT_REDRAWSTATUSALWAYS,
            hmux2::src::server_fn::CLIENT_REDRAWSTATUSALWAYS,
            hmux2::src::status::CLIENT_REDRAWSTATUSALWAYS,
            hmux2::src::tty::CLIENT_REDRAWSTATUSALWAYS
        ]
    );
    constant!(
        CLIENT_REDRAWWINDOW,
        [
            hmux2::src::screen_redraw::CLIENT_REDRAWWINDOW,
            hmux2::src::screen_write::CLIENT_REDRAWWINDOW,
            hmux2::src::server_client::CLIENT_REDRAWWINDOW,
            hmux2::src::server_fn::CLIENT_REDRAWWINDOW,
            hmux2::src::status::CLIENT_REDRAWWINDOW,
            hmux2::src::tty::CLIENT_REDRAWWINDOW
        ]
    );
    constant!(CLIENT_REPEAT, [hmux2::src::server_client::CLIENT_REPEAT]);
    constant!(
        CLIENT_SIZECHANGED,
        [
            hmux2::src::cmd_refresh_client::CLIENT_SIZECHANGED,
            hmux2::src::resize::CLIENT_SIZECHANGED
        ]
    );
    constant!(CLIENT_STARTSERVER, [hmux2::src::client::CLIENT_STARTSERVER]);
    constant!(
        CLIENT_STATUSFORCE,
        [
            hmux2::src::cmd_refresh_client::CLIENT_STATUSFORCE,
            hmux2::src::server_client::CLIENT_STATUSFORCE,
            hmux2::src::status::CLIENT_STATUSFORCE
        ]
    );
    constant!(
        CLIENT_STATUSOFF,
        [
            hmux2::src::resize::CLIENT_STATUSOFF,
            hmux2::src::status::CLIENT_STATUSOFF
        ]
    );
    constant!(
        CLIENT_SUSPENDED,
        [
            hmux2::src::control::CLIENT_SUSPENDED,
            hmux2::src::format::CLIENT_SUSPENDED,
            hmux2::src::input::CLIENT_SUSPENDED,
            hmux2::src::resize::CLIENT_SUSPENDED,
            hmux2::src::screen_redraw::CLIENT_SUSPENDED,
            hmux2::src::server::CLIENT_SUSPENDED,
            hmux2::src::server_client::CLIENT_SUSPENDED,
            hmux2::src::server_fn::CLIENT_SUSPENDED,
            hmux2::src::sort::CLIENT_SUSPENDED,
            hmux2::src::tty::CLIENT_SUSPENDED,
            hmux2::src::window::CLIENT_SUSPENDED,
            hmux2::src::window_client::CLIENT_SUSPENDED
        ]
    );
    constant!(
        CLIENT_TERMINAL,
        [
            hmux2::src::server_client::CLIENT_TERMINAL,
            hmux2::src::tty::CLIENT_TERMINAL
        ]
    );
    constant!(
        CLIENT_TRIPLECLICK,
        [hmux2::src::server_client::CLIENT_TRIPLECLICK]
    );
    constant!(
        CLIENT_UNATTACHEDFLAGS,
        [
            hmux2::src::control::CLIENT_UNATTACHEDFLAGS,
            hmux2::src::format::CLIENT_UNATTACHEDFLAGS,
            hmux2::src::input::CLIENT_UNATTACHEDFLAGS,
            hmux2::src::resize::CLIENT_UNATTACHEDFLAGS,
            hmux2::src::server_client::CLIENT_UNATTACHEDFLAGS,
            hmux2::src::sort::CLIENT_UNATTACHEDFLAGS,
            hmux2::src::window::CLIENT_UNATTACHEDFLAGS,
            hmux2::src::window_client::CLIENT_UNATTACHEDFLAGS
        ]
    );
    constant!(
        CLIENT_UTF8,
        [
            hmux2::src::cmd_queue::CLIENT_UTF8,
            hmux2::src::format::CLIENT_UTF8,
            hmux2::src::screen_redraw::CLIENT_UTF8,
            hmux2::src::server_client::CLIENT_UTF8,
            hmux2::src::tmux::CLIENT_UTF8,
            hmux2::src::tty::CLIENT_UTF8,
            hmux2::src::tty_acs::CLIENT_UTF8,
            hmux2::src::tty_features::CLIENT_UTF8
        ]
    );
    constant!(
        CLIENT_WINDOWSIZECHANGED,
        [
            hmux2::src::cmd_refresh_client::CLIENT_WINDOWSIZECHANGED,
            hmux2::src::resize::CLIENT_WINDOWSIZECHANGED
        ]
    );
    constant!(
        CLIENT_WRITE_ACK,
        [
            hmux2::src::client::CLIENT_WRITE_ACK,
            hmux2::src::file::CLIENT_WRITE_ACK
        ]
    );
    constant!(CMDQ_FIRED, [hmux2::src::cmd_queue::CMDQ_FIRED]);
    constant!(
        CMDQ_STATE_CONTROL,
        [
            hmux2::src::cmd_queue::CMDQ_STATE_CONTROL,
            hmux2::src::control::CMDQ_STATE_CONTROL
        ]
    );
    constant!(
        CMDQ_STATE_NOHOOKS,
        [
            hmux2::src::cmd_queue::CMDQ_STATE_NOHOOKS,
            hmux2::src::hooks::CMDQ_STATE_NOHOOKS
        ]
    );
    constant!(
        CMDQ_STATE_REPEAT,
        [
            hmux2::src::cmd_attach_session::CMDQ_STATE_REPEAT,
            hmux2::src::cmd_new_session::CMDQ_STATE_REPEAT,
            hmux2::src::cmd_switch_client::CMDQ_STATE_REPEAT,
            hmux2::src::key_bindings::CMDQ_STATE_REPEAT
        ]
    );
    constant!(CMDQ_WAITING, [hmux2::src::cmd_queue::CMDQ_WAITING]);
    constant!(
        CMD_AFTERHOOK,
        [
            hmux2::src::cmd_bind_key::CMD_AFTERHOOK,
            hmux2::src::cmd_capture_pane::CMD_AFTERHOOK,
            hmux2::src::cmd_choose_tree::CMD_AFTERHOOK,
            hmux2::src::cmd_copy_mode::CMD_AFTERHOOK,
            hmux2::src::cmd_display_menu::CMD_AFTERHOOK,
            hmux2::src::cmd_display_message::CMD_AFTERHOOK,
            hmux2::src::cmd_kill_pane::CMD_AFTERHOOK,
            hmux2::src::cmd_list_buffers::CMD_AFTERHOOK,
            hmux2::src::cmd_list_clients::CMD_AFTERHOOK,
            hmux2::src::cmd_list_commands::CMD_AFTERHOOK,
            hmux2::src::cmd_list_keys::CMD_AFTERHOOK,
            hmux2::src::cmd_list_panes::CMD_AFTERHOOK,
            hmux2::src::cmd_list_sessions::CMD_AFTERHOOK,
            hmux2::src::cmd_list_windows::CMD_AFTERHOOK,
            hmux2::src::cmd_load_buffer::CMD_AFTERHOOK,
            hmux2::src::cmd_lock_server::CMD_AFTERHOOK,
            hmux2::src::cmd_paste_buffer::CMD_AFTERHOOK,
            hmux2::src::cmd_pipe_pane::CMD_AFTERHOOK,
            hmux2::src::cmd_queue::CMD_AFTERHOOK,
            hmux2::src::cmd_refresh_client::CMD_AFTERHOOK,
            hmux2::src::cmd_rename_session::CMD_AFTERHOOK,
            hmux2::src::cmd_rename_window::CMD_AFTERHOOK,
            hmux2::src::cmd_resize_pane::CMD_AFTERHOOK,
            hmux2::src::cmd_resize_window::CMD_AFTERHOOK,
            hmux2::src::cmd_save_buffer::CMD_AFTERHOOK,
            hmux2::src::cmd_select_layout::CMD_AFTERHOOK,
            hmux2::src::cmd_send_keys::CMD_AFTERHOOK,
            hmux2::src::cmd_set_buffer::CMD_AFTERHOOK,
            hmux2::src::cmd_set_environment::CMD_AFTERHOOK,
            hmux2::src::cmd_set_option::CMD_AFTERHOOK,
            hmux2::src::cmd_show_environment::CMD_AFTERHOOK,
            hmux2::src::cmd_show_messages::CMD_AFTERHOOK,
            hmux2::src::cmd_show_options::CMD_AFTERHOOK,
            hmux2::src::cmd_show_prompt_history::CMD_AFTERHOOK,
            hmux2::src::cmd_swap_window::CMD_AFTERHOOK,
            hmux2::src::cmd_unbind_key::CMD_AFTERHOOK
        ]
    );
    constant!(
        CMD_BUFFER_USAGE,
        [
            hmux2::src::cmd_save_buffer::CMD_BUFFER_USAGE,
            hmux2::src::cmd_set_buffer::CMD_BUFFER_USAGE
        ]
    );
    constant!(
        CMD_CLIENT_CANFAIL,
        [
            hmux2::src::cmd_display_message::CMD_CLIENT_CANFAIL,
            hmux2::src::cmd_load_buffer::CMD_CLIENT_CANFAIL,
            hmux2::src::cmd_queue::CMD_CLIENT_CANFAIL,
            hmux2::src::cmd_send_keys::CMD_CLIENT_CANFAIL,
            hmux2::src::cmd_server_access::CMD_CLIENT_CANFAIL,
            hmux2::src::cmd_set_buffer::CMD_CLIENT_CANFAIL,
            hmux2::src::cmd_show_messages::CMD_CLIENT_CANFAIL
        ]
    );
    constant!(
        CMD_CLIENT_CFLAG,
        [
            hmux2::src::cmd_display_menu::CMD_CLIENT_CFLAG,
            hmux2::src::cmd_display_message::CMD_CLIENT_CFLAG,
            hmux2::src::cmd_queue::CMD_CLIENT_CFLAG,
            hmux2::src::cmd_send_keys::CMD_CLIENT_CFLAG,
            hmux2::src::cmd_switch_client::CMD_CLIENT_CFLAG
        ]
    );
    constant!(
        CMD_CLIENT_TFLAG,
        [
            hmux2::src::cmd_command_prompt::CMD_CLIENT_TFLAG,
            hmux2::src::cmd_confirm_before::CMD_CLIENT_TFLAG,
            hmux2::src::cmd_detach_client::CMD_CLIENT_TFLAG,
            hmux2::src::cmd_load_buffer::CMD_CLIENT_TFLAG,
            hmux2::src::cmd_lock_server::CMD_CLIENT_TFLAG,
            hmux2::src::cmd_queue::CMD_CLIENT_TFLAG,
            hmux2::src::cmd_refresh_client::CMD_CLIENT_TFLAG,
            hmux2::src::cmd_set_buffer::CMD_CLIENT_TFLAG,
            hmux2::src::cmd_show_messages::CMD_CLIENT_TFLAG
        ]
    );
    constant!(
        CMD_FIND_CANFAIL,
        [
            hmux2::src::cmd_detach_client::CMD_FIND_CANFAIL,
            hmux2::src::cmd_display_message::CMD_FIND_CANFAIL,
            hmux2::src::cmd_find::CMD_FIND_CANFAIL,
            hmux2::src::cmd_if_shell::CMD_FIND_CANFAIL,
            hmux2::src::cmd_new_session::CMD_FIND_CANFAIL,
            hmux2::src::cmd_run_shell::CMD_FIND_CANFAIL,
            hmux2::src::cmd_set_environment::CMD_FIND_CANFAIL,
            hmux2::src::cmd_set_option::CMD_FIND_CANFAIL,
            hmux2::src::cmd_show_environment::CMD_FIND_CANFAIL,
            hmux2::src::cmd_show_options::CMD_FIND_CANFAIL,
            hmux2::src::cmd_source_file::CMD_FIND_CANFAIL
        ]
    );
    constant!(
        CMD_FIND_DEFAULT_MARKED,
        [
            hmux2::src::cmd_find::CMD_FIND_DEFAULT_MARKED,
            hmux2::src::cmd_join_pane::CMD_FIND_DEFAULT_MARKED,
            hmux2::src::cmd_swap_pane::CMD_FIND_DEFAULT_MARKED,
            hmux2::src::cmd_swap_window::CMD_FIND_DEFAULT_MARKED
        ]
    );
    constant!(
        CMD_FIND_EXACT_SESSION,
        [hmux2::src::cmd_find::CMD_FIND_EXACT_SESSION]
    );
    constant!(
        CMD_FIND_EXACT_WINDOW,
        [hmux2::src::cmd_find::CMD_FIND_EXACT_WINDOW]
    );
    constant!(
        CMD_FIND_PREFER_UNATTACHED,
        [
            hmux2::src::cmd_attach_session::CMD_FIND_PREFER_UNATTACHED,
            hmux2::src::cmd_find::CMD_FIND_PREFER_UNATTACHED,
            hmux2::src::cmd_switch_client::CMD_FIND_PREFER_UNATTACHED
        ]
    );
    constant!(
        CMD_FIND_QUIET,
        [
            hmux2::src::cmd_find::CMD_FIND_QUIET,
            hmux2::src::cmd_move_window::CMD_FIND_QUIET
        ]
    );
    constant!(
        CMD_FIND_WINDOW_INDEX,
        [
            hmux2::src::cmd_break_pane::CMD_FIND_WINDOW_INDEX,
            hmux2::src::cmd_find::CMD_FIND_WINDOW_INDEX,
            hmux2::src::cmd_move_window::CMD_FIND_WINDOW_INDEX,
            hmux2::src::cmd_new_window::CMD_FIND_WINDOW_INDEX
        ]
    );
    constant!(
        CMD_LIST_PRINT_ESCAPED,
        [
            hmux2::src::cmd::CMD_LIST_PRINT_ESCAPED,
            hmux2::src::cmd_list_keys::CMD_LIST_PRINT_ESCAPED
        ]
    );
    constant!(
        CMD_LIST_PRINT_NO_GROUPS,
        [
            hmux2::src::cmd::CMD_LIST_PRINT_NO_GROUPS,
            hmux2::src::cmd_list_keys::CMD_LIST_PRINT_NO_GROUPS
        ]
    );
    constant!(
        CMD_PARSE_MAX_ENVIRON_LEN,
        [hmux2::src::cmd_parse::CMD_PARSE_MAX_ENVIRON_LEN]
    );
    constant!(
        CMD_PARSE_NOALIAS,
        [hmux2::src::cmd_parse::CMD_PARSE_NOALIAS]
    );
    constant!(
        CMD_PARSE_ONEGROUP,
        [hmux2::src::cmd_parse::CMD_PARSE_ONEGROUP]
    );
    constant!(
        CMD_PARSE_PARSEONLY,
        [
            hmux2::src::cfg::CMD_PARSE_PARSEONLY,
            hmux2::src::cmd_parse::CMD_PARSE_PARSEONLY,
            hmux2::src::cmd_source_file::CMD_PARSE_PARSEONLY
        ]
    );
    constant!(
        CMD_PARSE_QUIET,
        [
            hmux2::src::cfg::CMD_PARSE_QUIET,
            hmux2::src::cmd_source_file::CMD_PARSE_QUIET
        ]
    );
    constant!(
        CMD_PARSE_VERBOSE,
        [
            hmux2::src::cmd_parse::CMD_PARSE_VERBOSE,
            hmux2::src::cmd_source_file::CMD_PARSE_VERBOSE
        ]
    );
    constant!(
        CMD_READONLY,
        [
            hmux2::src::cmd_attach_session::CMD_READONLY,
            hmux2::src::cmd_copy_mode::CMD_READONLY,
            hmux2::src::cmd_detach_client::CMD_READONLY,
            hmux2::src::cmd_list_clients::CMD_READONLY,
            hmux2::src::cmd_send_keys::CMD_READONLY,
            hmux2::src::cmd_switch_client::CMD_READONLY,
            hmux2::src::key_bindings::CMD_READONLY,
            hmux2::src::server_client::CMD_READONLY
        ]
    );
    constant!(
        CMD_SOURCE_FILE_DEPTH_LIMIT,
        [hmux2::src::cmd_source_file::CMD_SOURCE_FILE_DEPTH_LIMIT]
    );
    constant!(
        CMD_STARTSERVER,
        [
            hmux2::src::client::CMD_STARTSERVER,
            hmux2::src::cmd_attach_session::CMD_STARTSERVER,
            hmux2::src::cmd_kill_server::CMD_STARTSERVER,
            hmux2::src::cmd_list_commands::CMD_STARTSERVER,
            hmux2::src::cmd_list_keys::CMD_STARTSERVER,
            hmux2::src::cmd_new_session::CMD_STARTSERVER
        ]
    );
    constant!(
        CMD_TARGET_CLIENT_USAGE,
        [
            hmux2::src::cmd_detach_client::CMD_TARGET_CLIENT_USAGE,
            hmux2::src::cmd_lock_server::CMD_TARGET_CLIENT_USAGE
        ]
    );
    constant!(
        CMD_TARGET_PANE_USAGE,
        [hmux2::src::cmd_copy_mode::CMD_TARGET_PANE_USAGE]
    );
    constant!(
        CMD_TARGET_SESSION_USAGE,
        [
            hmux2::src::cmd_lock_server::CMD_TARGET_SESSION_USAGE,
            hmux2::src::cmd_new_session::CMD_TARGET_SESSION_USAGE,
            hmux2::src::cmd_select_window::CMD_TARGET_SESSION_USAGE
        ]
    );
    constant!(
        CMD_TARGET_WINDOW_USAGE,
        [hmux2::src::cmd_select_layout::CMD_TARGET_WINDOW_USAGE]
    );
    constant!(
        COLOUR_FLAG_256,
        [
            hmux2::src::cmd_capture_pane::COLOUR_FLAG_256,
            hmux2::src::colour::COLOUR_FLAG_256,
            hmux2::src::grid::COLOUR_FLAG_256,
            hmux2::src::input::COLOUR_FLAG_256,
            hmux2::src::tty::COLOUR_FLAG_256
        ]
    );
    constant!(
        COLOUR_FLAG_RGB,
        [
            hmux2::src::colour::COLOUR_FLAG_RGB,
            hmux2::src::grid::COLOUR_FLAG_RGB,
            hmux2::src::tty::COLOUR_FLAG_RGB
        ]
    );
    constant!(
        COLOUR_FLAG_THEME,
        [
            hmux2::src::colour::COLOUR_FLAG_THEME,
            hmux2::src::grid::COLOUR_FLAG_THEME,
            hmux2::src::mode_tree::COLOUR_FLAG_THEME,
            hmux2::src::server_client::COLOUR_FLAG_THEME,
            hmux2::src::tty::COLOUR_FLAG_THEME,
            hmux2::src::window_customize::COLOUR_FLAG_THEME
        ]
    );
    constant!(
        COLOUR_THEME_BLACK,
        [
            hmux2::src::mode_tree::COLOUR_THEME_BLACK,
            hmux2::src::window_customize::COLOUR_THEME_BLACK
        ]
    );
    constant!(
        COLOUR_THEME_BLUE,
        [
            hmux2::src::mode_tree::COLOUR_THEME_BLUE,
            hmux2::src::window_customize::COLOUR_THEME_BLUE
        ]
    );
    constant!(
        COLOUR_THEME_COUNT,
        [
            hmux2::src::colour::COLOUR_THEME_COUNT,
            hmux2::src::server_client::COLOUR_THEME_COUNT,
            hmux2::src::tty::COLOUR_THEME_COUNT
        ]
    );
    constant!(
        COLOUR_THEME_CYAN,
        [
            hmux2::src::mode_tree::COLOUR_THEME_CYAN,
            hmux2::src::window_customize::COLOUR_THEME_CYAN
        ]
    );
    constant!(
        COLOUR_THEME_DARK_GREY,
        [
            hmux2::src::mode_tree::COLOUR_THEME_DARK_GREY,
            hmux2::src::window_customize::COLOUR_THEME_DARK_GREY
        ]
    );
    constant!(
        COLOUR_THEME_GREEN,
        [
            hmux2::src::mode_tree::COLOUR_THEME_GREEN,
            hmux2::src::window_customize::COLOUR_THEME_GREEN
        ]
    );
    constant!(
        COLOUR_THEME_LIGHT_GREY,
        [
            hmux2::src::mode_tree::COLOUR_THEME_LIGHT_GREY,
            hmux2::src::window_customize::COLOUR_THEME_LIGHT_GREY
        ]
    );
    constant!(
        COLOUR_THEME_MAGENTA,
        [
            hmux2::src::mode_tree::COLOUR_THEME_MAGENTA,
            hmux2::src::window_customize::COLOUR_THEME_MAGENTA
        ]
    );
    constant!(
        COLOUR_THEME_RED,
        [
            hmux2::src::mode_tree::COLOUR_THEME_RED,
            hmux2::src::window_customize::COLOUR_THEME_RED
        ]
    );
    constant!(
        COLOUR_THEME_WHITE,
        [
            hmux2::src::mode_tree::COLOUR_THEME_WHITE,
            hmux2::src::window_customize::COLOUR_THEME_WHITE
        ]
    );
    constant!(
        COLOUR_THEME_YELLOW,
        [
            hmux2::src::mode_tree::COLOUR_THEME_YELLOW,
            hmux2::src::window_customize::COLOUR_THEME_YELLOW
        ]
    );
    constant!(
        CURSOR_MODES,
        [
            hmux2::src::screen_redraw::CURSOR_MODES,
            hmux2::src::server_client::CURSOR_MODES,
            hmux2::src::tty::CURSOR_MODES
        ]
    );
    constant!(
        EVBUFFER_EOL_ANY,
        [
            hmux2::src::cmd_run_shell::EVBUFFER_EOL_ANY,
            hmux2::src::control::EVBUFFER_EOL_ANY,
            hmux2::src::server_client::EVBUFFER_EOL_ANY
        ]
    );
    constant!(
        EVBUFFER_EOL_CRLF,
        [
            hmux2::src::cmd_run_shell::EVBUFFER_EOL_CRLF,
            hmux2::src::control::EVBUFFER_EOL_CRLF,
            hmux2::src::server_client::EVBUFFER_EOL_CRLF
        ]
    );
    constant!(
        EVBUFFER_EOL_CRLF_STRICT,
        [
            hmux2::src::cmd_run_shell::EVBUFFER_EOL_CRLF_STRICT,
            hmux2::src::control::EVBUFFER_EOL_CRLF_STRICT,
            hmux2::src::server_client::EVBUFFER_EOL_CRLF_STRICT
        ]
    );
    constant!(
        EVBUFFER_EOL_LF,
        [
            hmux2::src::cmd_run_shell::EVBUFFER_EOL_LF,
            hmux2::src::control::EVBUFFER_EOL_LF,
            hmux2::src::server_client::EVBUFFER_EOL_LF
        ]
    );
    constant!(
        EVBUFFER_EOL_NUL,
        [
            hmux2::src::cmd_run_shell::EVBUFFER_EOL_NUL,
            hmux2::src::control::EVBUFFER_EOL_NUL,
            hmux2::src::server_client::EVBUFFER_EOL_NUL
        ]
    );
    constant!(
        EV_PERSIST,
        [hmux2::src::proc::EV_PERSIST, hmux2::src::tty::EV_PERSIST]
    );
    constant!(
        EV_READ,
        [
            hmux2::src::cmd_pipe_pane::EV_READ,
            hmux2::src::control::EV_READ,
            hmux2::src::file::EV_READ,
            hmux2::src::job::EV_READ,
            hmux2::src::proc::EV_READ,
            hmux2::src::server::EV_READ,
            hmux2::src::server_client::EV_READ,
            hmux2::src::tty::EV_READ,
            hmux2::src::window::EV_READ
        ]
    );
    constant!(EV_SIGNAL, [hmux2::src::proc::EV_SIGNAL]);
    constant!(
        EV_TIMEOUT,
        [
            hmux2::src::alerts::EV_TIMEOUT,
            hmux2::src::cmd_run_shell::EV_TIMEOUT,
            hmux2::src::file::EV_TIMEOUT,
            hmux2::src::format::EV_TIMEOUT,
            hmux2::src::monitor::EV_TIMEOUT,
            hmux2::src::names::EV_TIMEOUT,
            hmux2::src::screen_write::EV_TIMEOUT,
            hmux2::src::server::EV_TIMEOUT,
            hmux2::src::server_client::EV_TIMEOUT,
            hmux2::src::session::EV_TIMEOUT,
            hmux2::src::tty_keys::EV_TIMEOUT
        ]
    );
    constant!(
        EV_WRITE,
        [
            hmux2::src::cmd_pipe_pane::EV_WRITE,
            hmux2::src::control::EV_WRITE,
            hmux2::src::file::EV_WRITE,
            hmux2::src::job::EV_WRITE,
            hmux2::src::proc::EV_WRITE,
            hmux2::src::tty::EV_WRITE,
            hmux2::src::window::EV_WRITE
        ]
    );
    constant!(
        EXTENDED_KEY_MODES,
        [
            hmux2::src::format::EXTENDED_KEY_MODES,
            hmux2::src::input::EXTENDED_KEY_MODES,
            hmux2::src::input_keys::EXTENDED_KEY_MODES,
            hmux2::src::screen::EXTENDED_KEY_MODES,
            hmux2::src::screen_write::EXTENDED_KEY_MODES
        ]
    );
    constant!(
        HANGULJAMO_STATE_CHOSEONG,
        [
            hmux2::src::screen_write::HANGULJAMO_STATE_CHOSEONG,
            hmux2::src::utf8_combined::HANGULJAMO_STATE_CHOSEONG
        ]
    );
    constant!(
        HANGULJAMO_STATE_COMPOSABLE,
        [
            hmux2::src::screen_write::HANGULJAMO_STATE_COMPOSABLE,
            hmux2::src::utf8_combined::HANGULJAMO_STATE_COMPOSABLE
        ]
    );
    constant!(
        HANGULJAMO_STATE_NOT_COMPOSABLE,
        [
            hmux2::src::screen_write::HANGULJAMO_STATE_NOT_COMPOSABLE,
            hmux2::src::utf8_combined::HANGULJAMO_STATE_NOT_COMPOSABLE
        ]
    );
    constant!(
        HANGULJAMO_STATE_NOT_HANGULJAMO,
        [
            hmux2::src::screen_write::HANGULJAMO_STATE_NOT_HANGULJAMO,
            hmux2::src::utf8_combined::HANGULJAMO_STATE_NOT_HANGULJAMO
        ]
    );
    constant!(
        MENU_NOMOUSE,
        [
            hmux2::src::cmd_display_menu::MENU_NOMOUSE,
            hmux2::src::menu::MENU_NOMOUSE
        ]
    );
    constant!(
        MENU_STAYOPEN,
        [
            hmux2::src::cmd_display_menu::MENU_STAYOPEN,
            hmux2::src::menu::MENU_STAYOPEN
        ]
    );
    constant!(MENU_TAB, [hmux2::src::menu::MENU_TAB]);
    constant!(
        MODE_BRACKETPASTE,
        [
            hmux2::src::cmd_paste_buffer::MODE_BRACKETPASTE,
            hmux2::src::format::MODE_BRACKETPASTE,
            hmux2::src::input::MODE_BRACKETPASTE,
            hmux2::src::input_keys::MODE_BRACKETPASTE,
            hmux2::src::screen::MODE_BRACKETPASTE,
            hmux2::src::server_client::MODE_BRACKETPASTE,
            hmux2::src::window::MODE_BRACKETPASTE
        ]
    );
    constant!(
        MODE_CRLF,
        [
            hmux2::src::input::MODE_CRLF,
            hmux2::src::screen::MODE_CRLF,
            hmux2::src::spawn::MODE_CRLF
        ]
    );
    constant!(
        MODE_CURSOR,
        [
            hmux2::src::format::MODE_CURSOR,
            hmux2::src::input::MODE_CURSOR,
            hmux2::src::menu::MODE_CURSOR,
            hmux2::src::mode_tree::MODE_CURSOR,
            hmux2::src::screen::MODE_CURSOR,
            hmux2::src::screen_redraw::MODE_CURSOR,
            hmux2::src::screen_write::MODE_CURSOR,
            hmux2::src::server_client::MODE_CURSOR,
            hmux2::src::server_fn::MODE_CURSOR,
            hmux2::src::spawn::MODE_CURSOR,
            hmux2::src::tty::MODE_CURSOR,
            hmux2::src::window_clock::MODE_CURSOR,
            hmux2::src::window_panes::MODE_CURSOR,
            hmux2::src::window_switch::MODE_CURSOR
        ]
    );
    constant!(
        MODE_CURSOR_BLINKING,
        [
            hmux2::src::format::MODE_CURSOR_BLINKING,
            hmux2::src::input::MODE_CURSOR_BLINKING,
            hmux2::src::screen::MODE_CURSOR_BLINKING,
            hmux2::src::screen_redraw::MODE_CURSOR_BLINKING,
            hmux2::src::server_client::MODE_CURSOR_BLINKING,
            hmux2::src::tty::MODE_CURSOR_BLINKING
        ]
    );
    constant!(
        MODE_CURSOR_BLINKING_SET,
        [
            hmux2::src::format::MODE_CURSOR_BLINKING_SET,
            hmux2::src::input::MODE_CURSOR_BLINKING_SET,
            hmux2::src::screen::MODE_CURSOR_BLINKING_SET,
            hmux2::src::tty::MODE_CURSOR_BLINKING_SET
        ]
    );
    constant!(
        MODE_CURSOR_VERY_VISIBLE,
        [
            hmux2::src::format::MODE_CURSOR_VERY_VISIBLE,
            hmux2::src::input::MODE_CURSOR_VERY_VISIBLE,
            hmux2::src::screen::MODE_CURSOR_VERY_VISIBLE,
            hmux2::src::screen_redraw::MODE_CURSOR_VERY_VISIBLE,
            hmux2::src::server_client::MODE_CURSOR_VERY_VISIBLE,
            hmux2::src::tty::MODE_CURSOR_VERY_VISIBLE
        ]
    );
    constant!(
        MODE_FOCUSON,
        [
            hmux2::src::format::MODE_FOCUSON,
            hmux2::src::input::MODE_FOCUSON,
            hmux2::src::screen::MODE_FOCUSON,
            hmux2::src::window::MODE_FOCUSON
        ]
    );
    constant!(
        MODE_INSERT,
        [
            hmux2::src::format::MODE_INSERT,
            hmux2::src::input::MODE_INSERT,
            hmux2::src::screen::MODE_INSERT,
            hmux2::src::screen_write::MODE_INSERT
        ]
    );
    constant!(
        MODE_KCURSOR,
        [
            hmux2::src::format::MODE_KCURSOR,
            hmux2::src::input::MODE_KCURSOR,
            hmux2::src::input_keys::MODE_KCURSOR,
            hmux2::src::screen::MODE_KCURSOR
        ]
    );
    constant!(
        MODE_KEYS_EXTENDED,
        [
            hmux2::src::format::MODE_KEYS_EXTENDED,
            hmux2::src::input::MODE_KEYS_EXTENDED,
            hmux2::src::input_keys::MODE_KEYS_EXTENDED,
            hmux2::src::screen::MODE_KEYS_EXTENDED,
            hmux2::src::screen_write::MODE_KEYS_EXTENDED
        ]
    );
    constant!(
        MODE_KEYS_EXTENDED_2,
        [
            hmux2::src::format::MODE_KEYS_EXTENDED_2,
            hmux2::src::input::MODE_KEYS_EXTENDED_2,
            hmux2::src::input_keys::MODE_KEYS_EXTENDED_2,
            hmux2::src::screen::MODE_KEYS_EXTENDED_2,
            hmux2::src::screen_write::MODE_KEYS_EXTENDED_2
        ]
    );
    constant!(
        MODE_KKEYPAD,
        [
            hmux2::src::format::MODE_KKEYPAD,
            hmux2::src::input::MODE_KKEYPAD,
            hmux2::src::input_keys::MODE_KKEYPAD,
            hmux2::src::screen::MODE_KKEYPAD
        ]
    );
    constant!(
        MODE_MOUSE_ALL,
        [
            hmux2::src::format::MODE_MOUSE_ALL,
            hmux2::src::input::MODE_MOUSE_ALL,
            hmux2::src::input_keys::MODE_MOUSE_ALL,
            hmux2::src::menu::MODE_MOUSE_ALL,
            hmux2::src::screen::MODE_MOUSE_ALL,
            hmux2::src::server_client::MODE_MOUSE_ALL,
            hmux2::src::tty::MODE_MOUSE_ALL
        ]
    );
    constant!(
        MODE_MOUSE_BUTTON,
        [
            hmux2::src::format::MODE_MOUSE_BUTTON,
            hmux2::src::input::MODE_MOUSE_BUTTON,
            hmux2::src::input_keys::MODE_MOUSE_BUTTON,
            hmux2::src::menu::MODE_MOUSE_BUTTON,
            hmux2::src::screen::MODE_MOUSE_BUTTON,
            hmux2::src::server_client::MODE_MOUSE_BUTTON,
            hmux2::src::tty::MODE_MOUSE_BUTTON
        ]
    );
    constant!(
        MODE_MOUSE_SGR,
        [
            hmux2::src::format::MODE_MOUSE_SGR,
            hmux2::src::input::MODE_MOUSE_SGR,
            hmux2::src::input_keys::MODE_MOUSE_SGR,
            hmux2::src::screen::MODE_MOUSE_SGR
        ]
    );
    constant!(
        MODE_MOUSE_STANDARD,
        [
            hmux2::src::format::MODE_MOUSE_STANDARD,
            hmux2::src::input::MODE_MOUSE_STANDARD,
            hmux2::src::input_keys::MODE_MOUSE_STANDARD,
            hmux2::src::screen::MODE_MOUSE_STANDARD,
            hmux2::src::server_client::MODE_MOUSE_STANDARD,
            hmux2::src::tty::MODE_MOUSE_STANDARD
        ]
    );
    constant!(
        MODE_MOUSE_UTF8,
        [
            hmux2::src::format::MODE_MOUSE_UTF8,
            hmux2::src::input::MODE_MOUSE_UTF8,
            hmux2::src::input_keys::MODE_MOUSE_UTF8,
            hmux2::src::screen::MODE_MOUSE_UTF8
        ]
    );
    constant!(
        MODE_ORIGIN,
        [
            hmux2::src::format::MODE_ORIGIN,
            hmux2::src::input::MODE_ORIGIN,
            hmux2::src::screen::MODE_ORIGIN,
            hmux2::src::screen_write::MODE_ORIGIN
        ]
    );
    constant!(
        MODE_SYNC,
        [
            hmux2::src::format::MODE_SYNC,
            hmux2::src::input::MODE_SYNC,
            hmux2::src::screen::MODE_SYNC,
            hmux2::src::screen_redraw::MODE_SYNC,
            hmux2::src::screen_write::MODE_SYNC,
            hmux2::src::server_client::MODE_SYNC
        ]
    );
    constant!(
        MODE_THEME_UPDATES,
        [
            hmux2::src::format::MODE_THEME_UPDATES,
            hmux2::src::input::MODE_THEME_UPDATES,
            hmux2::src::screen::MODE_THEME_UPDATES,
            hmux2::src::window::MODE_THEME_UPDATES
        ]
    );
    constant!(
        MODE_WRAP,
        [
            hmux2::src::format::MODE_WRAP,
            hmux2::src::input::MODE_WRAP,
            hmux2::src::screen::MODE_WRAP,
            hmux2::src::screen_write::MODE_WRAP
        ]
    );
    constant!(
        MONITOR_ALL_PANES,
        [
            hmux2::src::cmd_refresh_client::MONITOR_ALL_PANES,
            hmux2::src::cmd_set_option::MONITOR_ALL_PANES,
            hmux2::src::cmd_show_options::MONITOR_ALL_PANES,
            hmux2::src::control::MONITOR_ALL_PANES,
            hmux2::src::hooks::MONITOR_ALL_PANES,
            hmux2::src::monitor::MONITOR_ALL_PANES
        ]
    );
    constant!(
        MONITOR_ALL_WINDOWS,
        [
            hmux2::src::cmd_refresh_client::MONITOR_ALL_WINDOWS,
            hmux2::src::cmd_set_option::MONITOR_ALL_WINDOWS,
            hmux2::src::cmd_show_options::MONITOR_ALL_WINDOWS,
            hmux2::src::control::MONITOR_ALL_WINDOWS,
            hmux2::src::hooks::MONITOR_ALL_WINDOWS,
            hmux2::src::monitor::MONITOR_ALL_WINDOWS
        ]
    );
    constant!(
        MONITOR_NOTIFY_INITIAL,
        [
            hmux2::src::control::MONITOR_NOTIFY_INITIAL,
            hmux2::src::monitor::MONITOR_NOTIFY_INITIAL
        ]
    );
    constant!(
        MONITOR_NOTIFY_TRUE,
        [
            hmux2::src::cmd_set_option::MONITOR_NOTIFY_TRUE,
            hmux2::src::monitor::MONITOR_NOTIFY_TRUE
        ]
    );
    constant!(
        MONITOR_PANE,
        [
            hmux2::src::cmd_refresh_client::MONITOR_PANE,
            hmux2::src::cmd_set_option::MONITOR_PANE,
            hmux2::src::cmd_show_options::MONITOR_PANE,
            hmux2::src::control::MONITOR_PANE,
            hmux2::src::hooks::MONITOR_PANE,
            hmux2::src::monitor::MONITOR_PANE
        ]
    );
    constant!(
        MONITOR_SESSION,
        [
            hmux2::src::cmd_refresh_client::MONITOR_SESSION,
            hmux2::src::cmd_set_option::MONITOR_SESSION,
            hmux2::src::cmd_show_options::MONITOR_SESSION,
            hmux2::src::control::MONITOR_SESSION,
            hmux2::src::hooks::MONITOR_SESSION,
            hmux2::src::monitor::MONITOR_SESSION
        ]
    );
    constant!(
        MONITOR_WINDOW,
        [
            hmux2::src::cmd_refresh_client::MONITOR_WINDOW,
            hmux2::src::cmd_set_option::MONITOR_WINDOW,
            hmux2::src::cmd_show_options::MONITOR_WINDOW,
            hmux2::src::control::MONITOR_WINDOW,
            hmux2::src::hooks::MONITOR_WINDOW,
            hmux2::src::monitor::MONITOR_WINDOW
        ]
    );
    constant!(
        MOUSE_BUTTON_1,
        [
            hmux2::src::menu::MOUSE_BUTTON_1,
            hmux2::src::mode_tree::MOUSE_BUTTON_1,
            hmux2::src::popup::MOUSE_BUTTON_1,
            hmux2::src::server_client::MOUSE_BUTTON_1,
            hmux2::src::status::MOUSE_BUTTON_1,
            hmux2::src::window::MOUSE_BUTTON_1,
            hmux2::src::window_switch::MOUSE_BUTTON_1
        ]
    );
    constant!(
        MOUSE_BUTTON_10,
        [hmux2::src::server_client::MOUSE_BUTTON_10]
    );
    constant!(
        MOUSE_BUTTON_11,
        [hmux2::src::server_client::MOUSE_BUTTON_11]
    );
    constant!(MOUSE_BUTTON_2, [hmux2::src::server_client::MOUSE_BUTTON_2]);
    constant!(
        MOUSE_BUTTON_3,
        [
            hmux2::src::popup::MOUSE_BUTTON_3,
            hmux2::src::server_client::MOUSE_BUTTON_3
        ]
    );
    constant!(MOUSE_BUTTON_6, [hmux2::src::server_client::MOUSE_BUTTON_6]);
    constant!(MOUSE_BUTTON_7, [hmux2::src::server_client::MOUSE_BUTTON_7]);
    constant!(MOUSE_BUTTON_8, [hmux2::src::server_client::MOUSE_BUTTON_8]);
    constant!(MOUSE_BUTTON_9, [hmux2::src::server_client::MOUSE_BUTTON_9]);
    constant!(
        MOUSE_MASK_BUTTONS,
        [
            hmux2::src::input_keys::MOUSE_MASK_BUTTONS,
            hmux2::src::menu::MOUSE_MASK_BUTTONS,
            hmux2::src::mode_tree::MOUSE_MASK_BUTTONS,
            hmux2::src::popup::MOUSE_MASK_BUTTONS,
            hmux2::src::server_client::MOUSE_MASK_BUTTONS,
            hmux2::src::status::MOUSE_MASK_BUTTONS,
            hmux2::src::tty_keys::MOUSE_MASK_BUTTONS,
            hmux2::src::window::MOUSE_MASK_BUTTONS,
            hmux2::src::window_copy::MOUSE_MASK_BUTTONS,
            hmux2::src::window_switch::MOUSE_MASK_BUTTONS
        ]
    );
    constant!(
        MOUSE_MASK_CTRL,
        [
            hmux2::src::popup::MOUSE_MASK_CTRL,
            hmux2::src::server_client::MOUSE_MASK_CTRL
        ]
    );
    constant!(
        MOUSE_MASK_DRAG,
        [
            hmux2::src::input_keys::MOUSE_MASK_DRAG,
            hmux2::src::menu::MOUSE_MASK_DRAG,
            hmux2::src::mode_tree::MOUSE_MASK_DRAG,
            hmux2::src::popup::MOUSE_MASK_DRAG,
            hmux2::src::server_client::MOUSE_MASK_DRAG,
            hmux2::src::status::MOUSE_MASK_DRAG,
            hmux2::src::window::MOUSE_MASK_DRAG,
            hmux2::src::window_switch::MOUSE_MASK_DRAG
        ]
    );
    constant!(
        MOUSE_MASK_META,
        [
            hmux2::src::popup::MOUSE_MASK_META,
            hmux2::src::server_client::MOUSE_MASK_META
        ]
    );
    constant!(
        MOUSE_MASK_MODIFIERS,
        [hmux2::src::popup::MOUSE_MASK_MODIFIERS]
    );
    constant!(
        MOUSE_MASK_SHIFT,
        [
            hmux2::src::popup::MOUSE_MASK_SHIFT,
            hmux2::src::server_client::MOUSE_MASK_SHIFT
        ]
    );
    constant!(
        MOUSE_PARAM_BTN_OFF,
        [
            hmux2::src::input_keys::MOUSE_PARAM_BTN_OFF,
            hmux2::src::tty_keys::MOUSE_PARAM_BTN_OFF
        ]
    );
    constant!(MOUSE_PARAM_MAX, [hmux2::src::input_keys::MOUSE_PARAM_MAX]);
    constant!(
        MOUSE_PARAM_POS_OFF,
        [
            hmux2::src::input_keys::MOUSE_PARAM_POS_OFF,
            hmux2::src::tty_keys::MOUSE_PARAM_POS_OFF
        ]
    );
    constant!(
        MOUSE_PARAM_UTF8_MAX,
        [hmux2::src::input_keys::MOUSE_PARAM_UTF8_MAX]
    );
    constant!(
        MOUSE_WHEEL_DOWN,
        [
            hmux2::src::menu::MOUSE_WHEEL_DOWN,
            hmux2::src::server_client::MOUSE_WHEEL_DOWN,
            hmux2::src::tty_keys::MOUSE_WHEEL_DOWN,
            hmux2::src::window_copy::MOUSE_WHEEL_DOWN
        ]
    );
    constant!(
        MOUSE_WHEEL_UP,
        [
            hmux2::src::menu::MOUSE_WHEEL_UP,
            hmux2::src::server_client::MOUSE_WHEEL_UP,
            hmux2::src::tty_keys::MOUSE_WHEEL_UP,
            hmux2::src::window_copy::MOUSE_WHEEL_UP
        ]
    );
    constant!(
        OPTIONS_TABLE_IS_ARRAY,
        [
            hmux2::src::options::OPTIONS_TABLE_IS_ARRAY,
            hmux2::src::options_table::OPTIONS_TABLE_IS_ARRAY,
            hmux2::src::window_customize::OPTIONS_TABLE_IS_ARRAY
        ]
    );
    constant!(
        OPTIONS_TABLE_IS_COLOUR,
        [
            hmux2::src::options::OPTIONS_TABLE_IS_COLOUR,
            hmux2::src::options_table::OPTIONS_TABLE_IS_COLOUR,
            hmux2::src::window_customize::OPTIONS_TABLE_IS_COLOUR
        ]
    );
    constant!(
        OPTIONS_TABLE_IS_HOOK,
        [
            hmux2::src::cmd_show_options::OPTIONS_TABLE_IS_HOOK,
            hmux2::src::format::OPTIONS_TABLE_IS_HOOK,
            hmux2::src::hooks::OPTIONS_TABLE_IS_HOOK,
            hmux2::src::options_table::OPTIONS_TABLE_IS_HOOK,
            hmux2::src::window_customize::OPTIONS_TABLE_IS_HOOK
        ]
    );
    constant!(
        OPTIONS_TABLE_IS_STYLE,
        [
            hmux2::src::options::OPTIONS_TABLE_IS_STYLE,
            hmux2::src::options_table::OPTIONS_TABLE_IS_STYLE,
            hmux2::src::window_customize::OPTIONS_TABLE_IS_STYLE
        ]
    );
    constant!(
        OPTIONS_TABLE_NONE,
        [
            hmux2::src::cmd_set_option::OPTIONS_TABLE_NONE,
            hmux2::src::cmd_show_options::OPTIONS_TABLE_NONE,
            hmux2::src::options::OPTIONS_TABLE_NONE
        ]
    );
    constant!(
        OPTIONS_TABLE_PANE,
        [
            hmux2::src::options::OPTIONS_TABLE_PANE,
            hmux2::src::options_table::OPTIONS_TABLE_PANE,
            hmux2::src::window_customize::OPTIONS_TABLE_PANE
        ]
    );
    constant!(
        OPTIONS_TABLE_SERVER,
        [
            hmux2::src::options::OPTIONS_TABLE_SERVER,
            hmux2::src::options_table::OPTIONS_TABLE_SERVER,
            hmux2::src::tmux::OPTIONS_TABLE_SERVER,
            hmux2::src::window_customize::OPTIONS_TABLE_SERVER
        ]
    );
    constant!(
        OPTIONS_TABLE_SESSION,
        [
            hmux2::src::options::OPTIONS_TABLE_SESSION,
            hmux2::src::options_table::OPTIONS_TABLE_SESSION,
            hmux2::src::tmux::OPTIONS_TABLE_SESSION,
            hmux2::src::window_customize::OPTIONS_TABLE_SESSION
        ]
    );
    constant!(
        OPTIONS_TABLE_STATUS_FORMAT1,
        [hmux2::src::options_table::OPTIONS_TABLE_STATUS_FORMAT1]
    );
    constant!(
        OPTIONS_TABLE_STATUS_FORMAT2,
        [hmux2::src::options_table::OPTIONS_TABLE_STATUS_FORMAT2]
    );
    constant!(
        OPTIONS_TABLE_STATUS_FORMAT3,
        [hmux2::src::options_table::OPTIONS_TABLE_STATUS_FORMAT3]
    );
    constant!(
        OPTIONS_TABLE_WINDOW,
        [
            hmux2::src::cmd_set_option::OPTIONS_TABLE_WINDOW,
            hmux2::src::options::OPTIONS_TABLE_WINDOW,
            hmux2::src::options_table::OPTIONS_TABLE_WINDOW,
            hmux2::src::tmux::OPTIONS_TABLE_WINDOW,
            hmux2::src::window_customize::OPTIONS_TABLE_WINDOW
        ]
    );
    constant!(
        PANE_ACTIVITY,
        [
            hmux2::src::input::PANE_ACTIVITY,
            hmux2::src::server_client::PANE_ACTIVITY
        ]
    );
    constant!(
        PANE_BORDER_ARROWS,
        [hmux2::src::screen_redraw::PANE_BORDER_ARROWS]
    );
    constant!(
        PANE_BORDER_BOTH,
        [hmux2::src::screen_redraw::PANE_BORDER_BOTH]
    );
    constant!(
        PANE_BORDER_COLOUR,
        [
            hmux2::src::options_table::PANE_BORDER_COLOUR,
            hmux2::src::screen_redraw::PANE_BORDER_COLOUR
        ]
    );
    constant!(
        PANE_CAPTUREALLKEYS,
        [
            hmux2::src::cmd_split_window::PANE_CAPTUREALLKEYS,
            hmux2::src::server_client::PANE_CAPTUREALLKEYS
        ]
    );
    constant!(
        PANE_CHANGED,
        [
            hmux2::src::cmd_break_pane::PANE_CHANGED,
            hmux2::src::input::PANE_CHANGED,
            hmux2::src::names::PANE_CHANGED,
            hmux2::src::options::PANE_CHANGED,
            hmux2::src::window::PANE_CHANGED
        ]
    );
    constant!(
        PANE_CLOSEONCANCEL,
        [
            hmux2::src::cmd_split_window::PANE_CLOSEONCANCEL,
            hmux2::src::server_client::PANE_CLOSEONCANCEL
        ]
    );
    constant!(
        PANE_CLOSEONCLICK,
        [
            hmux2::src::cmd_split_window::PANE_CLOSEONCLICK,
            hmux2::src::server_client::PANE_CLOSEONCLICK
        ]
    );
    constant!(
        PANE_CMDRUNNING,
        [
            hmux2::src::format::PANE_CMDRUNNING,
            hmux2::src::input::PANE_CMDRUNNING
        ]
    );
    constant!(PANE_DESTROYED, [hmux2::src::window::PANE_DESTROYED]);
    constant!(PANE_DROP, [hmux2::src::screen_write::PANE_DROP]);
    constant!(
        PANE_EMPTY,
        [
            hmux2::src::spawn::PANE_EMPTY,
            hmux2::src::window::PANE_EMPTY
        ]
    );
    constant!(
        PANE_EXITED,
        [
            hmux2::src::server::PANE_EXITED,
            hmux2::src::server_client::PANE_EXITED,
            hmux2::src::spawn::PANE_EXITED,
            hmux2::src::window::PANE_EXITED
        ]
    );
    constant!(
        PANE_FLOATOVERZOOM,
        [
            hmux2::src::server_fn::PANE_FLOATOVERZOOM,
            hmux2::src::spawn::PANE_FLOATOVERZOOM,
            hmux2::src::window::PANE_FLOATOVERZOOM
        ]
    );
    constant!(PANE_FOCUSED, [hmux2::src::window::PANE_FOCUSED]);
    constant!(
        PANE_INPUTOFF,
        [
            hmux2::src::cmd_paste_buffer::PANE_INPUTOFF,
            hmux2::src::cmd_select_pane::PANE_INPUTOFF,
            hmux2::src::format::PANE_INPUTOFF,
            hmux2::src::window::PANE_INPUTOFF
        ]
    );
    constant!(
        PANE_MAXIMUM,
        [
            hmux2::src::cmd_resize_pane::PANE_MAXIMUM,
            hmux2::src::layout::PANE_MAXIMUM,
            hmux2::src::layout_custom::PANE_MAXIMUM
        ]
    );
    constant!(
        PANE_MINIMUM,
        [
            hmux2::src::cmd_refresh_client::PANE_MINIMUM,
            hmux2::src::cmd_resize_pane::PANE_MINIMUM,
            hmux2::src::cmd_resize_window::PANE_MINIMUM,
            hmux2::src::cmd_split_window::PANE_MINIMUM,
            hmux2::src::format::PANE_MINIMUM,
            hmux2::src::layout::PANE_MINIMUM,
            hmux2::src::layout_custom::PANE_MINIMUM,
            hmux2::src::layout_set::PANE_MINIMUM,
            hmux2::src::resize::PANE_MINIMUM
        ]
    );
    constant!(PANE_NEWSTATUS, [hmux2::src::screen_redraw::PANE_NEWSTATUS]);
    constant!(
        PANE_REDRAW,
        [
            hmux2::src::cmd_resize_pane::PANE_REDRAW,
            hmux2::src::cmd_respawn_pane::PANE_REDRAW,
            hmux2::src::cmd_select_pane::PANE_REDRAW,
            hmux2::src::cmd_send_keys::PANE_REDRAW,
            hmux2::src::cmd_split_window::PANE_REDRAW,
            hmux2::src::mode_tree::PANE_REDRAW,
            hmux2::src::screen_write::PANE_REDRAW,
            hmux2::src::server_client::PANE_REDRAW,
            hmux2::src::server_fn::PANE_REDRAW,
            hmux2::src::window::PANE_REDRAW,
            hmux2::src::window_buffer::PANE_REDRAW,
            hmux2::src::window_client::PANE_REDRAW,
            hmux2::src::window_clock::PANE_REDRAW,
            hmux2::src::window_copy::PANE_REDRAW,
            hmux2::src::window_customize::PANE_REDRAW,
            hmux2::src::window_panes::PANE_REDRAW,
            hmux2::src::window_switch::PANE_REDRAW,
            hmux2::src::window_tree::PANE_REDRAW
        ]
    );
    constant!(
        PANE_REDRAWSCROLLBAR,
        [
            hmux2::src::layout::PANE_REDRAWSCROLLBAR,
            hmux2::src::screen_write::PANE_REDRAWSCROLLBAR,
            hmux2::src::server_client::PANE_REDRAWSCROLLBAR,
            hmux2::src::window::PANE_REDRAWSCROLLBAR,
            hmux2::src::window_copy::PANE_REDRAWSCROLLBAR
        ]
    );
    constant!(
        PANE_SCROLLBARS_ALWAYS,
        [
            hmux2::src::format::PANE_SCROLLBARS_ALWAYS,
            hmux2::src::layout::PANE_SCROLLBARS_ALWAYS,
            hmux2::src::window::PANE_SCROLLBARS_ALWAYS
        ]
    );
    constant!(
        PANE_SCROLLBARS_AUTOHIDE,
        [
            hmux2::src::server_client::PANE_SCROLLBARS_AUTOHIDE,
            hmux2::src::window::PANE_SCROLLBARS_AUTOHIDE
        ]
    );
    constant!(
        PANE_SCROLLBARS_CHARACTER,
        [hmux2::src::style::PANE_SCROLLBARS_CHARACTER]
    );
    constant!(
        PANE_SCROLLBARS_DEFAULT_PADDING,
        [hmux2::src::style::PANE_SCROLLBARS_DEFAULT_PADDING]
    );
    constant!(
        PANE_SCROLLBARS_DEFAULT_WIDTH,
        [hmux2::src::style::PANE_SCROLLBARS_DEFAULT_WIDTH]
    );
    constant!(
        PANE_SCROLLBARS_LEFT,
        [
            hmux2::src::cmd_resize_pane::PANE_SCROLLBARS_LEFT,
            hmux2::src::layout::PANE_SCROLLBARS_LEFT,
            hmux2::src::screen_redraw::PANE_SCROLLBARS_LEFT,
            hmux2::src::server_client::PANE_SCROLLBARS_LEFT,
            hmux2::src::window::PANE_SCROLLBARS_LEFT,
            hmux2::src::window_visible::PANE_SCROLLBARS_LEFT
        ]
    );
    constant!(
        PANE_SCROLLBARS_MODAL,
        [
            hmux2::src::server_client::PANE_SCROLLBARS_MODAL,
            hmux2::src::window::PANE_SCROLLBARS_MODAL
        ]
    );
    constant!(
        PANE_SCROLLBARS_OFF,
        [hmux2::src::options_table::PANE_SCROLLBARS_OFF]
    );
    constant!(
        PANE_SCROLLBARS_RIGHT,
        [
            hmux2::src::cmd_resize_pane::PANE_SCROLLBARS_RIGHT,
            hmux2::src::options_table::PANE_SCROLLBARS_RIGHT,
            hmux2::src::server_client::PANE_SCROLLBARS_RIGHT
        ]
    );
    constant!(
        PANE_STATUSDRAWN,
        [
            hmux2::src::format::PANE_STATUSDRAWN,
            hmux2::src::server_fn::PANE_STATUSDRAWN,
            hmux2::src::spawn::PANE_STATUSDRAWN
        ]
    );
    constant!(
        PANE_STATUSREADY,
        [
            hmux2::src::format::PANE_STATUSREADY,
            hmux2::src::server::PANE_STATUSREADY,
            hmux2::src::server_fn::PANE_STATUSREADY,
            hmux2::src::spawn::PANE_STATUSREADY,
            hmux2::src::window::PANE_STATUSREADY
        ]
    );
    constant!(
        PANE_STATUS_BOTTOM,
        [
            hmux2::src::cmd_resize_pane::PANE_STATUS_BOTTOM,
            hmux2::src::format::PANE_STATUS_BOTTOM,
            hmux2::src::layout::PANE_STATUS_BOTTOM,
            hmux2::src::screen_redraw::PANE_STATUS_BOTTOM,
            hmux2::src::server_client::PANE_STATUS_BOTTOM,
            hmux2::src::window::PANE_STATUS_BOTTOM,
            hmux2::src::window_panes::PANE_STATUS_BOTTOM
        ]
    );
    constant!(
        PANE_STATUS_BOTTOM_FLOATING,
        [hmux2::src::window::PANE_STATUS_BOTTOM_FLOATING]
    );
    constant!(
        PANE_STATUS_OFF,
        [
            hmux2::src::options_table::PANE_STATUS_OFF,
            hmux2::src::screen_redraw::PANE_STATUS_OFF,
            hmux2::src::server_client::PANE_STATUS_OFF,
            hmux2::src::window::PANE_STATUS_OFF,
            hmux2::src::window_border::PANE_STATUS_OFF
        ]
    );
    constant!(
        PANE_STATUS_TOP,
        [
            hmux2::src::cmd_resize_pane::PANE_STATUS_TOP,
            hmux2::src::format::PANE_STATUS_TOP,
            hmux2::src::layout::PANE_STATUS_TOP,
            hmux2::src::screen_redraw::PANE_STATUS_TOP,
            hmux2::src::server_client::PANE_STATUS_TOP,
            hmux2::src::window::PANE_STATUS_TOP,
            hmux2::src::window_panes::PANE_STATUS_TOP
        ]
    );
    constant!(
        PANE_STATUS_TOP_FLOATING,
        [hmux2::src::window::PANE_STATUS_TOP_FLOATING]
    );
    constant!(
        PANE_STYLECHANGED,
        [
            hmux2::src::cmd_break_pane::PANE_STYLECHANGED,
            hmux2::src::cmd_join_pane::PANE_STYLECHANGED,
            hmux2::src::cmd_select_pane::PANE_STYLECHANGED,
            hmux2::src::cmd_send_keys::PANE_STYLECHANGED,
            hmux2::src::cmd_split_window::PANE_STYLECHANGED,
            hmux2::src::cmd_swap_pane::PANE_STYLECHANGED,
            hmux2::src::input::PANE_STYLECHANGED,
            hmux2::src::options::PANE_STYLECHANGED,
            hmux2::src::server_client::PANE_STYLECHANGED,
            hmux2::src::tty::PANE_STYLECHANGED,
            hmux2::src::window::PANE_STYLECHANGED
        ]
    );
    constant!(
        PANE_THEMECHANGED,
        [
            hmux2::src::cmd_break_pane::PANE_THEMECHANGED,
            hmux2::src::cmd_join_pane::PANE_THEMECHANGED,
            hmux2::src::cmd_refresh_client::PANE_THEMECHANGED,
            hmux2::src::cmd_select_pane::PANE_THEMECHANGED,
            hmux2::src::cmd_send_keys::PANE_THEMECHANGED,
            hmux2::src::cmd_split_window::PANE_THEMECHANGED,
            hmux2::src::cmd_swap_pane::PANE_THEMECHANGED,
            hmux2::src::input::PANE_THEMECHANGED,
            hmux2::src::options::PANE_THEMECHANGED,
            hmux2::src::session::PANE_THEMECHANGED,
            hmux2::src::window::PANE_THEMECHANGED
        ]
    );
    constant!(
        PANE_UNSEENCHANGES,
        [
            hmux2::src::format::PANE_UNSEENCHANGES,
            hmux2::src::input::PANE_UNSEENCHANGES,
            hmux2::src::window::PANE_UNSEENCHANGES,
            hmux2::src::window_copy::PANE_UNSEENCHANGES
        ]
    );
    constant!(PANE_VISITED, [hmux2::src::window::PANE_VISITED]);
    constant!(
        PANE_ZOOMED,
        [
            hmux2::src::format::PANE_ZOOMED,
            hmux2::src::window::PANE_ZOOMED
        ]
    );
    constant!(
        PROMPT_ACCEPT,
        [
            hmux2::src::mode_tree::PROMPT_ACCEPT,
            hmux2::src::prompt::PROMPT_ACCEPT,
            hmux2::src::status::PROMPT_ACCEPT,
            hmux2::src::window_customize::PROMPT_ACCEPT,
            hmux2::src::window_tree::PROMPT_ACCEPT
        ]
    );
    constant!(
        PROMPT_BSPACE_EXIT,
        [
            hmux2::src::cmd_command_prompt::PROMPT_BSPACE_EXIT,
            hmux2::src::prompt::PROMPT_BSPACE_EXIT
        ]
    );
    constant!(
        PROMPT_CLOSE,
        [
            hmux2::src::cmd_command_prompt::PROMPT_CLOSE,
            hmux2::src::cmd_confirm_before::PROMPT_CLOSE,
            hmux2::src::mode_tree::PROMPT_CLOSE,
            hmux2::src::prompt::PROMPT_CLOSE,
            hmux2::src::status::PROMPT_CLOSE,
            hmux2::src::window::PROMPT_CLOSE,
            hmux2::src::window_customize::PROMPT_CLOSE,
            hmux2::src::window_switch::PROMPT_CLOSE,
            hmux2::src::window_tree::PROMPT_CLOSE
        ]
    );
    constant!(PROMPT_COMMANDMODE, [hmux2::src::prompt::PROMPT_COMMANDMODE]);
    constant!(
        PROMPT_CONTINUE,
        [
            hmux2::src::cmd_command_prompt::PROMPT_CONTINUE,
            hmux2::src::cmd_confirm_before::PROMPT_CONTINUE,
            hmux2::src::mode_tree::PROMPT_CONTINUE,
            hmux2::src::prompt::PROMPT_CONTINUE,
            hmux2::src::status::PROMPT_CONTINUE,
            hmux2::src::window::PROMPT_CONTINUE,
            hmux2::src::window_customize::PROMPT_CONTINUE,
            hmux2::src::window_switch::PROMPT_CONTINUE,
            hmux2::src::window_tree::PROMPT_CONTINUE
        ]
    );
    constant!(
        PROMPT_EDITARROWS,
        [
            hmux2::src::prompt::PROMPT_EDITARROWS,
            hmux2::src::window_switch::PROMPT_EDITARROWS
        ]
    );
    constant!(
        PROMPT_INCREMENTAL,
        [
            hmux2::src::cmd_command_prompt::PROMPT_INCREMENTAL,
            hmux2::src::prompt::PROMPT_INCREMENTAL,
            hmux2::src::status::PROMPT_INCREMENTAL,
            hmux2::src::window_switch::PROMPT_INCREMENTAL
        ]
    );
    constant!(
        PROMPT_ISMODE,
        [
            hmux2::src::mode_tree::PROMPT_ISMODE,
            hmux2::src::prompt::PROMPT_ISMODE,
            hmux2::src::window_switch::PROMPT_ISMODE
        ]
    );
    constant!(
        PROMPT_ISPANE,
        [
            hmux2::src::cmd_command_prompt::PROMPT_ISPANE,
            hmux2::src::prompt::PROMPT_ISPANE
        ]
    );
    constant!(
        PROMPT_KEY,
        [
            hmux2::src::cmd_command_prompt::PROMPT_KEY,
            hmux2::src::prompt::PROMPT_KEY
        ]
    );
    constant!(
        PROMPT_NOFORMAT,
        [
            hmux2::src::mode_tree::PROMPT_NOFORMAT,
            hmux2::src::prompt::PROMPT_NOFORMAT,
            hmux2::src::window_customize::PROMPT_NOFORMAT,
            hmux2::src::window_switch::PROMPT_NOFORMAT,
            hmux2::src::window_tree::PROMPT_NOFORMAT
        ]
    );
    constant!(
        PROMPT_NOFREEZE,
        [
            hmux2::src::cmd_command_prompt::PROMPT_NOFREEZE,
            hmux2::src::prompt::PROMPT_NOFREEZE,
            hmux2::src::status::PROMPT_NOFREEZE
        ]
    );
    constant!(
        PROMPT_NTYPES,
        [
            hmux2::src::cmd_show_prompt_history::PROMPT_NTYPES,
            hmux2::src::prompt::PROMPT_NTYPES,
            hmux2::src::prompt_history::PROMPT_NTYPES
        ]
    );
    constant!(
        PROMPT_NUMERIC,
        [
            hmux2::src::cmd_command_prompt::PROMPT_NUMERIC,
            hmux2::src::prompt::PROMPT_NUMERIC
        ]
    );
    constant!(PROMPT_QUOTENEXT, [hmux2::src::prompt::PROMPT_QUOTENEXT]);
    constant!(
        PROMPT_SINGLE,
        [
            hmux2::src::cmd_command_prompt::PROMPT_SINGLE,
            hmux2::src::cmd_confirm_before::PROMPT_SINGLE,
            hmux2::src::mode_tree::PROMPT_SINGLE,
            hmux2::src::prompt::PROMPT_SINGLE,
            hmux2::src::status::PROMPT_SINGLE,
            hmux2::src::window_customize::PROMPT_SINGLE,
            hmux2::src::window_tree::PROMPT_SINGLE
        ]
    );
    constant!(
        RB_BLACK,
        [
            hmux2::src::arguments::RB_BLACK,
            hmux2::src::cmd_wait_for::RB_BLACK,
            hmux2::src::control::RB_BLACK,
            hmux2::src::environ::RB_BLACK,
            hmux2::src::events_payload::RB_BLACK,
            hmux2::src::file::RB_BLACK,
            hmux2::src::format::RB_BLACK,
            hmux2::src::hyperlinks::RB_BLACK,
            hmux2::src::input_keys::RB_BLACK,
            hmux2::src::json::RB_BLACK,
            hmux2::src::key_bindings::RB_BLACK,
            hmux2::src::monitor::RB_BLACK,
            hmux2::src::options::RB_BLACK,
            hmux2::src::paste::RB_BLACK,
            hmux2::src::server_acl::RB_BLACK,
            hmux2::src::session::RB_BLACK,
            hmux2::src::utf8::RB_BLACK,
            hmux2::src::window::RB_BLACK
        ]
    );
    constant!(
        RB_INF,
        [
            hmux2::src::cmd_find::RB_INF,
            hmux2::src::format::RB_INF,
            hmux2::src::paste::RB_INF,
            hmux2::src::session::RB_INF,
            hmux2::src::window::RB_INF
        ]
    );
    constant!(
        RB_NEGINF,
        [
            hmux2::src::alerts::RB_NEGINF,
            hmux2::src::arguments::RB_NEGINF,
            hmux2::src::cfg::RB_NEGINF,
            hmux2::src::cmd_find::RB_NEGINF,
            hmux2::src::cmd_kill_session::RB_NEGINF,
            hmux2::src::cmd_kill_window::RB_NEGINF,
            hmux2::src::cmd_list_panes::RB_NEGINF,
            hmux2::src::cmd_new_session::RB_NEGINF,
            hmux2::src::cmd_new_window::RB_NEGINF,
            hmux2::src::cmd_wait_for::RB_NEGINF,
            hmux2::src::control::RB_NEGINF,
            hmux2::src::environ::RB_NEGINF,
            hmux2::src::events_payload::RB_NEGINF,
            hmux2::src::file::RB_NEGINF,
            hmux2::src::format::RB_NEGINF,
            hmux2::src::hyperlinks::RB_NEGINF,
            hmux2::src::input_keys::RB_NEGINF,
            hmux2::src::json::RB_NEGINF,
            hmux2::src::key_bindings::RB_NEGINF,
            hmux2::src::monitor::RB_NEGINF,
            hmux2::src::options::RB_NEGINF,
            hmux2::src::paste::RB_NEGINF,
            hmux2::src::resize::RB_NEGINF,
            hmux2::src::screen_redraw::RB_NEGINF,
            hmux2::src::server::RB_NEGINF,
            hmux2::src::server_acl::RB_NEGINF,
            hmux2::src::server_client::RB_NEGINF,
            hmux2::src::server_fn::RB_NEGINF,
            hmux2::src::session::RB_NEGINF,
            hmux2::src::sort::RB_NEGINF,
            hmux2::src::utf8::RB_NEGINF,
            hmux2::src::window::RB_NEGINF,
            hmux2::src::window_tree::RB_NEGINF
        ]
    );
    constant!(
        RB_RED,
        [
            hmux2::src::arguments::RB_RED,
            hmux2::src::cmd_wait_for::RB_RED,
            hmux2::src::control::RB_RED,
            hmux2::src::environ::RB_RED,
            hmux2::src::events_payload::RB_RED,
            hmux2::src::file::RB_RED,
            hmux2::src::format::RB_RED,
            hmux2::src::hyperlinks::RB_RED,
            hmux2::src::input_keys::RB_RED,
            hmux2::src::json::RB_RED,
            hmux2::src::key_bindings::RB_RED,
            hmux2::src::monitor::RB_RED,
            hmux2::src::options::RB_RED,
            hmux2::src::paste::RB_RED,
            hmux2::src::server_acl::RB_RED,
            hmux2::src::session::RB_RED,
            hmux2::src::utf8::RB_RED,
            hmux2::src::window::RB_RED
        ]
    );
    constant!(
        SPAWN_BEFORE,
        [
            hmux2::src::cmd_join_pane::SPAWN_BEFORE,
            hmux2::src::cmd_split_window::SPAWN_BEFORE,
            hmux2::src::layout::SPAWN_BEFORE,
            hmux2::src::window::SPAWN_BEFORE
        ]
    );
    constant!(
        SPAWN_DETACHED,
        [
            hmux2::src::cmd_new_window::SPAWN_DETACHED,
            hmux2::src::cmd_split_window::SPAWN_DETACHED,
            hmux2::src::spawn::SPAWN_DETACHED
        ]
    );
    constant!(
        SPAWN_EMPTY,
        [
            hmux2::src::cmd_new_window::SPAWN_EMPTY,
            hmux2::src::cmd_respawn_pane::SPAWN_EMPTY,
            hmux2::src::cmd_respawn_window::SPAWN_EMPTY,
            hmux2::src::cmd_split_window::SPAWN_EMPTY,
            hmux2::src::spawn::SPAWN_EMPTY
        ]
    );
    constant!(
        SPAWN_FLOATING,
        [
            hmux2::src::cmd_split_window::SPAWN_FLOATING,
            hmux2::src::spawn::SPAWN_FLOATING,
            hmux2::src::window::SPAWN_FLOATING
        ]
    );
    constant!(
        SPAWN_FLOATOVERZOOM,
        [
            hmux2::src::cmd_split_window::SPAWN_FLOATOVERZOOM,
            hmux2::src::layout::SPAWN_FLOATOVERZOOM,
            hmux2::src::spawn::SPAWN_FLOATOVERZOOM
        ]
    );
    constant!(
        SPAWN_FULLSIZE,
        [
            hmux2::src::cmd_join_pane::SPAWN_FULLSIZE,
            hmux2::src::cmd_split_window::SPAWN_FULLSIZE,
            hmux2::src::layout::SPAWN_FULLSIZE,
            hmux2::src::window::SPAWN_FULLSIZE
        ]
    );
    constant!(
        SPAWN_HORIZONTAL,
        [
            hmux2::src::cmd_join_pane::SPAWN_HORIZONTAL,
            hmux2::src::cmd_split_window::SPAWN_HORIZONTAL,
            hmux2::src::layout::SPAWN_HORIZONTAL
        ]
    );
    constant!(
        SPAWN_KILL,
        [
            hmux2::src::cmd_new_window::SPAWN_KILL,
            hmux2::src::cmd_respawn_pane::SPAWN_KILL,
            hmux2::src::cmd_respawn_window::SPAWN_KILL,
            hmux2::src::spawn::SPAWN_KILL
        ]
    );
    constant!(
        SPAWN_MODAL,
        [
            hmux2::src::cmd_split_window::SPAWN_MODAL,
            hmux2::src::spawn::SPAWN_MODAL
        ]
    );
    constant!(SPAWN_NONOTIFY, [hmux2::src::spawn::SPAWN_NONOTIFY]);
    constant!(
        SPAWN_RESPAWN,
        [
            hmux2::src::cmd_respawn_pane::SPAWN_RESPAWN,
            hmux2::src::cmd_respawn_window::SPAWN_RESPAWN,
            hmux2::src::spawn::SPAWN_RESPAWN
        ]
    );
    constant!(
        SPAWN_SPLIT,
        [
            hmux2::src::cmd_split_window::SPAWN_SPLIT,
            hmux2::src::layout::SPAWN_SPLIT
        ]
    );
    constant!(
        SPAWN_ZOOM,
        [
            hmux2::src::cmd_split_window::SPAWN_ZOOM,
            hmux2::src::layout::SPAWN_ZOOM,
            hmux2::src::spawn::SPAWN_ZOOM
        ]
    );
    constant!(
        TERM_256COLOURS,
        [
            hmux2::src::colour::TERM_256COLOURS,
            hmux2::src::format::TERM_256COLOURS,
            hmux2::src::tty::TERM_256COLOURS,
            hmux2::src::tty_features::TERM_256COLOURS
        ]
    );
    constant!(
        TERM_DECFRA,
        [
            hmux2::src::tty::TERM_DECFRA,
            hmux2::src::tty_features::TERM_DECFRA,
            hmux2::src::tty_term::TERM_DECFRA
        ]
    );
    constant!(
        TERM_DECSLRM,
        [
            hmux2::src::tty::TERM_DECSLRM,
            hmux2::src::tty_features::TERM_DECSLRM,
            hmux2::src::tty_term::TERM_DECSLRM
        ]
    );
    constant!(
        TERM_INVALIDMS,
        [
            hmux2::src::tty_term::TERM_INVALIDMS,
            hmux2::src::window_client::TERM_INVALIDMS
        ]
    );
    constant!(
        TERM_NOAM,
        [hmux2::src::tty::TERM_NOAM, hmux2::src::tty_term::TERM_NOAM]
    );
    constant!(
        TERM_RGBCOLOURS,
        [
            hmux2::src::colour::TERM_RGBCOLOURS,
            hmux2::src::format::TERM_RGBCOLOURS,
            hmux2::src::tty::TERM_RGBCOLOURS,
            hmux2::src::tty_features::TERM_RGBCOLOURS,
            hmux2::src::tty_term::TERM_RGBCOLOURS
        ]
    );
    constant!(
        TERM_SIXEL,
        [
            hmux2::src::tty_features::TERM_SIXEL,
            hmux2::src::tty_term::TERM_SIXEL
        ]
    );
    constant!(
        TERM_VT100LIKE,
        [
            hmux2::src::tty::TERM_VT100LIKE,
            hmux2::src::tty_term::TERM_VT100LIKE
        ]
    );
    constant!(TEXT, [hmux2::src::screen_write::TEXT]);
    constant!(
        TTY_ALL_REQUEST_FLAGS,
        [
            hmux2::src::tty::TTY_ALL_REQUEST_FLAGS,
            hmux2::src::tty_keys::TTY_ALL_REQUEST_FLAGS
        ]
    );
    constant!(
        TTY_BLOCK,
        [
            hmux2::src::server_client::TTY_BLOCK,
            hmux2::src::tty::TTY_BLOCK
        ]
    );
    constant!(TTY_BLOCK_INTERVAL, [hmux2::src::tty::TTY_BLOCK_INTERVAL]);
    constant!(TTY_BRACKETPASTE, [hmux2::src::tty_keys::TTY_BRACKETPASTE]);
    constant!(
        TTY_CTX_CELL_INVALIDATE,
        [
            hmux2::src::screen_write::TTY_CTX_CELL_INVALIDATE,
            hmux2::src::tty::TTY_CTX_CELL_INVALIDATE
        ]
    );
    constant!(
        TTY_CTX_INVISIBLE_PANES,
        [
            hmux2::src::screen_write::TTY_CTX_INVISIBLE_PANES,
            hmux2::src::tty::TTY_CTX_INVISIBLE_PANES
        ]
    );
    constant!(
        TTY_CTX_OVERLAY_SYNC,
        [
            hmux2::src::screen_write::TTY_CTX_OVERLAY_SYNC,
            hmux2::src::tty::TTY_CTX_OVERLAY_SYNC
        ]
    );
    constant!(
        TTY_CTX_PANE_OBSCURED,
        [
            hmux2::src::screen_write::TTY_CTX_PANE_OBSCURED,
            hmux2::src::tty::TTY_CTX_PANE_OBSCURED
        ]
    );
    constant!(
        TTY_CTX_SYNC,
        [
            hmux2::src::screen_write::TTY_CTX_SYNC,
            hmux2::src::tty::TTY_CTX_SYNC
        ]
    );
    constant!(
        TTY_CTX_WINDOW_BIGGER,
        [
            hmux2::src::popup::TTY_CTX_WINDOW_BIGGER,
            hmux2::src::screen_write::TTY_CTX_WINDOW_BIGGER,
            hmux2::src::tty::TTY_CTX_WINDOW_BIGGER
        ]
    );
    constant!(
        TTY_CTX_WRAPPED,
        [
            hmux2::src::screen_write::TTY_CTX_WRAPPED,
            hmux2::src::tty::TTY_CTX_WRAPPED
        ]
    );
    constant!(
        TTY_FREEZE,
        [
            hmux2::src::server_client::TTY_FREEZE,
            hmux2::src::status::TTY_FREEZE,
            hmux2::src::tty::TTY_FREEZE
        ]
    );
    constant!(
        TTY_HAVEDA,
        [
            hmux2::src::tty::TTY_HAVEDA,
            hmux2::src::tty_keys::TTY_HAVEDA
        ]
    );
    constant!(
        TTY_HAVEDA2,
        [
            hmux2::src::tty::TTY_HAVEDA2,
            hmux2::src::tty_keys::TTY_HAVEDA2
        ]
    );
    constant!(
        TTY_HAVESYNC,
        [
            hmux2::src::tty::TTY_HAVESYNC,
            hmux2::src::tty_keys::TTY_HAVESYNC
        ]
    );
    constant!(
        TTY_HAVEXDA,
        [
            hmux2::src::tty::TTY_HAVEXDA,
            hmux2::src::tty_keys::TTY_HAVEXDA
        ]
    );
    constant!(TTY_NOBLOCK, [hmux2::src::tty::TTY_NOBLOCK]);
    constant!(
        TTY_NOCURSOR,
        [
            hmux2::src::server_client::TTY_NOCURSOR,
            hmux2::src::status::TTY_NOCURSOR,
            hmux2::src::tty::TTY_NOCURSOR,
            hmux2::src::tty_draw::TTY_NOCURSOR
        ]
    );
    constant!(
        TTY_OPENED,
        [
            hmux2::src::colour::TTY_OPENED,
            hmux2::src::options::TTY_OPENED,
            hmux2::src::server_client::TTY_OPENED,
            hmux2::src::tty::TTY_OPENED
        ]
    );
    constant!(
        TTY_OSC52QUERY,
        [
            hmux2::src::tty::TTY_OSC52QUERY,
            hmux2::src::tty_keys::TTY_OSC52QUERY
        ]
    );
    constant!(TTY_QUERY_TIMEOUT, [hmux2::src::tty::TTY_QUERY_TIMEOUT]);
    constant!(TTY_REQUEST_LIMIT, [hmux2::src::tty::TTY_REQUEST_LIMIT]);
    constant!(
        TTY_STARTED,
        [
            hmux2::src::format::TTY_STARTED,
            hmux2::src::input::TTY_STARTED,
            hmux2::src::tty::TTY_STARTED
        ]
    );
    constant!(TTY_SYNCING, [hmux2::src::tty::TTY_SYNCING]);
    constant!(
        TTY_TIMER,
        [hmux2::src::tty::TTY_TIMER, hmux2::src::tty_keys::TTY_TIMER]
    );
    constant!(
        TTY_WAITBG,
        [
            hmux2::src::tty::TTY_WAITBG,
            hmux2::src::tty_keys::TTY_WAITBG
        ]
    );
    constant!(
        TTY_WAITFG,
        [
            hmux2::src::tty::TTY_WAITFG,
            hmux2::src::tty_keys::TTY_WAITFG
        ]
    );
    constant!(
        TTY_WINSIZEQUERY,
        [
            hmux2::src::tty::TTY_WINSIZEQUERY,
            hmux2::src::tty_keys::TTY_WINSIZEQUERY
        ]
    );
    constant!(
        WINDOW_ACTIVITY,
        [
            hmux2::src::alerts::WINDOW_ACTIVITY,
            hmux2::src::cmd_kill_session::WINDOW_ACTIVITY,
            hmux2::src::window::WINDOW_ACTIVITY
        ]
    );
    constant!(
        WINDOW_ALERTFLAGS,
        [
            hmux2::src::alerts::WINDOW_ALERTFLAGS,
            hmux2::src::cmd_kill_session::WINDOW_ALERTFLAGS,
            hmux2::src::window::WINDOW_ALERTFLAGS
        ]
    );
    constant!(
        WINDOW_BELL,
        [
            hmux2::src::alerts::WINDOW_BELL,
            hmux2::src::cmd_kill_session::WINDOW_BELL,
            hmux2::src::input::WINDOW_BELL,
            hmux2::src::window::WINDOW_BELL
        ]
    );
    constant!(
        WINDOW_MAXIMUM,
        [
            hmux2::src::cmd_refresh_client::WINDOW_MAXIMUM,
            hmux2::src::cmd_resize_window::WINDOW_MAXIMUM,
            hmux2::src::layout_custom::WINDOW_MAXIMUM,
            hmux2::src::resize::WINDOW_MAXIMUM
        ]
    );
    constant!(
        WINDOW_MINIMUM,
        [
            hmux2::src::cmd_refresh_client::WINDOW_MINIMUM,
            hmux2::src::cmd_resize_window::WINDOW_MINIMUM,
            hmux2::src::resize::WINDOW_MINIMUM
        ]
    );
    constant!(
        WINDOW_MODE_HIDE_PANE_STATUS,
        [
            hmux2::src::window::WINDOW_MODE_HIDE_PANE_STATUS,
            hmux2::src::window_panes::WINDOW_MODE_HIDE_PANE_STATUS
        ]
    );
    constant!(
        WINDOW_MODE_HIDE_SCROLLBARS,
        [
            hmux2::src::window::WINDOW_MODE_HIDE_SCROLLBARS,
            hmux2::src::window_panes::WINDOW_MODE_HIDE_SCROLLBARS
        ]
    );
    constant!(
        WINDOW_MODE_NO_STACK,
        [
            hmux2::src::window::WINDOW_MODE_NO_STACK,
            hmux2::src::window_panes::WINDOW_MODE_NO_STACK
        ]
    );
    constant!(
        WINDOW_PANE_NO_MODE,
        [
            hmux2::src::format::WINDOW_PANE_NO_MODE,
            hmux2::src::screen_redraw::WINDOW_PANE_NO_MODE,
            hmux2::src::window::WINDOW_PANE_NO_MODE
        ]
    );
    constant!(
        WINDOW_RESIZE,
        [
            hmux2::src::resize::WINDOW_RESIZE,
            hmux2::src::server_client::WINDOW_RESIZE
        ]
    );
    constant!(
        WINDOW_SILENCE,
        [
            hmux2::src::alerts::WINDOW_SILENCE,
            hmux2::src::cmd_kill_session::WINDOW_SILENCE,
            hmux2::src::window::WINDOW_SILENCE
        ]
    );
    constant!(
        WINDOW_SIZE_LARGEST,
        [
            hmux2::src::cmd_resize_window::WINDOW_SIZE_LARGEST,
            hmux2::src::resize::WINDOW_SIZE_LARGEST
        ]
    );
    constant!(
        WINDOW_SIZE_LATEST,
        [
            hmux2::src::options_table::WINDOW_SIZE_LATEST,
            hmux2::src::resize::WINDOW_SIZE_LATEST,
            hmux2::src::server_client::WINDOW_SIZE_LATEST
        ]
    );
    constant!(
        WINDOW_SIZE_MANUAL,
        [
            hmux2::src::cmd_resize_window::WINDOW_SIZE_MANUAL,
            hmux2::src::format::WINDOW_SIZE_MANUAL,
            hmux2::src::resize::WINDOW_SIZE_MANUAL
        ]
    );
    constant!(
        WINDOW_ZOOMED,
        [
            hmux2::src::cmd_break_pane::WINDOW_ZOOMED,
            hmux2::src::cmd_join_pane::WINDOW_ZOOMED,
            hmux2::src::cmd_resize_pane::WINDOW_ZOOMED,
            hmux2::src::cmd_split_window::WINDOW_ZOOMED,
            hmux2::src::format::WINDOW_ZOOMED,
            hmux2::src::mode_tree::WINDOW_ZOOMED,
            hmux2::src::spawn::WINDOW_ZOOMED,
            hmux2::src::window::WINDOW_ZOOMED,
            hmux2::src::window_panes::WINDOW_ZOOMED,
            hmux2::src::window_switch::WINDOW_ZOOMED
        ]
    );
    constant!(
        WINLINK_ACTIVITY,
        [
            hmux2::src::alerts::WINLINK_ACTIVITY,
            hmux2::src::cmd_kill_session::WINLINK_ACTIVITY,
            hmux2::src::format::WINLINK_ACTIVITY,
            hmux2::src::server_client::WINLINK_ACTIVITY,
            hmux2::src::server_fn::WINLINK_ACTIVITY,
            hmux2::src::session::WINLINK_ACTIVITY,
            hmux2::src::spawn::WINLINK_ACTIVITY,
            hmux2::src::window::WINLINK_ACTIVITY
        ]
    );
    constant!(
        WINLINK_ALERTFLAGS,
        [
            hmux2::src::cmd_kill_session::WINLINK_ALERTFLAGS,
            hmux2::src::format::WINLINK_ALERTFLAGS,
            hmux2::src::server_client::WINLINK_ALERTFLAGS,
            hmux2::src::server_fn::WINLINK_ALERTFLAGS,
            hmux2::src::session::WINLINK_ALERTFLAGS,
            hmux2::src::spawn::WINLINK_ALERTFLAGS,
            hmux2::src::window::WINLINK_ALERTFLAGS
        ]
    );
    constant!(
        WINLINK_BELL,
        [
            hmux2::src::alerts::WINLINK_BELL,
            hmux2::src::cmd_kill_session::WINLINK_BELL,
            hmux2::src::format::WINLINK_BELL,
            hmux2::src::server_client::WINLINK_BELL,
            hmux2::src::server_fn::WINLINK_BELL,
            hmux2::src::session::WINLINK_BELL,
            hmux2::src::spawn::WINLINK_BELL,
            hmux2::src::window::WINLINK_BELL
        ]
    );
    constant!(
        WINLINK_SILENCE,
        [
            hmux2::src::alerts::WINLINK_SILENCE,
            hmux2::src::cmd_kill_session::WINLINK_SILENCE,
            hmux2::src::format::WINLINK_SILENCE,
            hmux2::src::server_client::WINLINK_SILENCE,
            hmux2::src::server_fn::WINLINK_SILENCE,
            hmux2::src::session::WINLINK_SILENCE,
            hmux2::src::spawn::WINLINK_SILENCE,
            hmux2::src::window::WINLINK_SILENCE
        ]
    );
    constant!(
        WINLINK_VISITED,
        [
            hmux2::src::session::WINLINK_VISITED,
            hmux2::src::window::WINLINK_VISITED
        ]
    );
    let actual: String = constants
        .iter()
        .map(|(name, value)| format!("{name} {value}\n"))
        .collect();
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    assert_eq!(
        actual,
        std::fs::read_to_string(root.join("tests/fixtures/consolidation-constants.txt")).unwrap()
    );
}
