//! Frozen layout snapshots, with layout-cell types recorded in their migrated form.
use std::mem::{align_of, offset_of, size_of};
#[test]
fn layout_types_match_snapshot() {
    let mut records = Vec::new();
    macro_rules! record {
        ($label:literal, $ty:ty, [$($field:ident),*]) => {
            records.push(format!("{} {} {} {:?}", $label, size_of::<$ty>(), align_of::<$ty>(),
                &[$(offset_of!($ty, $field)),*] as &[usize]));
        };
    }
    record!(
        "src/alerts.rs::layout_cell",
        hmux2::src::alerts::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/arguments.rs::layout_cell",
        hmux2::src::arguments::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cfg.rs::layout_cell",
        hmux2::src::cfg::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/client.rs::layout_cell",
        hmux2::src::client::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd.rs::layout_cell",
        hmux2::src::cmd::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_attach_session.rs::layout_cell",
        hmux2::src::cmd_attach_session::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_bind_key.rs::layout_cell",
        hmux2::src::cmd_bind_key::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_break_pane.rs::layout_cell",
        hmux2::src::cmd_break_pane::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_capture_pane.rs::layout_cell",
        hmux2::src::cmd_capture_pane::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_choose_tree.rs::layout_cell",
        hmux2::src::cmd_choose_tree::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_command_prompt.rs::layout_cell",
        hmux2::src::cmd_command_prompt::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_confirm_before.rs::layout_cell",
        hmux2::src::cmd_confirm_before::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_copy_mode.rs::layout_cell",
        hmux2::src::cmd_copy_mode::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_detach_client.rs::layout_cell",
        hmux2::src::cmd_detach_client::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_display_menu.rs::layout_cell",
        hmux2::src::cmd_display_menu::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_display_message.rs::layout_cell",
        hmux2::src::cmd_display_message::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_find.rs::layout_cell",
        hmux2::src::cmd_find::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_find_window.rs::layout_cell",
        hmux2::src::cmd_find_window::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_if_shell.rs::layout_cell",
        hmux2::src::cmd_if_shell::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_join_pane.rs::layout_cell",
        hmux2::src::cmd_join_pane::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_kill_pane.rs::layout_cell",
        hmux2::src::cmd_kill_pane::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_kill_session.rs::layout_cell",
        hmux2::src::cmd_kill_session::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_kill_window.rs::layout_cell",
        hmux2::src::cmd_kill_window::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_list_buffers.rs::layout_cell",
        hmux2::src::cmd_list_buffers::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_list_clients.rs::layout_cell",
        hmux2::src::cmd_list_clients::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_list_commands.rs::layout_cell",
        hmux2::src::cmd_list_commands::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_list_keys.rs::layout_cell",
        hmux2::src::cmd_list_keys::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_list_panes.rs::layout_cell",
        hmux2::src::cmd_list_panes::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_list_sessions.rs::layout_cell",
        hmux2::src::cmd_list_sessions::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_list_windows.rs::layout_cell",
        hmux2::src::cmd_list_windows::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_load_buffer.rs::layout_cell",
        hmux2::src::cmd_load_buffer::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_lock_server.rs::layout_cell",
        hmux2::src::cmd_lock_server::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_move_window.rs::layout_cell",
        hmux2::src::cmd_move_window::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_new_session.rs::layout_cell",
        hmux2::src::cmd_new_session::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_new_window.rs::layout_cell",
        hmux2::src::cmd_new_window::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_parse.rs::layout_cell",
        hmux2::src::cmd_parse::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_paste_buffer.rs::layout_cell",
        hmux2::src::cmd_paste_buffer::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_pipe_pane.rs::layout_cell",
        hmux2::src::cmd_pipe_pane::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_queue.rs::layout_cell",
        hmux2::src::cmd_queue::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_refresh_client.rs::layout_cell",
        hmux2::src::cmd_refresh_client::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_rename_session.rs::layout_cell",
        hmux2::src::cmd_rename_session::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_rename_window.rs::layout_cell",
        hmux2::src::cmd_rename_window::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_resize_pane.rs::layout_cell",
        hmux2::src::cmd_resize_pane::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_resize_window.rs::layout_cell",
        hmux2::src::cmd_resize_window::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_respawn_pane.rs::layout_cell",
        hmux2::src::cmd_respawn_pane::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_respawn_window.rs::layout_cell",
        hmux2::src::cmd_respawn_window::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_rotate_window.rs::layout_cell",
        hmux2::src::cmd_rotate_window::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_run_shell.rs::layout_cell",
        hmux2::src::cmd_run_shell::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_save_buffer.rs::layout_cell",
        hmux2::src::cmd_save_buffer::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_select_layout.rs::layout_cell",
        hmux2::src::cmd_select_layout::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_select_pane.rs::layout_cell",
        hmux2::src::cmd_select_pane::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_select_window.rs::layout_cell",
        hmux2::src::cmd_select_window::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_send_keys.rs::layout_cell",
        hmux2::src::cmd_send_keys::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_server_access.rs::layout_cell",
        hmux2::src::cmd_server_access::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_set_buffer.rs::layout_cell",
        hmux2::src::cmd_set_buffer::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_set_environment.rs::layout_cell",
        hmux2::src::cmd_set_environment::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_set_option.rs::layout_cell",
        hmux2::src::cmd_set_option::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_show_environment.rs::layout_cell",
        hmux2::src::cmd_show_environment::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_show_messages.rs::layout_cell",
        hmux2::src::cmd_show_messages::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_show_options.rs::layout_cell",
        hmux2::src::cmd_show_options::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_source_file.rs::layout_cell",
        hmux2::src::cmd_source_file::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_split_window.rs::layout_cell",
        hmux2::src::cmd_split_window::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_swap_pane.rs::layout_cell",
        hmux2::src::cmd_swap_pane::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_swap_window.rs::layout_cell",
        hmux2::src::cmd_swap_window::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_switch_client.rs::layout_cell",
        hmux2::src::cmd_switch_client::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/cmd_wait_for.rs::layout_cell",
        hmux2::src::cmd_wait_for::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/colour.rs::layout_cell",
        hmux2::src::colour::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/control.rs::layout_cell",
        hmux2::src::control::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/control_notify.rs::layout_cell",
        hmux2::src::control_notify::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/environ.rs::layout_cell",
        hmux2::src::environ::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/events.rs::layout_cell",
        hmux2::src::events::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/events_payload.rs::layout_cell",
        hmux2::src::events_payload::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/file.rs::layout_cell",
        hmux2::src::file::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/format.rs::layout_cell",
        hmux2::src::format::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/format_draw.rs::layout_cell",
        hmux2::src::format_draw::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/hooks.rs::layout_cell",
        hmux2::src::hooks::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/input.rs::layout_cell",
        hmux2::src::input::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/input_keys.rs::layout_cell",
        hmux2::src::input_keys::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/job.rs::layout_cell",
        hmux2::src::job::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/key_bindings.rs::layout_cell",
        hmux2::src::key_bindings::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/layout.rs::layout_cell",
        hmux2::src::layout::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/layout_custom.rs::layout_cell",
        hmux2::src::layout_custom::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/layout_set.rs::layout_cell",
        hmux2::src::layout_set::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/menu.rs::layout_cell",
        hmux2::src::menu::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/mode_tree.rs::layout_cell",
        hmux2::src::mode_tree::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/monitor.rs::layout_cell",
        hmux2::src::monitor::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/names.rs::layout_cell",
        hmux2::src::names::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/options.rs::layout_cell",
        hmux2::src::options::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/popup.rs::layout_cell",
        hmux2::src::popup::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/prompt.rs::layout_cell",
        hmux2::src::prompt::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/resize.rs::layout_cell",
        hmux2::src::resize::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/screen.rs::layout_cell",
        hmux2::src::screen::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/screen_redraw.rs::layout_cell",
        hmux2::src::screen_redraw::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/screen_write.rs::layout_cell",
        hmux2::src::screen_write::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/server.rs::layout_cell",
        hmux2::src::server::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/server_acl.rs::layout_cell",
        hmux2::src::server_acl::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/server_client.rs::layout_cell",
        hmux2::src::server_client::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/server_fn.rs::layout_cell",
        hmux2::src::server_fn::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/session.rs::layout_cell",
        hmux2::src::session::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/sort.rs::layout_cell",
        hmux2::src::sort::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/spawn.rs::layout_cell",
        hmux2::src::spawn::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/status.rs::layout_cell",
        hmux2::src::status::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/style.rs::layout_cell",
        hmux2::src::style::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/tty.rs::layout_cell",
        hmux2::src::tty::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/tty_acs.rs::layout_cell",
        hmux2::src::tty_acs::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/tty_draw.rs::layout_cell",
        hmux2::src::tty_draw::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/tty_features.rs::layout_cell",
        hmux2::src::tty_features::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/tty_keys.rs::layout_cell",
        hmux2::src::tty_keys::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/tty_term.rs::layout_cell",
        hmux2::src::tty_term::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/window.rs::layout_cell",
        hmux2::src::window::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/window_border.rs::layout_cell",
        hmux2::src::window_border::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/window_buffer.rs::layout_cell",
        hmux2::src::window_buffer::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/window_client.rs::layout_cell",
        hmux2::src::window_client::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/window_clock.rs::layout_cell",
        hmux2::src::window_clock::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/window_copy.rs::layout_cell",
        hmux2::src::window_copy::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/window_customize.rs::layout_cell",
        hmux2::src::window_customize::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/window_panes.rs::layout_cell",
        hmux2::src::window_panes::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/window_switch.rs::layout_cell",
        hmux2::src::window_switch::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/window_tree.rs::layout_cell",
        hmux2::src::window_tree::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/window_visible.rs::layout_cell",
        hmux2::src::window_visible::layout_cell,
        [type_0, flags, parent, sibling_index, g, fg, wp, cells]
    );
    record!(
        "src/alerts.rs::layout_cell_entry",
        hmux2::src::alerts::layout_cell_entry,
        []
    );
    record!(
        "src/arguments.rs::layout_cell_entry",
        hmux2::src::arguments::layout_cell_entry,
        []
    );
    record!(
        "src/cfg.rs::layout_cell_entry",
        hmux2::src::cfg::layout_cell_entry,
        []
    );
    record!(
        "src/client.rs::layout_cell_entry",
        hmux2::src::client::layout_cell_entry,
        []
    );
    record!(
        "src/cmd.rs::layout_cell_entry",
        hmux2::src::cmd::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_attach_session.rs::layout_cell_entry",
        hmux2::src::cmd_attach_session::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_bind_key.rs::layout_cell_entry",
        hmux2::src::cmd_bind_key::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_break_pane.rs::layout_cell_entry",
        hmux2::src::cmd_break_pane::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_capture_pane.rs::layout_cell_entry",
        hmux2::src::cmd_capture_pane::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_choose_tree.rs::layout_cell_entry",
        hmux2::src::cmd_choose_tree::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_command_prompt.rs::layout_cell_entry",
        hmux2::src::cmd_command_prompt::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_confirm_before.rs::layout_cell_entry",
        hmux2::src::cmd_confirm_before::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_copy_mode.rs::layout_cell_entry",
        hmux2::src::cmd_copy_mode::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_detach_client.rs::layout_cell_entry",
        hmux2::src::cmd_detach_client::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_display_menu.rs::layout_cell_entry",
        hmux2::src::cmd_display_menu::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_display_message.rs::layout_cell_entry",
        hmux2::src::cmd_display_message::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_find.rs::layout_cell_entry",
        hmux2::src::cmd_find::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_find_window.rs::layout_cell_entry",
        hmux2::src::cmd_find_window::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_if_shell.rs::layout_cell_entry",
        hmux2::src::cmd_if_shell::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_join_pane.rs::layout_cell_entry",
        hmux2::src::cmd_join_pane::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_kill_pane.rs::layout_cell_entry",
        hmux2::src::cmd_kill_pane::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_kill_session.rs::layout_cell_entry",
        hmux2::src::cmd_kill_session::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_kill_window.rs::layout_cell_entry",
        hmux2::src::cmd_kill_window::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_list_buffers.rs::layout_cell_entry",
        hmux2::src::cmd_list_buffers::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_list_clients.rs::layout_cell_entry",
        hmux2::src::cmd_list_clients::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_list_commands.rs::layout_cell_entry",
        hmux2::src::cmd_list_commands::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_list_keys.rs::layout_cell_entry",
        hmux2::src::cmd_list_keys::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_list_panes.rs::layout_cell_entry",
        hmux2::src::cmd_list_panes::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_list_sessions.rs::layout_cell_entry",
        hmux2::src::cmd_list_sessions::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_list_windows.rs::layout_cell_entry",
        hmux2::src::cmd_list_windows::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_load_buffer.rs::layout_cell_entry",
        hmux2::src::cmd_load_buffer::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_lock_server.rs::layout_cell_entry",
        hmux2::src::cmd_lock_server::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_move_window.rs::layout_cell_entry",
        hmux2::src::cmd_move_window::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_new_session.rs::layout_cell_entry",
        hmux2::src::cmd_new_session::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_new_window.rs::layout_cell_entry",
        hmux2::src::cmd_new_window::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_parse.rs::layout_cell_entry",
        hmux2::src::cmd_parse::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_paste_buffer.rs::layout_cell_entry",
        hmux2::src::cmd_paste_buffer::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_pipe_pane.rs::layout_cell_entry",
        hmux2::src::cmd_pipe_pane::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_queue.rs::layout_cell_entry",
        hmux2::src::cmd_queue::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_refresh_client.rs::layout_cell_entry",
        hmux2::src::cmd_refresh_client::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_rename_session.rs::layout_cell_entry",
        hmux2::src::cmd_rename_session::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_rename_window.rs::layout_cell_entry",
        hmux2::src::cmd_rename_window::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_resize_pane.rs::layout_cell_entry",
        hmux2::src::cmd_resize_pane::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_resize_window.rs::layout_cell_entry",
        hmux2::src::cmd_resize_window::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_respawn_pane.rs::layout_cell_entry",
        hmux2::src::cmd_respawn_pane::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_respawn_window.rs::layout_cell_entry",
        hmux2::src::cmd_respawn_window::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_rotate_window.rs::layout_cell_entry",
        hmux2::src::cmd_rotate_window::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_run_shell.rs::layout_cell_entry",
        hmux2::src::cmd_run_shell::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_save_buffer.rs::layout_cell_entry",
        hmux2::src::cmd_save_buffer::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_select_layout.rs::layout_cell_entry",
        hmux2::src::cmd_select_layout::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_select_pane.rs::layout_cell_entry",
        hmux2::src::cmd_select_pane::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_select_window.rs::layout_cell_entry",
        hmux2::src::cmd_select_window::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_send_keys.rs::layout_cell_entry",
        hmux2::src::cmd_send_keys::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_server_access.rs::layout_cell_entry",
        hmux2::src::cmd_server_access::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_set_buffer.rs::layout_cell_entry",
        hmux2::src::cmd_set_buffer::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_set_environment.rs::layout_cell_entry",
        hmux2::src::cmd_set_environment::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_set_option.rs::layout_cell_entry",
        hmux2::src::cmd_set_option::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_show_environment.rs::layout_cell_entry",
        hmux2::src::cmd_show_environment::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_show_messages.rs::layout_cell_entry",
        hmux2::src::cmd_show_messages::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_show_options.rs::layout_cell_entry",
        hmux2::src::cmd_show_options::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_source_file.rs::layout_cell_entry",
        hmux2::src::cmd_source_file::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_split_window.rs::layout_cell_entry",
        hmux2::src::cmd_split_window::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_swap_pane.rs::layout_cell_entry",
        hmux2::src::cmd_swap_pane::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_swap_window.rs::layout_cell_entry",
        hmux2::src::cmd_swap_window::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_switch_client.rs::layout_cell_entry",
        hmux2::src::cmd_switch_client::layout_cell_entry,
        []
    );
    record!(
        "src/cmd_wait_for.rs::layout_cell_entry",
        hmux2::src::cmd_wait_for::layout_cell_entry,
        []
    );
    record!(
        "src/colour.rs::layout_cell_entry",
        hmux2::src::colour::layout_cell_entry,
        []
    );
    record!(
        "src/control.rs::layout_cell_entry",
        hmux2::src::control::layout_cell_entry,
        []
    );
    record!(
        "src/control_notify.rs::layout_cell_entry",
        hmux2::src::control_notify::layout_cell_entry,
        []
    );
    record!(
        "src/environ.rs::layout_cell_entry",
        hmux2::src::environ::layout_cell_entry,
        []
    );
    record!(
        "src/events.rs::layout_cell_entry",
        hmux2::src::events::layout_cell_entry,
        []
    );
    record!(
        "src/events_payload.rs::layout_cell_entry",
        hmux2::src::events_payload::layout_cell_entry,
        []
    );
    record!(
        "src/file.rs::layout_cell_entry",
        hmux2::src::file::layout_cell_entry,
        []
    );
    record!(
        "src/format.rs::layout_cell_entry",
        hmux2::src::format::layout_cell_entry,
        []
    );
    record!(
        "src/format_draw.rs::layout_cell_entry",
        hmux2::src::format_draw::layout_cell_entry,
        []
    );
    record!(
        "src/hooks.rs::layout_cell_entry",
        hmux2::src::hooks::layout_cell_entry,
        []
    );
    record!(
        "src/input.rs::layout_cell_entry",
        hmux2::src::input::layout_cell_entry,
        []
    );
    record!(
        "src/input_keys.rs::layout_cell_entry",
        hmux2::src::input_keys::layout_cell_entry,
        []
    );
    record!(
        "src/job.rs::layout_cell_entry",
        hmux2::src::job::layout_cell_entry,
        []
    );
    record!(
        "src/key_bindings.rs::layout_cell_entry",
        hmux2::src::key_bindings::layout_cell_entry,
        []
    );
    record!(
        "src/layout.rs::layout_cell_entry",
        hmux2::src::layout::layout_cell_entry,
        []
    );
    record!(
        "src/layout_custom.rs::layout_cell_entry",
        hmux2::src::layout_custom::layout_cell_entry,
        []
    );
    record!(
        "src/layout_set.rs::layout_cell_entry",
        hmux2::src::layout_set::layout_cell_entry,
        []
    );
    record!(
        "src/menu.rs::layout_cell_entry",
        hmux2::src::menu::layout_cell_entry,
        []
    );
    record!(
        "src/mode_tree.rs::layout_cell_entry",
        hmux2::src::mode_tree::layout_cell_entry,
        []
    );
    record!(
        "src/monitor.rs::layout_cell_entry",
        hmux2::src::monitor::layout_cell_entry,
        []
    );
    record!(
        "src/names.rs::layout_cell_entry",
        hmux2::src::names::layout_cell_entry,
        []
    );
    record!(
        "src/options.rs::layout_cell_entry",
        hmux2::src::options::layout_cell_entry,
        []
    );
    record!(
        "src/popup.rs::layout_cell_entry",
        hmux2::src::popup::layout_cell_entry,
        []
    );
    record!(
        "src/prompt.rs::layout_cell_entry",
        hmux2::src::prompt::layout_cell_entry,
        []
    );
    record!(
        "src/resize.rs::layout_cell_entry",
        hmux2::src::resize::layout_cell_entry,
        []
    );
    record!(
        "src/screen.rs::layout_cell_entry",
        hmux2::src::screen::layout_cell_entry,
        []
    );
    record!(
        "src/screen_redraw.rs::layout_cell_entry",
        hmux2::src::screen_redraw::layout_cell_entry,
        []
    );
    record!(
        "src/screen_write.rs::layout_cell_entry",
        hmux2::src::screen_write::layout_cell_entry,
        []
    );
    record!(
        "src/server.rs::layout_cell_entry",
        hmux2::src::server::layout_cell_entry,
        []
    );
    record!(
        "src/server_acl.rs::layout_cell_entry",
        hmux2::src::server_acl::layout_cell_entry,
        []
    );
    record!(
        "src/server_client.rs::layout_cell_entry",
        hmux2::src::server_client::layout_cell_entry,
        []
    );
    record!(
        "src/server_fn.rs::layout_cell_entry",
        hmux2::src::server_fn::layout_cell_entry,
        []
    );
    record!(
        "src/session.rs::layout_cell_entry",
        hmux2::src::session::layout_cell_entry,
        []
    );
    record!(
        "src/sort.rs::layout_cell_entry",
        hmux2::src::sort::layout_cell_entry,
        []
    );
    record!(
        "src/spawn.rs::layout_cell_entry",
        hmux2::src::spawn::layout_cell_entry,
        []
    );
    record!(
        "src/status.rs::layout_cell_entry",
        hmux2::src::status::layout_cell_entry,
        []
    );
    record!(
        "src/style.rs::layout_cell_entry",
        hmux2::src::style::layout_cell_entry,
        []
    );
    record!(
        "src/tty.rs::layout_cell_entry",
        hmux2::src::tty::layout_cell_entry,
        []
    );
    record!(
        "src/tty_acs.rs::layout_cell_entry",
        hmux2::src::tty_acs::layout_cell_entry,
        []
    );
    record!(
        "src/tty_draw.rs::layout_cell_entry",
        hmux2::src::tty_draw::layout_cell_entry,
        []
    );
    record!(
        "src/tty_features.rs::layout_cell_entry",
        hmux2::src::tty_features::layout_cell_entry,
        []
    );
    record!(
        "src/tty_keys.rs::layout_cell_entry",
        hmux2::src::tty_keys::layout_cell_entry,
        []
    );
    record!(
        "src/tty_term.rs::layout_cell_entry",
        hmux2::src::tty_term::layout_cell_entry,
        []
    );
    record!(
        "src/window.rs::layout_cell_entry",
        hmux2::src::window::layout_cell_entry,
        []
    );
    record!(
        "src/window_border.rs::layout_cell_entry",
        hmux2::src::window_border::layout_cell_entry,
        []
    );
    record!(
        "src/window_buffer.rs::layout_cell_entry",
        hmux2::src::window_buffer::layout_cell_entry,
        []
    );
    record!(
        "src/window_client.rs::layout_cell_entry",
        hmux2::src::window_client::layout_cell_entry,
        []
    );
    record!(
        "src/window_clock.rs::layout_cell_entry",
        hmux2::src::window_clock::layout_cell_entry,
        []
    );
    record!(
        "src/window_copy.rs::layout_cell_entry",
        hmux2::src::window_copy::layout_cell_entry,
        []
    );
    record!(
        "src/window_customize.rs::layout_cell_entry",
        hmux2::src::window_customize::layout_cell_entry,
        []
    );
    record!(
        "src/window_panes.rs::layout_cell_entry",
        hmux2::src::window_panes::layout_cell_entry,
        []
    );
    record!(
        "src/window_switch.rs::layout_cell_entry",
        hmux2::src::window_switch::layout_cell_entry,
        []
    );
    record!(
        "src/window_tree.rs::layout_cell_entry",
        hmux2::src::window_tree::layout_cell_entry,
        []
    );
    record!(
        "src/window_visible.rs::layout_cell_entry",
        hmux2::src::window_visible::layout_cell_entry,
        []
    );
    record!(
        "src/alerts.rs::layout_cells",
        hmux2::src::alerts::layout_cells,
        [children]
    );
    record!(
        "src/arguments.rs::layout_cells",
        hmux2::src::arguments::layout_cells,
        [children]
    );
    record!(
        "src/cfg.rs::layout_cells",
        hmux2::src::cfg::layout_cells,
        [children]
    );
    record!(
        "src/client.rs::layout_cells",
        hmux2::src::client::layout_cells,
        [children]
    );
    record!(
        "src/cmd.rs::layout_cells",
        hmux2::src::cmd::layout_cells,
        [children]
    );
    record!(
        "src/cmd_attach_session.rs::layout_cells",
        hmux2::src::cmd_attach_session::layout_cells,
        [children]
    );
    record!(
        "src/cmd_bind_key.rs::layout_cells",
        hmux2::src::cmd_bind_key::layout_cells,
        [children]
    );
    record!(
        "src/cmd_break_pane.rs::layout_cells",
        hmux2::src::cmd_break_pane::layout_cells,
        [children]
    );
    record!(
        "src/cmd_capture_pane.rs::layout_cells",
        hmux2::src::cmd_capture_pane::layout_cells,
        [children]
    );
    record!(
        "src/cmd_choose_tree.rs::layout_cells",
        hmux2::src::cmd_choose_tree::layout_cells,
        [children]
    );
    record!(
        "src/cmd_command_prompt.rs::layout_cells",
        hmux2::src::cmd_command_prompt::layout_cells,
        [children]
    );
    record!(
        "src/cmd_confirm_before.rs::layout_cells",
        hmux2::src::cmd_confirm_before::layout_cells,
        [children]
    );
    record!(
        "src/cmd_copy_mode.rs::layout_cells",
        hmux2::src::cmd_copy_mode::layout_cells,
        [children]
    );
    record!(
        "src/cmd_detach_client.rs::layout_cells",
        hmux2::src::cmd_detach_client::layout_cells,
        [children]
    );
    record!(
        "src/cmd_display_menu.rs::layout_cells",
        hmux2::src::cmd_display_menu::layout_cells,
        [children]
    );
    record!(
        "src/cmd_display_message.rs::layout_cells",
        hmux2::src::cmd_display_message::layout_cells,
        [children]
    );
    record!(
        "src/cmd_find.rs::layout_cells",
        hmux2::src::cmd_find::layout_cells,
        [children]
    );
    record!(
        "src/cmd_find_window.rs::layout_cells",
        hmux2::src::cmd_find_window::layout_cells,
        [children]
    );
    record!(
        "src/cmd_if_shell.rs::layout_cells",
        hmux2::src::cmd_if_shell::layout_cells,
        [children]
    );
    record!(
        "src/cmd_join_pane.rs::layout_cells",
        hmux2::src::cmd_join_pane::layout_cells,
        [children]
    );
    record!(
        "src/cmd_kill_pane.rs::layout_cells",
        hmux2::src::cmd_kill_pane::layout_cells,
        [children]
    );
    record!(
        "src/cmd_kill_session.rs::layout_cells",
        hmux2::src::cmd_kill_session::layout_cells,
        [children]
    );
    record!(
        "src/cmd_kill_window.rs::layout_cells",
        hmux2::src::cmd_kill_window::layout_cells,
        [children]
    );
    record!(
        "src/cmd_list_buffers.rs::layout_cells",
        hmux2::src::cmd_list_buffers::layout_cells,
        [children]
    );
    record!(
        "src/cmd_list_clients.rs::layout_cells",
        hmux2::src::cmd_list_clients::layout_cells,
        [children]
    );
    record!(
        "src/cmd_list_commands.rs::layout_cells",
        hmux2::src::cmd_list_commands::layout_cells,
        [children]
    );
    record!(
        "src/cmd_list_keys.rs::layout_cells",
        hmux2::src::cmd_list_keys::layout_cells,
        [children]
    );
    record!(
        "src/cmd_list_panes.rs::layout_cells",
        hmux2::src::cmd_list_panes::layout_cells,
        [children]
    );
    record!(
        "src/cmd_list_sessions.rs::layout_cells",
        hmux2::src::cmd_list_sessions::layout_cells,
        [children]
    );
    record!(
        "src/cmd_list_windows.rs::layout_cells",
        hmux2::src::cmd_list_windows::layout_cells,
        [children]
    );
    record!(
        "src/cmd_load_buffer.rs::layout_cells",
        hmux2::src::cmd_load_buffer::layout_cells,
        [children]
    );
    record!(
        "src/cmd_lock_server.rs::layout_cells",
        hmux2::src::cmd_lock_server::layout_cells,
        [children]
    );
    record!(
        "src/cmd_move_window.rs::layout_cells",
        hmux2::src::cmd_move_window::layout_cells,
        [children]
    );
    record!(
        "src/cmd_new_session.rs::layout_cells",
        hmux2::src::cmd_new_session::layout_cells,
        [children]
    );
    record!(
        "src/cmd_new_window.rs::layout_cells",
        hmux2::src::cmd_new_window::layout_cells,
        [children]
    );
    record!(
        "src/cmd_parse.rs::layout_cells",
        hmux2::src::cmd_parse::layout_cells,
        [children]
    );
    record!(
        "src/cmd_paste_buffer.rs::layout_cells",
        hmux2::src::cmd_paste_buffer::layout_cells,
        [children]
    );
    record!(
        "src/cmd_pipe_pane.rs::layout_cells",
        hmux2::src::cmd_pipe_pane::layout_cells,
        [children]
    );
    record!(
        "src/cmd_queue.rs::layout_cells",
        hmux2::src::cmd_queue::layout_cells,
        [children]
    );
    record!(
        "src/cmd_refresh_client.rs::layout_cells",
        hmux2::src::cmd_refresh_client::layout_cells,
        [children]
    );
    record!(
        "src/cmd_rename_session.rs::layout_cells",
        hmux2::src::cmd_rename_session::layout_cells,
        [children]
    );
    record!(
        "src/cmd_rename_window.rs::layout_cells",
        hmux2::src::cmd_rename_window::layout_cells,
        [children]
    );
    record!(
        "src/cmd_resize_pane.rs::layout_cells",
        hmux2::src::cmd_resize_pane::layout_cells,
        [children]
    );
    record!(
        "src/cmd_resize_window.rs::layout_cells",
        hmux2::src::cmd_resize_window::layout_cells,
        [children]
    );
    record!(
        "src/cmd_respawn_pane.rs::layout_cells",
        hmux2::src::cmd_respawn_pane::layout_cells,
        [children]
    );
    record!(
        "src/cmd_respawn_window.rs::layout_cells",
        hmux2::src::cmd_respawn_window::layout_cells,
        [children]
    );
    record!(
        "src/cmd_rotate_window.rs::layout_cells",
        hmux2::src::cmd_rotate_window::layout_cells,
        [children]
    );
    record!(
        "src/cmd_run_shell.rs::layout_cells",
        hmux2::src::cmd_run_shell::layout_cells,
        [children]
    );
    record!(
        "src/cmd_save_buffer.rs::layout_cells",
        hmux2::src::cmd_save_buffer::layout_cells,
        [children]
    );
    record!(
        "src/cmd_select_layout.rs::layout_cells",
        hmux2::src::cmd_select_layout::layout_cells,
        [children]
    );
    record!(
        "src/cmd_select_pane.rs::layout_cells",
        hmux2::src::cmd_select_pane::layout_cells,
        [children]
    );
    record!(
        "src/cmd_select_window.rs::layout_cells",
        hmux2::src::cmd_select_window::layout_cells,
        [children]
    );
    record!(
        "src/cmd_send_keys.rs::layout_cells",
        hmux2::src::cmd_send_keys::layout_cells,
        [children]
    );
    record!(
        "src/cmd_server_access.rs::layout_cells",
        hmux2::src::cmd_server_access::layout_cells,
        [children]
    );
    record!(
        "src/cmd_set_buffer.rs::layout_cells",
        hmux2::src::cmd_set_buffer::layout_cells,
        [children]
    );
    record!(
        "src/cmd_set_environment.rs::layout_cells",
        hmux2::src::cmd_set_environment::layout_cells,
        [children]
    );
    record!(
        "src/cmd_set_option.rs::layout_cells",
        hmux2::src::cmd_set_option::layout_cells,
        [children]
    );
    record!(
        "src/cmd_show_environment.rs::layout_cells",
        hmux2::src::cmd_show_environment::layout_cells,
        [children]
    );
    record!(
        "src/cmd_show_messages.rs::layout_cells",
        hmux2::src::cmd_show_messages::layout_cells,
        [children]
    );
    record!(
        "src/cmd_show_options.rs::layout_cells",
        hmux2::src::cmd_show_options::layout_cells,
        [children]
    );
    record!(
        "src/cmd_source_file.rs::layout_cells",
        hmux2::src::cmd_source_file::layout_cells,
        [children]
    );
    record!(
        "src/cmd_split_window.rs::layout_cells",
        hmux2::src::cmd_split_window::layout_cells,
        [children]
    );
    record!(
        "src/cmd_swap_pane.rs::layout_cells",
        hmux2::src::cmd_swap_pane::layout_cells,
        [children]
    );
    record!(
        "src/cmd_swap_window.rs::layout_cells",
        hmux2::src::cmd_swap_window::layout_cells,
        [children]
    );
    record!(
        "src/cmd_switch_client.rs::layout_cells",
        hmux2::src::cmd_switch_client::layout_cells,
        [children]
    );
    record!(
        "src/cmd_wait_for.rs::layout_cells",
        hmux2::src::cmd_wait_for::layout_cells,
        [children]
    );
    record!(
        "src/colour.rs::layout_cells",
        hmux2::src::colour::layout_cells,
        [children]
    );
    record!(
        "src/control.rs::layout_cells",
        hmux2::src::control::layout_cells,
        [children]
    );
    record!(
        "src/control_notify.rs::layout_cells",
        hmux2::src::control_notify::layout_cells,
        [children]
    );
    record!(
        "src/environ.rs::layout_cells",
        hmux2::src::environ::layout_cells,
        [children]
    );
    record!(
        "src/events.rs::layout_cells",
        hmux2::src::events::layout_cells,
        [children]
    );
    record!(
        "src/events_payload.rs::layout_cells",
        hmux2::src::events_payload::layout_cells,
        [children]
    );
    record!(
        "src/file.rs::layout_cells",
        hmux2::src::file::layout_cells,
        [children]
    );
    record!(
        "src/format.rs::layout_cells",
        hmux2::src::format::layout_cells,
        [children]
    );
    record!(
        "src/format_draw.rs::layout_cells",
        hmux2::src::format_draw::layout_cells,
        [children]
    );
    record!(
        "src/hooks.rs::layout_cells",
        hmux2::src::hooks::layout_cells,
        [children]
    );
    record!(
        "src/input.rs::layout_cells",
        hmux2::src::input::layout_cells,
        [children]
    );
    record!(
        "src/input_keys.rs::layout_cells",
        hmux2::src::input_keys::layout_cells,
        [children]
    );
    record!(
        "src/job.rs::layout_cells",
        hmux2::src::job::layout_cells,
        [children]
    );
    record!(
        "src/key_bindings.rs::layout_cells",
        hmux2::src::key_bindings::layout_cells,
        [children]
    );
    record!(
        "src/layout.rs::layout_cells",
        hmux2::src::layout::layout_cells,
        [children]
    );
    record!(
        "src/layout_custom.rs::layout_cells",
        hmux2::src::layout_custom::layout_cells,
        [children]
    );
    record!(
        "src/layout_set.rs::layout_cells",
        hmux2::src::layout_set::layout_cells,
        [children]
    );
    record!(
        "src/menu.rs::layout_cells",
        hmux2::src::menu::layout_cells,
        [children]
    );
    record!(
        "src/mode_tree.rs::layout_cells",
        hmux2::src::mode_tree::layout_cells,
        [children]
    );
    record!(
        "src/monitor.rs::layout_cells",
        hmux2::src::monitor::layout_cells,
        [children]
    );
    record!(
        "src/names.rs::layout_cells",
        hmux2::src::names::layout_cells,
        [children]
    );
    record!(
        "src/options.rs::layout_cells",
        hmux2::src::options::layout_cells,
        [children]
    );
    record!(
        "src/popup.rs::layout_cells",
        hmux2::src::popup::layout_cells,
        [children]
    );
    record!(
        "src/prompt.rs::layout_cells",
        hmux2::src::prompt::layout_cells,
        [children]
    );
    record!(
        "src/resize.rs::layout_cells",
        hmux2::src::resize::layout_cells,
        [children]
    );
    record!(
        "src/screen.rs::layout_cells",
        hmux2::src::screen::layout_cells,
        [children]
    );
    record!(
        "src/screen_redraw.rs::layout_cells",
        hmux2::src::screen_redraw::layout_cells,
        [children]
    );
    record!(
        "src/screen_write.rs::layout_cells",
        hmux2::src::screen_write::layout_cells,
        [children]
    );
    record!(
        "src/server.rs::layout_cells",
        hmux2::src::server::layout_cells,
        [children]
    );
    record!(
        "src/server_acl.rs::layout_cells",
        hmux2::src::server_acl::layout_cells,
        [children]
    );
    record!(
        "src/server_client.rs::layout_cells",
        hmux2::src::server_client::layout_cells,
        [children]
    );
    record!(
        "src/server_fn.rs::layout_cells",
        hmux2::src::server_fn::layout_cells,
        [children]
    );
    record!(
        "src/session.rs::layout_cells",
        hmux2::src::session::layout_cells,
        [children]
    );
    record!(
        "src/sort.rs::layout_cells",
        hmux2::src::sort::layout_cells,
        [children]
    );
    record!(
        "src/spawn.rs::layout_cells",
        hmux2::src::spawn::layout_cells,
        [children]
    );
    record!(
        "src/status.rs::layout_cells",
        hmux2::src::status::layout_cells,
        [children]
    );
    record!(
        "src/style.rs::layout_cells",
        hmux2::src::style::layout_cells,
        [children]
    );
    record!(
        "src/tty.rs::layout_cells",
        hmux2::src::tty::layout_cells,
        [children]
    );
    record!(
        "src/tty_acs.rs::layout_cells",
        hmux2::src::tty_acs::layout_cells,
        [children]
    );
    record!(
        "src/tty_draw.rs::layout_cells",
        hmux2::src::tty_draw::layout_cells,
        [children]
    );
    record!(
        "src/tty_features.rs::layout_cells",
        hmux2::src::tty_features::layout_cells,
        [children]
    );
    record!(
        "src/tty_keys.rs::layout_cells",
        hmux2::src::tty_keys::layout_cells,
        [children]
    );
    record!(
        "src/tty_term.rs::layout_cells",
        hmux2::src::tty_term::layout_cells,
        [children]
    );
    record!(
        "src/window.rs::layout_cells",
        hmux2::src::window::layout_cells,
        [children]
    );
    record!(
        "src/window_border.rs::layout_cells",
        hmux2::src::window_border::layout_cells,
        [children]
    );
    record!(
        "src/window_buffer.rs::layout_cells",
        hmux2::src::window_buffer::layout_cells,
        [children]
    );
    record!(
        "src/window_client.rs::layout_cells",
        hmux2::src::window_client::layout_cells,
        [children]
    );
    record!(
        "src/window_clock.rs::layout_cells",
        hmux2::src::window_clock::layout_cells,
        [children]
    );
    record!(
        "src/window_copy.rs::layout_cells",
        hmux2::src::window_copy::layout_cells,
        [children]
    );
    record!(
        "src/window_customize.rs::layout_cells",
        hmux2::src::window_customize::layout_cells,
        [children]
    );
    record!(
        "src/window_panes.rs::layout_cells",
        hmux2::src::window_panes::layout_cells,
        [children]
    );
    record!(
        "src/window_switch.rs::layout_cells",
        hmux2::src::window_switch::layout_cells,
        [children]
    );
    record!(
        "src/window_tree.rs::layout_cells",
        hmux2::src::window_tree::layout_cells,
        [children]
    );
    record!(
        "src/window_visible.rs::layout_cells",
        hmux2::src::window_visible::layout_cells,
        [children]
    );
    let actual = records.join("\n") + "\n";
    assert_eq!(actual, include_str!("fixtures/model-layout.txt"));
}
