//! Frozen measurements from every original translation-unit copy (Linux x86_64).
use std::mem::{align_of, size_of};
#[test]
fn platform_layouts() {
    let mut records = Vec::new();
    macro_rules! constant {
        ($label:literal, $ty:ty, $value:path) => {{
            let value: $ty = $value;
            records.push(format!(
                concat!($label, " {:?} {} {}"),
                value,
                size_of::<$ty>(),
                align_of::<$ty>()
            ));
        }};
    }

    constant!(
        "src/compat/systemd.rs::E2BIG",
        ::core::ffi::c_int,
        hmux2::src::compat::systemd::E2BIG
    );
    constant!(
        "src/file.rs::E2BIG",
        ::core::ffi::c_int,
        hmux2::src::file::E2BIG
    );
    constant!(
        "src/client.rs::EAGAIN",
        ::core::ffi::c_int,
        hmux2::src::client::EAGAIN
    );
    constant!(
        "src/compat/imsg_buffer.rs::EAGAIN",
        ::core::ffi::c_int,
        hmux2::src::compat::imsg_buffer::EAGAIN
    );
    constant!(
        "src/control.rs::EAGAIN",
        ::core::ffi::c_int,
        hmux2::src::control::EAGAIN
    );
    constant!(
        "src/server.rs::EAGAIN",
        ::core::ffi::c_int,
        hmux2::src::server::EAGAIN
    );
    constant!(
        "src/tty.rs::EAGAIN",
        ::core::ffi::c_int,
        hmux2::src::tty::EAGAIN
    );
    constant!(
        "src/compat/imsg.rs::EBADMSG",
        ::core::ffi::c_int,
        hmux2::src::compat::imsg::EBADMSG
    );
    constant!(
        "src/compat/imsg_buffer.rs::EBADMSG",
        ::core::ffi::c_int,
        hmux2::src::compat::imsg_buffer::EBADMSG
    );
    constant!(
        "src/client.rs::ECHILD",
        ::core::ffi::c_int,
        hmux2::src::client::ECHILD
    );
    constant!(
        "src/server.rs::ECHILD",
        ::core::ffi::c_int,
        hmux2::src::server::ECHILD
    );
    constant!(
        "src/client.rs::EINTR",
        ::core::ffi::c_int,
        hmux2::src::client::EINTR
    );
    constant!(
        "src/compat/imsg_buffer.rs::EINTR",
        ::core::ffi::c_int,
        hmux2::src::compat::imsg_buffer::EINTR
    );
    constant!(
        "src/control.rs::EINTR",
        ::core::ffi::c_int,
        hmux2::src::control::EINTR
    );
    constant!(
        "src/server.rs::EINTR",
        ::core::ffi::c_int,
        hmux2::src::server::EINTR
    );
    constant!(
        "src/server_client.rs::EINTR",
        ::core::ffi::c_int,
        hmux2::src::server_client::EINTR
    );
    constant!(
        "src/cmd_source_file.rs::EINVAL",
        ::core::ffi::c_int,
        hmux2::src::cmd_source_file::EINVAL
    );
    constant!(
        "src/compat/imsg.rs::EINVAL",
        ::core::ffi::c_int,
        hmux2::src::compat::imsg::EINVAL
    );
    constant!(
        "src/compat/imsg_buffer.rs::EINVAL",
        ::core::ffi::c_int,
        hmux2::src::compat::imsg_buffer::EINVAL
    );
    constant!(
        "src/compat/recallocarray.rs::EINVAL",
        ::core::ffi::c_int,
        hmux2::src::compat::recallocarray::EINVAL
    );
    constant!(
        "src/compat/strtonum.rs::EINVAL",
        ::core::ffi::c_int,
        hmux2::src::compat::strtonum::EINVAL
    );
    constant!(
        "src/file.rs::EINVAL",
        ::core::ffi::c_int,
        hmux2::src::file::EINVAL
    );
    constant!(
        "src/client.rs::ENAMETOOLONG",
        ::core::ffi::c_int,
        hmux2::src::client::ENAMETOOLONG
    );
    constant!(
        "src/server.rs::ENAMETOOLONG",
        ::core::ffi::c_int,
        hmux2::src::server::ENAMETOOLONG
    );
    constant!(
        "src/cfg.rs::ENOENT",
        ::core::ffi::c_int,
        hmux2::src::cfg::ENOENT
    );
    constant!(
        "src/client.rs::ENOENT",
        ::core::ffi::c_int,
        hmux2::src::client::ENOENT
    );
    constant!(
        "src/cmd_source_file.rs::ENOENT",
        ::core::ffi::c_int,
        hmux2::src::cmd_source_file::ENOENT
    );
    constant!(
        "src/cmd_source_file.rs::ENOMEM",
        ::core::ffi::c_int,
        hmux2::src::cmd_source_file::ENOMEM
    );
    constant!(
        "src/compat/recallocarray.rs::ENOMEM",
        ::core::ffi::c_int,
        hmux2::src::compat::recallocarray::ENOMEM
    );
    constant!(
        "src/file.rs::ENOMEM",
        ::core::ffi::c_int,
        hmux2::src::file::ENOMEM
    );
    constant!(
        "src/compat/imsg.rs::ERANGE",
        ::core::ffi::c_int,
        hmux2::src::compat::imsg::ERANGE
    );
    constant!(
        "src/compat/imsg_buffer.rs::ERANGE",
        ::core::ffi::c_int,
        hmux2::src::compat::imsg_buffer::ERANGE
    );
    constant!(
        "src/compat/strtonum.rs::ERANGE",
        ::core::ffi::c_int,
        hmux2::src::compat::strtonum::ERANGE
    );
    constant!(
        "src/utf8.rs::ERANGE",
        ::core::ffi::c_int,
        hmux2::src::utf8::ERANGE
    );
    let actual = records.join("\n") + "\n";
    assert_eq!(actual, include_str!("fixtures/platform-errno.txt"));
}
