//! Frozen measurements from every original translation-unit copy (Linux x86_64).
use std::mem::{align_of, offset_of, size_of};
#[test]
fn platform_layouts() {
    let mut records = Vec::new();
    macro_rules! layout {
    ($label:literal, $ty:path, [$($field:ident),*]) => {
        records.push(format!(concat!($label, " {} {}", $(" ", stringify!($field), "={}"),*),
            size_of::<$ty>(), align_of::<$ty>() $(, offset_of!($ty, $field))*));
    };
}
    macro_rules! constant {
        ($label:literal, $ty:ty, $value:path) => {{
            let value: $ty = $value;
            records.push(format!(
                concat!($label, " {:?} {} {}"),
                value,
                size_of::<$ty>(),
                align_of::<$ty>()
            ));
        }};
    }

    constant!(
        "src/client.rs::AF_UNIX",
        ::core::ffi::c_int,
        hmux2::src::client::AF_UNIX
    );
    constant!(
        "src/cmd_pipe_pane.rs::AF_UNIX",
        ::core::ffi::c_int,
        hmux2::src::cmd_pipe_pane::AF_UNIX
    );
    constant!(
        "src/job.rs::AF_UNIX",
        ::core::ffi::c_int,
        hmux2::src::job::AF_UNIX
    );
    constant!(
        "src/proc.rs::AF_UNIX",
        ::core::ffi::c_int,
        hmux2::src::proc::AF_UNIX
    );
    constant!(
        "src/server.rs::AF_UNIX",
        ::core::ffi::c_int,
        hmux2::src::server::AF_UNIX
    );
    constant!(
        "src/client.rs::PF_LOCAL",
        ::core::ffi::c_int,
        hmux2::src::client::PF_LOCAL
    );
    constant!(
        "src/cmd_pipe_pane.rs::PF_LOCAL",
        ::core::ffi::c_int,
        hmux2::src::cmd_pipe_pane::PF_LOCAL
    );
    constant!(
        "src/job.rs::PF_LOCAL",
        ::core::ffi::c_int,
        hmux2::src::job::PF_LOCAL
    );
    constant!(
        "src/proc.rs::PF_LOCAL",
        ::core::ffi::c_int,
        hmux2::src::proc::PF_LOCAL
    );
    constant!(
        "src/server.rs::PF_LOCAL",
        ::core::ffi::c_int,
        hmux2::src::server::PF_LOCAL
    );
    constant!(
        "src/client.rs::PF_UNIX",
        ::core::ffi::c_int,
        hmux2::src::client::PF_UNIX
    );
    constant!(
        "src/cmd_pipe_pane.rs::PF_UNIX",
        ::core::ffi::c_int,
        hmux2::src::cmd_pipe_pane::PF_UNIX
    );
    constant!(
        "src/job.rs::PF_UNIX",
        ::core::ffi::c_int,
        hmux2::src::job::PF_UNIX
    );
    constant!(
        "src/proc.rs::PF_UNIX",
        ::core::ffi::c_int,
        hmux2::src::proc::PF_UNIX
    );
    constant!(
        "src/server.rs::PF_UNIX",
        ::core::ffi::c_int,
        hmux2::src::server::PF_UNIX
    );
    constant!(
        "src/cmd_pipe_pane.rs::PF_UNSPEC",
        ::core::ffi::c_int,
        hmux2::src::cmd_pipe_pane::PF_UNSPEC
    );
    constant!(
        "src/job.rs::PF_UNSPEC",
        ::core::ffi::c_int,
        hmux2::src::job::PF_UNSPEC
    );
    constant!(
        "src/proc.rs::PF_UNSPEC",
        ::core::ffi::c_int,
        hmux2::src::proc::PF_UNSPEC
    );
    constant!(
        "src/client.rs::SOCK_CLOEXEC",
        hmux2::src::client::__socket_type,
        hmux2::src::client::SOCK_CLOEXEC
    );
    constant!(
        "src/cmd_pipe_pane.rs::SOCK_CLOEXEC",
        hmux2::src::cmd_pipe_pane::__socket_type,
        hmux2::src::cmd_pipe_pane::SOCK_CLOEXEC
    );
    constant!(
        "src/compat/systemd.rs::SOCK_CLOEXEC",
        hmux2::src::compat::systemd::__socket_type,
        hmux2::src::compat::systemd::SOCK_CLOEXEC
    );
    constant!(
        "src/job.rs::SOCK_CLOEXEC",
        hmux2::src::job::__socket_type,
        hmux2::src::job::SOCK_CLOEXEC
    );
    constant!(
        "src/proc.rs::SOCK_CLOEXEC",
        hmux2::src::proc::__socket_type,
        hmux2::src::proc::SOCK_CLOEXEC
    );
    constant!(
        "src/server.rs::SOCK_CLOEXEC",
        hmux2::src::server::__socket_type,
        hmux2::src::server::SOCK_CLOEXEC
    );
    constant!(
        "src/client.rs::SOCK_DCCP",
        hmux2::src::client::__socket_type,
        hmux2::src::client::SOCK_DCCP
    );
    constant!(
        "src/cmd_pipe_pane.rs::SOCK_DCCP",
        hmux2::src::cmd_pipe_pane::__socket_type,
        hmux2::src::cmd_pipe_pane::SOCK_DCCP
    );
    constant!(
        "src/compat/systemd.rs::SOCK_DCCP",
        hmux2::src::compat::systemd::__socket_type,
        hmux2::src::compat::systemd::SOCK_DCCP
    );
    constant!(
        "src/job.rs::SOCK_DCCP",
        hmux2::src::job::__socket_type,
        hmux2::src::job::SOCK_DCCP
    );
    constant!(
        "src/proc.rs::SOCK_DCCP",
        hmux2::src::proc::__socket_type,
        hmux2::src::proc::SOCK_DCCP
    );
    constant!(
        "src/server.rs::SOCK_DCCP",
        hmux2::src::server::__socket_type,
        hmux2::src::server::SOCK_DCCP
    );
    constant!(
        "src/client.rs::SOCK_DGRAM",
        hmux2::src::client::__socket_type,
        hmux2::src::client::SOCK_DGRAM
    );
    constant!(
        "src/cmd_pipe_pane.rs::SOCK_DGRAM",
        hmux2::src::cmd_pipe_pane::__socket_type,
        hmux2::src::cmd_pipe_pane::SOCK_DGRAM
    );
    constant!(
        "src/compat/systemd.rs::SOCK_DGRAM",
        hmux2::src::compat::systemd::__socket_type,
        hmux2::src::compat::systemd::SOCK_DGRAM
    );
    constant!(
        "src/job.rs::SOCK_DGRAM",
        hmux2::src::job::__socket_type,
        hmux2::src::job::SOCK_DGRAM
    );
    constant!(
        "src/proc.rs::SOCK_DGRAM",
        hmux2::src::proc::__socket_type,
        hmux2::src::proc::SOCK_DGRAM
    );
    constant!(
        "src/server.rs::SOCK_DGRAM",
        hmux2::src::server::__socket_type,
        hmux2::src::server::SOCK_DGRAM
    );
    constant!(
        "src/client.rs::SOCK_NONBLOCK",
        hmux2::src::client::__socket_type,
        hmux2::src::client::SOCK_NONBLOCK
    );
    constant!(
        "src/cmd_pipe_pane.rs::SOCK_NONBLOCK",
        hmux2::src::cmd_pipe_pane::__socket_type,
        hmux2::src::cmd_pipe_pane::SOCK_NONBLOCK
    );
    constant!(
        "src/compat/systemd.rs::SOCK_NONBLOCK",
        hmux2::src::compat::systemd::__socket_type,
        hmux2::src::compat::systemd::SOCK_NONBLOCK
    );
    constant!(
        "src/job.rs::SOCK_NONBLOCK",
        hmux2::src::job::__socket_type,
        hmux2::src::job::SOCK_NONBLOCK
    );
    constant!(
        "src/proc.rs::SOCK_NONBLOCK",
        hmux2::src::proc::__socket_type,
        hmux2::src::proc::SOCK_NONBLOCK
    );
    constant!(
        "src/server.rs::SOCK_NONBLOCK",
        hmux2::src::server::__socket_type,
        hmux2::src::server::SOCK_NONBLOCK
    );
    constant!(
        "src/client.rs::SOCK_PACKET",
        hmux2::src::client::__socket_type,
        hmux2::src::client::SOCK_PACKET
    );
    constant!(
        "src/cmd_pipe_pane.rs::SOCK_PACKET",
        hmux2::src::cmd_pipe_pane::__socket_type,
        hmux2::src::cmd_pipe_pane::SOCK_PACKET
    );
    constant!(
        "src/compat/systemd.rs::SOCK_PACKET",
        hmux2::src::compat::systemd::__socket_type,
        hmux2::src::compat::systemd::SOCK_PACKET
    );
    constant!(
        "src/job.rs::SOCK_PACKET",
        hmux2::src::job::__socket_type,
        hmux2::src::job::SOCK_PACKET
    );
    constant!(
        "src/proc.rs::SOCK_PACKET",
        hmux2::src::proc::__socket_type,
        hmux2::src::proc::SOCK_PACKET
    );
    constant!(
        "src/server.rs::SOCK_PACKET",
        hmux2::src::server::__socket_type,
        hmux2::src::server::SOCK_PACKET
    );
    constant!(
        "src/client.rs::SOCK_RAW",
        hmux2::src::client::__socket_type,
        hmux2::src::client::SOCK_RAW
    );
    constant!(
        "src/cmd_pipe_pane.rs::SOCK_RAW",
        hmux2::src::cmd_pipe_pane::__socket_type,
        hmux2::src::cmd_pipe_pane::SOCK_RAW
    );
    constant!(
        "src/compat/systemd.rs::SOCK_RAW",
        hmux2::src::compat::systemd::__socket_type,
        hmux2::src::compat::systemd::SOCK_RAW
    );
    constant!(
        "src/job.rs::SOCK_RAW",
        hmux2::src::job::__socket_type,
        hmux2::src::job::SOCK_RAW
    );
    constant!(
        "src/proc.rs::SOCK_RAW",
        hmux2::src::proc::__socket_type,
        hmux2::src::proc::SOCK_RAW
    );
    constant!(
        "src/server.rs::SOCK_RAW",
        hmux2::src::server::__socket_type,
        hmux2::src::server::SOCK_RAW
    );
    constant!(
        "src/client.rs::SOCK_RDM",
        hmux2::src::client::__socket_type,
        hmux2::src::client::SOCK_RDM
    );
    constant!(
        "src/cmd_pipe_pane.rs::SOCK_RDM",
        hmux2::src::cmd_pipe_pane::__socket_type,
        hmux2::src::cmd_pipe_pane::SOCK_RDM
    );
    constant!(
        "src/compat/systemd.rs::SOCK_RDM",
        hmux2::src::compat::systemd::__socket_type,
        hmux2::src::compat::systemd::SOCK_RDM
    );
    constant!(
        "src/job.rs::SOCK_RDM",
        hmux2::src::job::__socket_type,
        hmux2::src::job::SOCK_RDM
    );
    constant!(
        "src/proc.rs::SOCK_RDM",
        hmux2::src::proc::__socket_type,
        hmux2::src::proc::SOCK_RDM
    );
    constant!(
        "src/server.rs::SOCK_RDM",
        hmux2::src::server::__socket_type,
        hmux2::src::server::SOCK_RDM
    );
    constant!(
        "src/client.rs::SOCK_SEQPACKET",
        hmux2::src::client::__socket_type,
        hmux2::src::client::SOCK_SEQPACKET
    );
    constant!(
        "src/cmd_pipe_pane.rs::SOCK_SEQPACKET",
        hmux2::src::cmd_pipe_pane::__socket_type,
        hmux2::src::cmd_pipe_pane::SOCK_SEQPACKET
    );
    constant!(
        "src/compat/systemd.rs::SOCK_SEQPACKET",
        hmux2::src::compat::systemd::__socket_type,
        hmux2::src::compat::systemd::SOCK_SEQPACKET
    );
    constant!(
        "src/job.rs::SOCK_SEQPACKET",
        hmux2::src::job::__socket_type,
        hmux2::src::job::SOCK_SEQPACKET
    );
    constant!(
        "src/proc.rs::SOCK_SEQPACKET",
        hmux2::src::proc::__socket_type,
        hmux2::src::proc::SOCK_SEQPACKET
    );
    constant!(
        "src/server.rs::SOCK_SEQPACKET",
        hmux2::src::server::__socket_type,
        hmux2::src::server::SOCK_SEQPACKET
    );
    constant!(
        "src/client.rs::SOCK_STREAM",
        hmux2::src::client::__socket_type,
        hmux2::src::client::SOCK_STREAM
    );
    constant!(
        "src/cmd_pipe_pane.rs::SOCK_STREAM",
        hmux2::src::cmd_pipe_pane::__socket_type,
        hmux2::src::cmd_pipe_pane::SOCK_STREAM
    );
    constant!(
        "src/compat/systemd.rs::SOCK_STREAM",
        hmux2::src::compat::systemd::__socket_type,
        hmux2::src::compat::systemd::SOCK_STREAM
    );
    constant!(
        "src/job.rs::SOCK_STREAM",
        hmux2::src::job::__socket_type,
        hmux2::src::job::SOCK_STREAM
    );
    constant!(
        "src/proc.rs::SOCK_STREAM",
        hmux2::src::proc::__socket_type,
        hmux2::src::proc::SOCK_STREAM
    );
    constant!(
        "src/server.rs::SOCK_STREAM",
        hmux2::src::server::__socket_type,
        hmux2::src::server::SOCK_STREAM
    );
    constant!(
        "src/compat/getpeereid.rs::SOL_SOCKET",
        ::core::ffi::c_int,
        hmux2::src::compat::getpeereid::SOL_SOCKET
    );
    constant!(
        "src/compat/imsg_buffer.rs::SOL_SOCKET",
        ::core::ffi::c_int,
        hmux2::src::compat::imsg_buffer::SOL_SOCKET
    );
    layout!(
        "src/client.rs::__CONST_SOCKADDR_ARG",
        hmux2::src::client::__CONST_SOCKADDR_ARG,
        [
            __sockaddr__,
            __sockaddr_at__,
            __sockaddr_ax25__,
            __sockaddr_dl__,
            __sockaddr_eon__,
            __sockaddr_in__,
            __sockaddr_in6__,
            __sockaddr_inarp__,
            __sockaddr_ipx__,
            __sockaddr_iso__,
            __sockaddr_ns__,
            __sockaddr_un__,
            __sockaddr_x25__
        ]
    );
    layout!(
        "src/server.rs::__CONST_SOCKADDR_ARG",
        hmux2::src::server::__CONST_SOCKADDR_ARG,
        [
            __sockaddr__,
            __sockaddr_at__,
            __sockaddr_ax25__,
            __sockaddr_dl__,
            __sockaddr_eon__,
            __sockaddr_in__,
            __sockaddr_in6__,
            __sockaddr_inarp__,
            __sockaddr_ipx__,
            __sockaddr_iso__,
            __sockaddr_ns__,
            __sockaddr_un__,
            __sockaddr_x25__
        ]
    );
    layout!(
        "src/compat/systemd.rs::__SOCKADDR_ARG",
        hmux2::src::compat::systemd::__SOCKADDR_ARG,
        [
            __sockaddr__,
            __sockaddr_at__,
            __sockaddr_ax25__,
            __sockaddr_dl__,
            __sockaddr_eon__,
            __sockaddr_in__,
            __sockaddr_in6__,
            __sockaddr_inarp__,
            __sockaddr_ipx__,
            __sockaddr_iso__,
            __sockaddr_ns__,
            __sockaddr_un__,
            __sockaddr_x25__
        ]
    );
    layout!(
        "src/server.rs::__SOCKADDR_ARG",
        hmux2::src::server::__SOCKADDR_ARG,
        [
            __sockaddr__,
            __sockaddr_at__,
            __sockaddr_ax25__,
            __sockaddr_dl__,
            __sockaddr_eon__,
            __sockaddr_in__,
            __sockaddr_in6__,
            __sockaddr_inarp__,
            __sockaddr_ipx__,
            __sockaddr_iso__,
            __sockaddr_ns__,
            __sockaddr_un__,
            __sockaddr_x25__
        ]
    );
    layout!(
        "src/client.rs::__socket_type",
        hmux2::src::client::__socket_type,
        []
    );
    layout!(
        "src/cmd_pipe_pane.rs::__socket_type",
        hmux2::src::cmd_pipe_pane::__socket_type,
        []
    );
    layout!(
        "src/compat/systemd.rs::__socket_type",
        hmux2::src::compat::systemd::__socket_type,
        []
    );
    layout!(
        "src/job.rs::__socket_type",
        hmux2::src::job::__socket_type,
        []
    );
    layout!(
        "src/proc.rs::__socket_type",
        hmux2::src::proc::__socket_type,
        []
    );
    layout!(
        "src/server.rs::__socket_type",
        hmux2::src::server::__socket_type,
        []
    );
    layout!(
        "src/client.rs::in6_addr",
        hmux2::src::client::in6_addr,
        [__in6_u]
    );
    layout!(
        "src/compat/systemd.rs::in6_addr",
        hmux2::src::compat::systemd::in6_addr,
        [__in6_u]
    );
    layout!(
        "src/server.rs::in6_addr",
        hmux2::src::server::in6_addr,
        [__in6_u]
    );
    layout!(
        "src/client.rs::C2RustUnnamed",
        hmux2::src::client::in6_addr___in6_u,
        [__u6_addr8, __u6_addr16, __u6_addr32]
    );
    layout!(
        "src/compat/systemd.rs::C2RustUnnamed",
        hmux2::src::compat::systemd::in6_addr___in6_u,
        [__u6_addr8, __u6_addr16, __u6_addr32]
    );
    layout!(
        "src/server.rs::C2RustUnnamed",
        hmux2::src::server::in6_addr___in6_u,
        [__u6_addr8, __u6_addr16, __u6_addr32]
    );
    layout!(
        "src/client.rs::in_addr",
        hmux2::src::client::in_addr,
        [s_addr]
    );
    layout!(
        "src/compat/systemd.rs::in_addr",
        hmux2::src::compat::systemd::in_addr,
        [s_addr]
    );
    layout!(
        "src/server.rs::in_addr",
        hmux2::src::server::in_addr,
        [s_addr]
    );
    layout!(
        "src/client.rs::in_addr_t",
        hmux2::src::client::in_addr_t,
        []
    );
    layout!(
        "src/compat/systemd.rs::in_addr_t",
        hmux2::src::compat::systemd::in_addr_t,
        []
    );
    layout!(
        "src/server.rs::in_addr_t",
        hmux2::src::server::in_addr_t,
        []
    );
    layout!(
        "src/client.rs::in_port_t",
        hmux2::src::client::in_port_t,
        []
    );
    layout!(
        "src/compat/systemd.rs::in_port_t",
        hmux2::src::compat::systemd::in_port_t,
        []
    );
    layout!(
        "src/server.rs::in_port_t",
        hmux2::src::server::in_port_t,
        []
    );
    layout!(
        "src/client.rs::sa_family_t",
        hmux2::src::client::sa_family_t,
        []
    );
    layout!(
        "src/compat/systemd.rs::sa_family_t",
        hmux2::src::compat::systemd::sa_family_t,
        []
    );
    layout!(
        "src/server.rs::sa_family_t",
        hmux2::src::server::sa_family_t,
        []
    );
    layout!(
        "src/client.rs::sockaddr",
        hmux2::src::client::sockaddr,
        [sa_family, sa_data]
    );
    layout!(
        "src/compat/systemd.rs::sockaddr",
        hmux2::src::compat::systemd::sockaddr,
        [sa_family, sa_data]
    );
    layout!(
        "src/server.rs::sockaddr",
        hmux2::src::server::sockaddr,
        [sa_family, sa_data]
    );
    layout!(
        "src/client.rs::sockaddr_in",
        hmux2::src::client::sockaddr_in,
        [sin_family, sin_port, sin_addr, sin_zero]
    );
    layout!(
        "src/compat/systemd.rs::sockaddr_in",
        hmux2::src::compat::systemd::sockaddr_in,
        [sin_family, sin_port, sin_addr, sin_zero]
    );
    layout!(
        "src/server.rs::sockaddr_in",
        hmux2::src::server::sockaddr_in,
        [sin_family, sin_port, sin_addr, sin_zero]
    );
    layout!(
        "src/client.rs::sockaddr_in6",
        hmux2::src::client::sockaddr_in6,
        [
            sin6_family,
            sin6_port,
            sin6_flowinfo,
            sin6_addr,
            sin6_scope_id
        ]
    );
    layout!(
        "src/compat/systemd.rs::sockaddr_in6",
        hmux2::src::compat::systemd::sockaddr_in6,
        [
            sin6_family,
            sin6_port,
            sin6_flowinfo,
            sin6_addr,
            sin6_scope_id
        ]
    );
    layout!(
        "src/server.rs::sockaddr_in6",
        hmux2::src::server::sockaddr_in6,
        [
            sin6_family,
            sin6_port,
            sin6_flowinfo,
            sin6_addr,
            sin6_scope_id
        ]
    );
    layout!(
        "src/client.rs::sockaddr_un",
        hmux2::src::client::sockaddr_un,
        [sun_family, sun_path]
    );
    layout!(
        "src/compat/systemd.rs::sockaddr_un",
        hmux2::src::compat::systemd::sockaddr_un,
        [sun_family, sun_path]
    );
    layout!(
        "src/server.rs::sockaddr_un",
        hmux2::src::server::sockaddr_un,
        [sun_family, sun_path]
    );
    let actual = records.join("\n") + "\n";
    assert_eq!(actual, include_str!("fixtures/platform-socket.txt"));
}
