//! Frozen measurements from every original translation-unit copy (Linux x86_64).
use std::mem::{align_of, size_of};
#[test]
fn platform_layouts() {
    let mut records = Vec::new();
    macro_rules! constant {
        ($label:literal, $ty:ty, $value:path) => {{
            let value: $ty = $value;
            records.push(format!(
                concat!($label, " {:?} {} {}"),
                value,
                size_of::<$ty>(),
                align_of::<$ty>()
            ));
        }};
    }

    constant!(
        "src/cmd_find.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::cmd_find::INT_MAX
    );
    constant!(
        "src/cmd_join_pane.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::cmd_join_pane::INT_MAX
    );
    constant!(
        "src/cmd_refresh_client.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::cmd_refresh_client::INT_MAX
    );
    constant!(
        "src/cmd_resize_pane.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::cmd_resize_pane::INT_MAX
    );
    constant!(
        "src/cmd_resize_window.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::cmd_resize_window::INT_MAX
    );
    constant!(
        "src/compat/fdforkpty.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::compat::fdforkpty::INT_MAX
    );
    constant!(
        "src/input.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::input::INT_MAX
    );
    constant!(
        "src/layout.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::layout::INT_MAX
    );
    constant!(
        "src/layout_custom.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::layout_custom::INT_MAX
    );
    constant!(
        "src/options_table.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::options_table::INT_MAX
    );
    constant!(
        "src/tty_term.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::tty_term::INT_MAX
    );
    constant!(
        "src/window.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::window::INT_MAX
    );
    constant!(
        "src/window_copy.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::window_copy::INT_MAX
    );
    constant!(
        "src/window_customize.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::window_customize::INT_MAX
    );
    constant!(
        "src/xmalloc.rs::INT_MAX",
        ::core::ffi::c_int,
        hmux2::src::xmalloc::INT_MAX
    );
    constant!(
        "src/cmd_capture_pane.rs::INT_MIN",
        ::core::ffi::c_int,
        hmux2::src::cmd_capture_pane::INT_MIN
    );
    constant!(
        "src/cmd_join_pane.rs::INT_MIN",
        ::core::ffi::c_int,
        hmux2::src::cmd_join_pane::INT_MIN
    );
    constant!(
        "src/cmd_resize_pane.rs::INT_MIN",
        ::core::ffi::c_int,
        hmux2::src::cmd_resize_pane::INT_MIN
    );
    constant!(
        "src/cmd_capture_pane.rs::SHRT_MAX",
        ::core::ffi::c_int,
        hmux2::src::cmd_capture_pane::SHRT_MAX
    );
    constant!(
        "src/options_table.rs::SHRT_MAX",
        ::core::ffi::c_int,
        hmux2::src::options_table::SHRT_MAX
    );
    constant!(
        "src/cmd.rs::SIZE_MAX",
        ::core::ffi::c_ulong,
        hmux2::src::cmd::SIZE_MAX
    );
    constant!(
        "src/cmd_parse.rs::SIZE_MAX",
        ::core::ffi::c_ulong,
        hmux2::src::cmd_parse::SIZE_MAX
    );
    constant!(
        "src/compat/imsg_buffer.rs::SIZE_MAX",
        ::core::ffi::c_ulong,
        hmux2::src::compat::imsg_buffer::SIZE_MAX
    );
    constant!(
        "src/control.rs::SIZE_MAX",
        ::core::ffi::c_ulong,
        hmux2::src::control::SIZE_MAX
    );
    constant!(
        "src/screen_redraw.rs::SIZE_MAX",
        ::core::ffi::c_ulong,
        hmux2::src::screen_redraw::SIZE_MAX
    );
    constant!(
        "src/server_client.rs::SIZE_MAX",
        ::core::ffi::c_ulong,
        hmux2::src::server_client::SIZE_MAX
    );
    constant!(
        "src/spawn.rs::SIZE_MAX",
        ::core::ffi::c_ulong,
        hmux2::src::spawn::SIZE_MAX
    );
    constant!(
        "src/xmalloc.rs::SIZE_MAX",
        ::core::ffi::c_ulong,
        hmux2::src::xmalloc::SIZE_MAX
    );
    constant!(
        "src/compat/vis.rs::UCHAR_MAX",
        ::core::ffi::c_int,
        hmux2::src::compat::vis::UCHAR_MAX
    );
    constant!(
        "src/window_copy.rs::UCHAR_MAX",
        ::core::ffi::c_int,
        hmux2::src::window_copy::UCHAR_MAX
    );
    constant!(
        "src/compat/imsg.rs::UINT32_MAX",
        ::core::ffi::c_uint,
        hmux2::src::compat::imsg::UINT32_MAX
    );
    constant!(
        "src/compat/imsg_buffer.rs::UINT32_MAX",
        ::core::ffi::c_uint,
        hmux2::src::compat::imsg_buffer::UINT32_MAX
    );
    constant!(
        "src/cmd_display_menu.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::cmd_display_menu::UINT_MAX
    );
    constant!(
        "src/cmd_display_message.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::cmd_display_message::UINT_MAX
    );
    constant!(
        "src/cmd_join_pane.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::cmd_join_pane::UINT_MAX
    );
    constant!(
        "src/cmd_parse.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::cmd_parse::UINT_MAX
    );
    constant!(
        "src/cmd_send_keys.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::cmd_send_keys::UINT_MAX
    );
    constant!(
        "src/grid.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::grid::UINT_MAX
    );
    constant!(
        "src/layout.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::layout::UINT_MAX
    );
    constant!(
        "src/menu.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::menu::UINT_MAX
    );
    constant!(
        "src/options.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::options::UINT_MAX
    );
    constant!(
        "src/options_table.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::options_table::UINT_MAX
    );
    constant!(
        "src/resize.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::resize::UINT_MAX
    );
    constant!(
        "src/screen.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::screen::UINT_MAX
    );
    constant!(
        "src/screen_write.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::screen_write::UINT_MAX
    );
    constant!(
        "src/server_client.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::server_client::UINT_MAX
    );
    constant!(
        "src/session.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::session::UINT_MAX
    );
    constant!(
        "src/style.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::style::UINT_MAX
    );
    constant!(
        "src/tty.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::tty::UINT_MAX
    );
    constant!(
        "src/window.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::window::UINT_MAX
    );
    constant!(
        "src/window_copy.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::window_copy::UINT_MAX
    );
    constant!(
        "src/window_panes.rs::UINT_MAX",
        ::core::ffi::c_uint,
        hmux2::src::window_panes::UINT_MAX
    );
    constant!(
        "src/cmd_new_session.rs::USHRT_MAX",
        ::core::ffi::c_int,
        hmux2::src::cmd_new_session::USHRT_MAX
    );
    constant!(
        "src/options_table.rs::USHRT_MAX",
        ::core::ffi::c_int,
        hmux2::src::options_table::USHRT_MAX
    );
    constant!(
        "src/cmd_capture_pane.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::cmd_capture_pane::__INT_MAX__
    );
    constant!(
        "src/cmd_display_menu.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::cmd_display_menu::__INT_MAX__
    );
    constant!(
        "src/cmd_display_message.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::cmd_display_message::__INT_MAX__
    );
    constant!(
        "src/cmd_find.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::cmd_find::__INT_MAX__
    );
    constant!(
        "src/cmd_join_pane.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::cmd_join_pane::__INT_MAX__
    );
    constant!(
        "src/cmd_parse.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::cmd_parse::__INT_MAX__
    );
    constant!(
        "src/cmd_refresh_client.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::cmd_refresh_client::__INT_MAX__
    );
    constant!(
        "src/cmd_resize_pane.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::cmd_resize_pane::__INT_MAX__
    );
    constant!(
        "src/cmd_resize_window.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::cmd_resize_window::__INT_MAX__
    );
    constant!(
        "src/cmd_send_keys.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::cmd_send_keys::__INT_MAX__
    );
    constant!(
        "src/compat/fdforkpty.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::compat::fdforkpty::__INT_MAX__
    );
    constant!(
        "src/grid.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::grid::__INT_MAX__
    );
    constant!(
        "src/input.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::input::__INT_MAX__
    );
    constant!(
        "src/layout.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::layout::__INT_MAX__
    );
    constant!(
        "src/layout_custom.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::layout_custom::__INT_MAX__
    );
    constant!(
        "src/menu.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::menu::__INT_MAX__
    );
    constant!(
        "src/options.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::options::__INT_MAX__
    );
    constant!(
        "src/options_table.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::options_table::__INT_MAX__
    );
    constant!(
        "src/resize.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::resize::__INT_MAX__
    );
    constant!(
        "src/screen.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::screen::__INT_MAX__
    );
    constant!(
        "src/screen_write.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::screen_write::__INT_MAX__
    );
    constant!(
        "src/server_client.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::server_client::__INT_MAX__
    );
    constant!(
        "src/session.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::session::__INT_MAX__
    );
    constant!(
        "src/style.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::style::__INT_MAX__
    );
    constant!(
        "src/tty.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::tty::__INT_MAX__
    );
    constant!(
        "src/tty_term.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::tty_term::__INT_MAX__
    );
    constant!(
        "src/window.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::window::__INT_MAX__
    );
    constant!(
        "src/window_copy.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::window_copy::__INT_MAX__
    );
    constant!(
        "src/window_customize.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::window_customize::__INT_MAX__
    );
    constant!(
        "src/window_panes.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::window_panes::__INT_MAX__
    );
    constant!(
        "src/xmalloc.rs::__INT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::xmalloc::__INT_MAX__
    );
    constant!(
        "src/compat/strtonum.rs::__LONG_LONG_MAX__",
        ::core::ffi::c_longlong,
        hmux2::src::compat::strtonum::__LONG_LONG_MAX__
    );
    constant!(
        "src/utf8.rs::__LONG_LONG_MAX__",
        ::core::ffi::c_longlong,
        hmux2::src::utf8::__LONG_LONG_MAX__
    );
    constant!(
        "src/compat/vis.rs::__SCHAR_MAX__",
        ::core::ffi::c_int,
        hmux2::src::compat::vis::__SCHAR_MAX__
    );
    constant!(
        "src/window_copy.rs::__SCHAR_MAX__",
        ::core::ffi::c_int,
        hmux2::src::window_copy::__SCHAR_MAX__
    );
    constant!(
        "src/cmd_capture_pane.rs::__SHRT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::cmd_capture_pane::__SHRT_MAX__
    );
    constant!(
        "src/cmd_new_session.rs::__SHRT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::cmd_new_session::__SHRT_MAX__
    );
    constant!(
        "src/options_table.rs::__SHRT_MAX__",
        ::core::ffi::c_int,
        hmux2::src::options_table::__SHRT_MAX__
    );
    let actual = records.join("\n") + "\n";
    assert_eq!(actual, include_str!("fixtures/platform-limits.txt"));
}
