//! Frozen pre-migration sizes, alignments, and every named field offset.
use std::mem::{align_of, offset_of, size_of};
#[test]
fn original_copies_match() {
    let mut records = Vec::new();
    macro_rules! record {
        ($label:literal, $ty:ty, [$($field:ident),*]) => {
            records.push(format!("{} {} {} {:?}", $label, size_of::<$ty>(), align_of::<$ty>(),
                &[$(offset_of!($ty, $field)),*] as &[usize]));
        };
    }
    record!(
        "src/mode_tree.rs::prompt_create_data",
        hmux2::src::mode_tree::prompt_create_data,
        [
            fs,
            prompt,
            input,
            type_0,
            flags,
            style,
            command_style,
            style_str,
            command_style_str,
            cstyle,
            command_cstyle,
            ccolour,
            command_ccolour,
            cmode,
            command_cmode,
            message_format,
            keys,
            word_separators,
            inputcb,
            freecb,
            data
        ]
    );
    record!(
        "src/prompt.rs::prompt_create_data",
        hmux2::src::prompt::prompt_create_data,
        [
            fs,
            prompt,
            input,
            type_0,
            flags,
            style,
            command_style,
            style_str,
            command_style_str,
            cstyle,
            command_cstyle,
            ccolour,
            command_ccolour,
            cmode,
            command_cmode,
            message_format,
            keys,
            word_separators,
            inputcb,
            freecb,
            data
        ]
    );
    record!(
        "src/status.rs::prompt_create_data",
        hmux2::src::status::prompt_create_data,
        [
            fs,
            prompt,
            input,
            type_0,
            flags,
            style,
            command_style,
            style_str,
            command_style_str,
            cstyle,
            command_cstyle,
            ccolour,
            command_ccolour,
            cmode,
            command_cmode,
            message_format,
            keys,
            word_separators,
            inputcb,
            freecb,
            data
        ]
    );
    record!(
        "src/window.rs::prompt_create_data",
        hmux2::src::window::prompt_create_data,
        [
            fs,
            prompt,
            input,
            type_0,
            flags,
            style,
            command_style,
            style_str,
            command_style_str,
            cstyle,
            command_cstyle,
            ccolour,
            command_ccolour,
            cmode,
            command_cmode,
            message_format,
            keys,
            word_separators,
            inputcb,
            freecb,
            data
        ]
    );
    record!(
        "src/window_switch.rs::prompt_create_data",
        hmux2::src::window_switch::prompt_create_data,
        [
            fs,
            prompt,
            input,
            type_0,
            flags,
            style,
            command_style,
            style_str,
            command_style_str,
            cstyle,
            command_cstyle,
            ccolour,
            command_ccolour,
            cmode,
            command_cmode,
            message_format,
            keys,
            word_separators,
            inputcb,
            freecb,
            data
        ]
    );
    record!(
        "src/mode_tree.rs::prompt_draw_data",
        hmux2::src::mode_tree::prompt_draw_data,
        [ctx, cursor_x, area_x, area_width, prompt_line]
    );
    record!(
        "src/prompt.rs::prompt_draw_data",
        hmux2::src::prompt::prompt_draw_data,
        [ctx, cursor_x, area_x, area_width, prompt_line]
    );
    record!(
        "src/screen_redraw.rs::prompt_draw_data",
        hmux2::src::screen_redraw::prompt_draw_data,
        [ctx, cursor_x, area_x, area_width, prompt_line]
    );
    record!(
        "src/status.rs::prompt_draw_data",
        hmux2::src::status::prompt_draw_data,
        [ctx, cursor_x, area_x, area_width, prompt_line]
    );
    record!(
        "src/window_switch.rs::prompt_draw_data",
        hmux2::src::window_switch::prompt_draw_data,
        [ctx, cursor_x, area_x, area_width, prompt_line]
    );
    let actual = records.join("\n") + "\n";
    assert_eq!(actual, include_str!("fixtures/remaining-prompt.txt"));
}
