//! Snapshot of the shared client registry type exported by client modules.
use std::mem::{align_of, offset_of, size_of};
#[test]
fn client_registry_exports_match() {
    let mut records = Vec::new();
    macro_rules! record {
        ($label:literal, $ty:ty, [$($field:ident),*]) => {
            records.push(format!("{} {} {} {:?}", $label, size_of::<$ty>(), align_of::<$ty>(),
                &[$(offset_of!($ty, $field)),*] as &[usize]));
        };
    }
    record!(
        "src/alerts.rs::clients",
        hmux2::src::alerts::clients,
        []
    );
    record!(
        "src/cfg.rs::clients",
        hmux2::src::cfg::clients,
        []
    );
    record!(
        "src/cmd_attach_session.rs::clients",
        hmux2::src::cmd_attach_session::clients,
        []
    );
    record!(
        "src/cmd_detach_client.rs::clients",
        hmux2::src::cmd_detach_client::clients,
        []
    );
    record!(
        "src/cmd_find.rs::clients",
        hmux2::src::cmd_find::clients,
        []
    );
    record!(
        "src/cmd_select_pane.rs::clients",
        hmux2::src::cmd_select_pane::clients,
        []
    );
    record!(
        "src/control_notify.rs::clients",
        hmux2::src::control_notify::clients,
        []
    );
    record!(
        "src/format.rs::clients",
        hmux2::src::format::clients,
        []
    );
    record!(
        "src/input.rs::clients",
        hmux2::src::input::clients,
        []
    );
    record!(
        "src/key_bindings.rs::clients",
        hmux2::src::key_bindings::clients,
        []
    );
    record!(
        "src/options.rs::clients",
        hmux2::src::options::clients,
        []
    );
    record!(
        "src/resize.rs::clients",
        hmux2::src::resize::clients,
        []
    );
    record!(
        "src/server.rs::clients",
        hmux2::src::server::clients,
        []
    );
    record!(
        "src/server_acl.rs::clients",
        hmux2::src::server_acl::clients,
        []
    );
    record!(
        "src/server_client.rs::clients",
        hmux2::src::server_client::clients,
        []
    );
    record!(
        "src/server_fn.rs::clients",
        hmux2::src::server_fn::clients,
        []
    );
    record!(
        "src/sort.rs::clients",
        hmux2::src::sort::clients,
        []
    );
    record!(
        "src/spawn.rs::clients",
        hmux2::src::spawn::clients,
        []
    );
    record!(
        "src/status.rs::clients",
        hmux2::src::status::clients,
        []
    );
    record!(
        "src/tty.rs::clients",
        hmux2::src::tty::clients,
        []
    );
    record!(
        "src/window.rs::clients",
        hmux2::src::window::clients,
        []
    );
    let actual = records.join("\n") + "\n";
    assert_eq!(actual, include_str!("fixtures/remaining-client.txt"));
}
