//! Frozen pre-migration sizes, alignments, and every named field offset.
use std::mem::{align_of, offset_of, size_of};
#[test]
fn original_copies_match() {
    let mut records = Vec::new();
    macro_rules! record {
        ($label:literal, $ty:ty, [$($field:ident),*]) => {
            records.push(format!("{} {} {} {:?}", $label, size_of::<$ty>(), align_of::<$ty>(),
                &[$(offset_of!($ty, $field)),*] as &[usize]));
        };
    }
    record!(
        "src/mode_tree.rs::mode_tree_build_cb",
        hmux2::src::mode_tree::mode_tree_build_cb,
        []
    );
    record!(
        "src/window_buffer.rs::mode_tree_build_cb",
        hmux2::src::window_buffer::mode_tree_build_cb,
        []
    );
    record!(
        "src/window_client.rs::mode_tree_build_cb",
        hmux2::src::window_client::mode_tree_build_cb,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_build_cb",
        hmux2::src::window_customize::mode_tree_build_cb,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_build_cb",
        hmux2::src::window_tree::mode_tree_build_cb,
        []
    );
    record!(
        "src/mode_tree.rs::mode_tree_data",
        hmux2::src::mode_tree::mode_tree_data,
        [
            dead,
            references,
            zoomed,
            wp,
            modedata,
            menu,
            sort_crit,
            view_name,
            buildcb,
            drawcb,
            searchcb,
            menucb,
            heightcb,
            keycb,
            swapcb,
            sortcb,
            helpcb,
            children,
            saved,
            line_list,
            line_size,
            depth,
            maxdepth,
            width,
            height,
            offset,
            current,
            screen,
            prompt,
            prompt_data,
            prompt_cx,
            prompt_top,
            preview,
            search,
            filter,
            no_matches,
            search_dir,
            search_icase,
            help
        ]
    );
    record!(
        "src/window_buffer.rs::mode_tree_data",
        *mut hmux2::src::window_buffer::mode_tree_data,
        []
    );
    record!(
        "src/window_client.rs::mode_tree_data",
        *mut hmux2::src::window_client::mode_tree_data,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_data",
        *mut hmux2::src::window_customize::mode_tree_data,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_data",
        *mut hmux2::src::window_tree::mode_tree_data,
        []
    );
    record!(
        "src/mode_tree.rs::mode_tree_draw_cb",
        hmux2::src::mode_tree::mode_tree_draw_cb,
        []
    );
    record!(
        "src/window_buffer.rs::mode_tree_draw_cb",
        hmux2::src::window_buffer::mode_tree_draw_cb,
        []
    );
    record!(
        "src/window_client.rs::mode_tree_draw_cb",
        hmux2::src::window_client::mode_tree_draw_cb,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_draw_cb",
        hmux2::src::window_customize::mode_tree_draw_cb,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_draw_cb",
        hmux2::src::window_tree::mode_tree_draw_cb,
        []
    );
    record!(
        "src/mode_tree.rs::mode_tree_each_cb",
        hmux2::src::mode_tree::mode_tree_each_cb,
        []
    );
    record!(
        "src/window_buffer.rs::mode_tree_each_cb",
        hmux2::src::window_buffer::mode_tree_each_cb,
        []
    );
    record!(
        "src/window_client.rs::mode_tree_each_cb",
        hmux2::src::window_client::mode_tree_each_cb,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_each_cb",
        hmux2::src::window_customize::mode_tree_each_cb,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_each_cb",
        hmux2::src::window_tree::mode_tree_each_cb,
        []
    );
    record!(
        "src/mode_tree.rs::mode_tree_height_cb",
        hmux2::src::mode_tree::mode_tree_height_cb,
        []
    );
    record!(
        "src/window_buffer.rs::mode_tree_height_cb",
        hmux2::src::window_buffer::mode_tree_height_cb,
        []
    );
    record!(
        "src/window_client.rs::mode_tree_height_cb",
        hmux2::src::window_client::mode_tree_height_cb,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_height_cb",
        hmux2::src::window_customize::mode_tree_height_cb,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_height_cb",
        hmux2::src::window_tree::mode_tree_height_cb,
        []
    );
    record!(
        "src/mode_tree.rs::mode_tree_help_cb",
        hmux2::src::mode_tree::mode_tree_help_cb,
        []
    );
    record!(
        "src/window_buffer.rs::mode_tree_help_cb",
        hmux2::src::window_buffer::mode_tree_help_cb,
        []
    );
    record!(
        "src/window_client.rs::mode_tree_help_cb",
        hmux2::src::window_client::mode_tree_help_cb,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_help_cb",
        hmux2::src::window_customize::mode_tree_help_cb,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_help_cb",
        hmux2::src::window_tree::mode_tree_help_cb,
        []
    );
    record!(
        "src/mode_tree.rs::mode_tree_item",
        hmux2::src::mode_tree::mode_tree_item,
        [
            parent,
            itemdata,
            line,
            key,
            keystr,
            keylen,
            tag,
            name,
            text,
            expanded,
            tagged,
            draw_as_parent,
            no_tag,
            align,
            children,
            entry
        ]
    );
    record!(
        "src/window_buffer.rs::mode_tree_item",
        *mut hmux2::src::window_buffer::mode_tree_item,
        []
    );
    record!(
        "src/window_client.rs::mode_tree_item",
        *mut hmux2::src::window_client::mode_tree_item,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_item",
        *mut hmux2::src::window_customize::mode_tree_item,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_item",
        *mut hmux2::src::window_tree::mode_tree_item,
        []
    );
    record!(
        "src/mode_tree.rs::C2RustUnnamed_35",
        hmux2::src::mode_tree::mode_tree_item_entry,
        [tqe_next, tqe_prev]
    );
    record!(
        "src/mode_tree.rs::mode_tree_key_cb",
        hmux2::src::mode_tree::mode_tree_key_cb,
        []
    );
    record!(
        "src/window_buffer.rs::mode_tree_key_cb",
        hmux2::src::window_buffer::mode_tree_key_cb,
        []
    );
    record!(
        "src/window_client.rs::mode_tree_key_cb",
        hmux2::src::window_client::mode_tree_key_cb,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_key_cb",
        hmux2::src::window_customize::mode_tree_key_cb,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_key_cb",
        hmux2::src::window_tree::mode_tree_key_cb,
        []
    );
    record!(
        "src/mode_tree.rs::mode_tree_line",
        hmux2::src::mode_tree::mode_tree_line,
        [item, depth, last, flat]
    );
    record!(
        "src/mode_tree.rs::mode_tree_list",
        hmux2::src::mode_tree::mode_tree_list,
        [tqh_first, tqh_last]
    );
    record!(
        "src/mode_tree.rs::mode_tree_menu_cb",
        hmux2::src::mode_tree::mode_tree_menu_cb,
        []
    );
    record!(
        "src/window_buffer.rs::mode_tree_menu_cb",
        hmux2::src::window_buffer::mode_tree_menu_cb,
        []
    );
    record!(
        "src/window_client.rs::mode_tree_menu_cb",
        hmux2::src::window_client::mode_tree_menu_cb,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_menu_cb",
        hmux2::src::window_customize::mode_tree_menu_cb,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_menu_cb",
        hmux2::src::window_tree::mode_tree_menu_cb,
        []
    );
    record!(
        "src/mode_tree.rs::mode_tree_prompt",
        hmux2::src::mode_tree::mode_tree_prompt,
        [mtd, c, inputcb, freecb, data]
    );
    record!(
        "src/mode_tree.rs::mode_tree_prompt_input_cb",
        hmux2::src::mode_tree::mode_tree_prompt_input_cb,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_prompt_input_cb",
        hmux2::src::window_customize::mode_tree_prompt_input_cb,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_prompt_input_cb",
        hmux2::src::window_tree::mode_tree_prompt_input_cb,
        []
    );
    record!(
        "src/mode_tree.rs::mode_tree_search_cb",
        hmux2::src::mode_tree::mode_tree_search_cb,
        []
    );
    record!(
        "src/window_buffer.rs::mode_tree_search_cb",
        hmux2::src::window_buffer::mode_tree_search_cb,
        []
    );
    record!(
        "src/window_client.rs::mode_tree_search_cb",
        hmux2::src::window_client::mode_tree_search_cb,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_search_cb",
        hmux2::src::window_customize::mode_tree_search_cb,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_search_cb",
        hmux2::src::window_tree::mode_tree_search_cb,
        []
    );
    record!(
        "src/mode_tree.rs::mode_tree_search_dir",
        hmux2::src::mode_tree::mode_tree_search_dir,
        []
    );
    record!(
        "src/mode_tree.rs::mode_tree_sort_cb",
        hmux2::src::mode_tree::mode_tree_sort_cb,
        []
    );
    record!(
        "src/window_buffer.rs::mode_tree_sort_cb",
        hmux2::src::window_buffer::mode_tree_sort_cb,
        []
    );
    record!(
        "src/window_client.rs::mode_tree_sort_cb",
        hmux2::src::window_client::mode_tree_sort_cb,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_sort_cb",
        hmux2::src::window_customize::mode_tree_sort_cb,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_sort_cb",
        hmux2::src::window_tree::mode_tree_sort_cb,
        []
    );
    record!(
        "src/mode_tree.rs::mode_tree_swap_cb",
        hmux2::src::mode_tree::mode_tree_swap_cb,
        []
    );
    record!(
        "src/window_buffer.rs::mode_tree_swap_cb",
        hmux2::src::window_buffer::mode_tree_swap_cb,
        []
    );
    record!(
        "src/window_client.rs::mode_tree_swap_cb",
        hmux2::src::window_client::mode_tree_swap_cb,
        []
    );
    record!(
        "src/window_customize.rs::mode_tree_swap_cb",
        hmux2::src::window_customize::mode_tree_swap_cb,
        []
    );
    record!(
        "src/window_tree.rs::mode_tree_swap_cb",
        hmux2::src::window_tree::mode_tree_swap_cb,
        []
    );
    let actual = records.join("\n") + "\n";
    assert_eq!(actual, include_str!("fixtures/remaining-mode_tree.txt"));
}
