#![deny(unsafe_op_in_unsafe_fn)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![feature(extern_types)]
#![feature(native_link_modifiers_as_needed)]
#![feature(local_waker)]

#[macro_use]
extern crate c2rust_bitfields;
extern crate libc;

pub mod alerts;
pub mod alternate_character_entry;
pub mod argument_command_state;
pub mod argument_entry;
pub mod argument_parse_spec;
pub mod argument_text;
pub mod argument_value;
pub mod arguments;
pub mod arguments_trait;
pub mod calendar_time;
pub mod cfg;
pub mod client;
pub mod client_file_state;
pub mod client_identity;
pub mod client_window_state;
pub mod cmd;
pub mod cmdq;
pub mod colour_palette_state;
mod command_catalog;
pub mod command_entry_flag;
pub mod command_find_flags;
pub mod command_find_index;
pub mod command_find_targets;
pub mod command_find_trait;
pub mod command_group;
pub mod command_list_group;
pub mod command_list_trait;
pub mod command_parse_argument;
pub mod command_parse_command;
pub mod command_parse_flags;
pub mod command_parse_input;
pub mod command_parse_result;
pub mod command_parse_state;
mod command_parser;
pub mod command_prompt_item;
pub mod command_source;
pub mod command_text;
pub mod command_trait;
pub mod compat;
pub mod consts;
pub mod control;
pub mod control_block_state;
pub mod control_pane_state;
mod entity_id;
pub mod environ;
pub mod ffi;
pub mod file;
pub mod file_status;
pub mod fmt_engine;
pub mod format;
pub mod format_modifier;
pub mod format_text;
pub mod glob_result;
pub mod grid;
pub mod grid_cell;
pub mod grid_cell_entry;
pub mod grid_extended_entry;
pub mod grid_line;
mod handle_registry;
pub mod imsg_buffer_state;
pub mod imsg_data_buffer;
pub mod imsg_header;
pub mod imsg_message;
pub mod input;
pub mod input_cell;
pub mod input_event;
pub mod input_table_entry;
pub mod internet_address;
pub mod io_vector;
pub mod job;
pub mod key_bindings;
pub mod key_string_entry;
pub mod layout;
pub mod layout_cell;
pub mod log;
pub mod long_option;
pub mod menu_item;
pub mod menu_model;
pub mod message_header;
pub mod message_log;
pub mod modes;
pub mod names;
pub mod notify;
pub mod option_name_map;
pub mod option_table_entry;
pub mod options;
pub mod osdep_linux;
pub mod overlay;
pub mod pane_activity;
pub mod pane_border_cache;
pub mod pane_command;
pub mod pane_control_colours;
pub mod pane_exit;
pub mod pane_geometry;
pub mod pane_identity;
pub mod pane_output;
pub mod pane_output_base;
pub mod pane_resize;
pub mod pane_scrollbar;
pub mod pane_scrollbar_style;
pub mod pane_search;
pub mod pane_status_line;
pub mod pane_style_cache;
pub mod pane_theme;
pub mod paste;
pub mod plugin;
pub mod r#proc;
pub mod progress_bar;
pub mod prompt_history;
pub mod protocol_message;
pub mod reactor;
pub mod regex_buffer;
pub mod regex_match;
pub mod regsub;
pub mod resize;
pub mod screen;
pub mod screen_redraw_context;
pub mod server;
pub mod session;
pub mod session_alert;
pub mod session_attachment;
pub mod session_directory;
pub mod session_group_state;
pub mod session_identity;
pub mod session_name;
pub mod session_status;
pub mod session_timestamps;
pub mod session_trait;
pub mod signal_set;
pub mod socket_address;
pub mod sort;
pub mod spawn;
pub mod status;
pub mod systemd_bus_error;
pub mod systemd_id128;
pub mod systemd_job_watch;
pub mod terminal_code_entry;
pub mod terminal_command_payload;
pub mod terminal_default_key;
pub mod terminal_feature;
pub mod terminal_size;
pub mod time_spec;
pub mod time_value;
pub mod user_account;
pub mod variadic_arguments;
pub mod window_buffer_item;
#[cfg(test)]
pub mod tests {
    pub mod test_coverage_alerts;
    pub mod test_coverage_alpha;
    pub mod test_coverage_auto_01;
    pub mod test_coverage_auto_02;
    pub mod test_coverage_auto_03;
    pub mod test_coverage_auto_04;
    pub mod test_coverage_auto_05;
    pub mod test_coverage_auto_06;
    pub mod test_coverage_auto_07;
    pub mod test_coverage_auto_08;
    pub mod test_coverage_auto_09;
    pub mod test_coverage_auto_10;
    pub mod test_coverage_auto_11;
    pub mod test_coverage_auto_13;
    pub mod test_coverage_auto_14;
    pub mod test_coverage_auto_15;
    pub mod test_coverage_auto_16;
    pub mod test_coverage_auto_17;
    pub mod test_coverage_auto_18;
    pub mod test_coverage_auto_19;
    pub mod test_coverage_auto_20;
    pub mod test_coverage_auto_21;
    pub mod test_coverage_auto_22;
    pub mod test_coverage_auto_23;
    pub mod test_coverage_auto_24;
    pub mod test_coverage_auto_25;
    pub mod test_coverage_auto_26;
    pub mod test_coverage_auto_28;
    pub mod test_coverage_auto_29;
    pub mod test_coverage_client;
    pub mod test_coverage_cmd;
    pub mod test_coverage_compat_systemd;
    pub mod test_coverage_control_notify;
    pub mod test_coverage_delta;
    pub mod test_coverage_epsilon;
    pub mod test_coverage_extra;
    pub mod test_coverage_fdforkpty;
    pub mod test_coverage_gamma;
    pub mod test_coverage_input;
    pub mod test_coverage_key_bindings;
    pub mod test_coverage_low;
    pub mod test_coverage_popup;
    pub mod test_coverage_screen_redraw;
    pub mod test_coverage_spawn;
    pub mod test_coverage_status_prompt;
    pub mod test_coverage_tty_draw;
    pub mod test_coverage_tty_keys;
    pub mod test_coverage_window_buffer;
    pub mod test_coverage_window_client;
    pub mod test_fixtures;
    pub mod test_leak_regressions;
    pub mod test_trait_io_watch;
    pub mod test_trait_plugin;
    pub mod test_trait_reactor;
    pub mod test_trait_signal_watch;
    pub mod test_trait_timer;
} // mod tests
pub mod style;
pub mod style_line;
pub mod style_range;
pub mod style_trait;
pub mod terminfo;
pub mod text;
pub mod tmux;
pub mod tree;
pub mod tty;
pub mod types;
pub mod utf8_data;
pub mod visible_ranges;
pub mod window;
pub mod window_alert_queue;
pub mod window_dimensions;
pub mod window_fill_character;
pub mod window_layout_selection;
pub mod window_name;
pub mod window_pane;
pub mod window_pane_trait;
pub mod window_saved_layout;
pub mod window_scrollbar;
pub mod window_timestamps;
pub mod window_trait;
pub mod winlink_flags;
pub mod winlink_identity;
pub mod winlink_trait;
pub mod xmalloc;

pub use alternate_character_entry::*;
pub use argument_command_state::*;
pub use argument_entry::*;
pub use argument_parse_spec::*;
pub use argument_text::{ArgumentTextCodec, RustArgumentTextCodec};
pub use argument_value::*;
pub use arguments::RustArguments;
pub use arguments_trait::Arguments;
pub use calendar_time::*;
pub use client_file_state::*;
pub use client_identity::*;
pub use client_window_state::*;
pub use cmdq::CmdqItemRef;
pub use colour_palette_state::*;
pub use command_catalog::{CommandCatalog, RustCommandCatalog};
pub use cmd::{CommandEntry, CommandResult, RustCommandContext, RustCommandEntry};
pub use command_entry_flag::*;
pub use command_find_flags::{CommandFindFlagsState, RustCommandFindFlagsState};
pub use command_find_index::{CommandFindIndexState, RustCommandFindIndexState};
pub use command_find_targets::*;
pub use command_find_trait::CommandFind;
pub use command_group::{CommandGroupState, RustCommandGroupState};
pub use command_list_group::{CommandListGroupState, RustCommandListGroupState};
pub use command_list_trait::CommandList;
pub use command_parse_argument::*;
pub use command_parse_command::*;
pub use command_parse_flags::{CommandParseFlagsState, RustCommandParseFlagsState};
pub use command_parse_input::*;
pub use command_parse_result::*;
pub use command_parse_state::*;
pub use command_parser::{CommandParser, RustCommandParser};
pub use command_prompt_item::*;
pub use command_source::{CommandSource, CommandSourceState, RustCommandSourceState};
pub use command_text::{CommandTextCodec, RustCommandTextCodec};
pub use command_trait::Command;
pub use control_block_state::*;
pub use control_pane_state::*;
pub use environ::{ENVIRON_HIDDEN, EnvironmentEntryRef, EnvironmentStore, RustEnvironment};
pub use file_status::*;
pub use format_modifier::*;
pub use format_text::{FormatText, RustFormatText};
pub use glob_result::*;
pub use grid::{Grid, GridReader, Hyperlinks, RustGrid, RustGridReader, RustHyperlinks};
pub use grid_cell::GridCell;
pub use grid_cell_entry::GridCellEntry;
pub use grid_extended_entry::GridExtendedEntry;
pub use grid_line::GridLine;
pub use imsg_buffer_state::*;
pub use imsg_data_buffer::*;
pub use imsg_header::*;
pub use imsg_message::*;
pub use input::{
    KeyEncoding, KeyInputEncoder, MouseInputEncoder, RustKeyInputEncoder, RustMouseInputEncoder,
};
pub use input_cell::*;
pub use input_event::*;
pub use input_table_entry::*;
pub use internet_address::*;
pub use io_vector::*;
pub use key_string_entry::*;
pub use layout_cell::LayoutCell;
pub use long_option::*;
pub use menu_item::*;
pub use menu_model::*;
pub use message_header::*;
pub use message_log::{MessageLogEntryRef, MessageLogStore, MessageLogTime, RustMessageLog};
pub use names::{RustWindowNameParser, WindowNameParser};
pub use option_name_map::*;
pub use option_table_entry::*;
pub use pane_activity::{PaneActivityState, RustPaneActivityState};
pub use pane_border_cache::{PaneBorderCache, PaneBorderKind, RustPaneBorderCache};
pub use pane_command::{PaneCommand, PaneCommandState, RustPaneCommandState};
pub use pane_control_colours::{PaneControlColourPair, PaneControlColours, RustPaneControlColours};
pub use pane_exit::{PaneExitState, RustPaneExitState};
pub use pane_geometry::{PaneGeometry, PaneGeometryState, RustPaneGeometryState};
pub use pane_identity::{PaneIdentity, RustPaneIdentity};
pub use pane_output::{PaneOutputOffset, RustPaneOutputOffset};
pub use pane_output_base::{PaneOutputBaseState, RustPaneOutputBaseState};
pub use pane_resize::{PaneResizeQueue, PaneResizeStep, PaneSize, RustPaneResizeQueue};
pub use pane_scrollbar::{PaneScrollbar, PaneScrollbarSlider, RustPaneScrollbar};
pub use pane_scrollbar_style::{
    PaneScrollbarStyle, PaneScrollbarStyleState, RustPaneScrollbarStyleState,
};
pub use pane_search::{PaneSearchState, RustPaneSearchState};
pub use pane_status_line::{PaneStatusLineState, RustPaneStatusLineState};
pub use pane_style_cache::{PaneStyleCache, PaneStyleCells, RustPaneStyleCache};
pub use pane_theme::{PaneThemeState, RustPaneThemeState};
pub use paste::{PasteBufferRef, PasteBufferStore, RustPasteBufferStore};
pub use progress_bar::*;
pub use prompt_history::{PromptHistoryStore, PromptHistoryType, RustPromptHistoryStore};
pub use protocol_message::*;
pub use regex_buffer::*;
pub use regex_match::*;
pub use regsub::{RegsubEngine, RustRegsub};
pub use screen::{RustScreen, Screen};
pub use screen_redraw_context::*;
pub use server::{RustServerAclStore, ServerAclAccess, ServerAclEntry, ServerAclStore};
pub use session_alert::{RustSessionAlertState, SessionAlertState};
pub use session_attachment::{RustSessionAttachmentState, SessionAttachmentState};
pub use session_directory::{RustSessionDirectoryState, SessionDirectoryState};
pub use session_group_state::*;
pub use session_identity::{RustSessionIdentity, SessionIdentity};
pub use session_name::{RustSessionNameState, SessionNameState};
pub use session_status::{RustSessionStatusState, SessionStatus, SessionStatusState};
pub use session_timestamps::{RustSessionTimestampState, SessionTimestampState, SessionTimestamps};
pub use session_trait::Session;
pub use signal_set::*;
pub use socket_address::*;
pub use sort::{RustSortCriteria, SortCriteria};
pub use style::{
    AttributeCodec, ColourEngine, RustAttributeCodec, RustColourEngine, RustStyleCodec, StyleCodec,
    StyleParseError,
};
pub use style_line::StyleLine;
pub use style_range::StyleRange;
pub use style_trait::Style;
pub use systemd_bus_error::*;
pub use systemd_id128::*;
pub use systemd_job_watch::*;
pub use terminal_code_entry::*;
pub use terminal_command_payload::*;
pub use terminal_default_key::*;
pub use terminal_feature::*;
pub use terminal_size::*;
pub use terminfo::{
    AlternateCharacterSet, BorderCharacterSet, RustAlternateCharacterSet, RustTerminalCapabilities,
    TerminalCapabilities, TerminalCapabilityRef,
};
pub use terminfo::{RustTerminalFeatureSet, TerminalFeatureSet};
pub use text::{
    KeyStringCodec, RustKeyStringCodec, RustUtf8Compositor, RustUtf8VisModel, Utf8Compositor,
    Utf8VisModel,
};
pub use time_spec::*;
pub use time_value::*;
pub use user_account::*;
pub use utf8_data::Utf8Data;
pub use variadic_arguments::*;
pub use visible_ranges::{VisibleRange, VisibleRanges};
pub use window_alert_queue::{RustWindowAlertQueueState, WindowAlertQueueState};
pub use window_buffer_item::*;
pub use window_dimensions::{
    RustWindowDimensionsState, WindowCellPosition, WindowDimensions, WindowDimensionsState,
    WindowPixelSize,
};
pub use window_fill_character::{RustWindowFillCharacterState, WindowFillCharacterState};
pub use window_layout_selection::{RustWindowLayoutSelectionState, WindowLayoutSelectionState};
pub use window_name::{RustWindowNameState, WindowNameState};
pub use window_pane_trait::WindowPane;
pub use window_saved_layout::{RustWindowSavedLayoutState, WindowSavedLayoutState};
pub use window_scrollbar::{
    RustWindowScrollbarState, WindowScrollbarSettings, WindowScrollbarState,
};
pub use window_timestamps::{RustWindowTimestampState, WindowTimestampState, WindowTimestamps};
pub use window_trait::Window;
pub use winlink_flags::{RustWinlinkFlagsState, WinlinkFlagsState};
pub use winlink_identity::{RustWinlinkIdentity, WinlinkIdentity};
pub use winlink_trait::Winlink;

pub use options::{OptionsEngine, OptionsRef, RustOptionsEngine, RustOptionsRef};

mod pane_handle;
mod session_handle;
