//! Public module registry and compatibility aliases for historical paths.

pub mod alerts;
pub mod arguments;
pub mod bracketed_paste;
pub mod ffi;
pub use self::style::attributes;
pub mod cfg;
pub mod client;
pub mod cmd;
pub use self::cmd::entries::attach_session as cmd_attach_session;
pub use self::cmd::entries::bind_key as cmd_bind_key;
pub use self::cmd::entries::break_pane as cmd_break_pane;
pub use self::cmd::entries::capture_pane as cmd_capture_pane;
pub use self::cmd::entries::choose_tree as cmd_choose_tree;
pub use self::cmd::entries::command_prompt as cmd_command_prompt;
pub use self::cmd::entries::confirm_before as cmd_confirm_before;
pub use self::cmd::entries::copy_mode as cmd_copy_mode;
pub use self::cmd::entries::detach_client as cmd_detach_client;
pub use self::cmd::entries::display_menu as cmd_display_menu;
pub use self::cmd::entries::display_message as cmd_display_message;
pub use self::cmd::entries::find_window as cmd_find_window;
pub use self::cmd::entries::if_shell as cmd_if_shell;
pub use self::cmd::entries::join_pane as cmd_join_pane;
pub use self::cmd::entries::kill_pane as cmd_kill_pane;
pub use self::cmd::entries::kill_server as cmd_kill_server;
pub use self::cmd::entries::kill_session as cmd_kill_session;
pub use self::cmd::entries::kill_window as cmd_kill_window;
pub use self::cmd::entries::list_buffers as cmd_list_buffers;
pub use self::cmd::entries::list_clients as cmd_list_clients;
pub use self::cmd::entries::list_commands as cmd_list_commands;
pub use self::cmd::entries::list_keys as cmd_list_keys;
pub use self::cmd::entries::list_panes as cmd_list_panes;
pub use self::cmd::entries::list_sessions as cmd_list_sessions;
pub use self::cmd::entries::list_windows as cmd_list_windows;
pub use self::cmd::entries::load_buffer as cmd_load_buffer;
pub use self::cmd::entries::lock_server as cmd_lock_server;
pub use self::cmd::entries::move_window as cmd_move_window;
pub use self::cmd::entries::new_session as cmd_new_session;
pub use self::cmd::entries::new_window as cmd_new_window;
pub use self::cmd::entries::paste_buffer as cmd_paste_buffer;
pub use self::cmd::entries::pipe_pane as cmd_pipe_pane;
pub use self::cmd::entries::refresh_client as cmd_refresh_client;
pub use self::cmd::entries::rename_session as cmd_rename_session;
pub use self::cmd::entries::rename_window as cmd_rename_window;
pub use self::cmd::entries::resize_pane as cmd_resize_pane;
pub use self::cmd::entries::resize_window as cmd_resize_window;
pub use self::cmd::entries::respawn_pane as cmd_respawn_pane;
pub use self::cmd::entries::respawn_window as cmd_respawn_window;
pub use self::cmd::entries::rotate_window as cmd_rotate_window;
pub use self::cmd::entries::run_shell as cmd_run_shell;
pub use self::cmd::entries::save_buffer as cmd_save_buffer;
pub use self::cmd::entries::select_layout as cmd_select_layout;
pub use self::cmd::entries::select_pane as cmd_select_pane;
pub use self::cmd::entries::select_window as cmd_select_window;
pub use self::cmd::entries::send_keys as cmd_send_keys;
pub use self::cmd::entries::server_access as cmd_server_access;
pub use self::cmd::entries::set_buffer as cmd_set_buffer;
pub use self::cmd::entries::set_environment as cmd_set_environment;
pub use self::cmd::entries::set_option as cmd_set_option;
pub use self::cmd::entries::show_environment as cmd_show_environment;
pub use self::cmd::entries::show_messages as cmd_show_messages;
pub use self::cmd::entries::show_options as cmd_show_options;
pub use self::cmd::entries::show_prompt_history as cmd_show_prompt_history;
pub use self::cmd::entries::source_file as cmd_source_file;
pub use self::cmd::entries::split_window as cmd_split_window;
pub use self::cmd::entries::swap_pane as cmd_swap_pane;
pub use self::cmd::entries::swap_window as cmd_swap_window;
pub use self::cmd::entries::switch_client as cmd_switch_client;
pub use self::cmd::entries::unbind_key as cmd_unbind_key;
pub use self::cmd::entries::wait_for as cmd_wait_for;
pub use self::cmd::find as cmd_find;
pub use self::cmd::parse as cmd_parse;
pub use self::cmd::queue as cmd_queue;
pub use self::style::colour;
pub mod compat {
    pub mod fdforkpty;
    pub mod freezero;
    pub mod getdtablecount;
    pub mod getopt_long;
    pub mod getpeereid;
    pub mod getprogname;
    pub mod htonll;
    pub mod imsg;
    pub mod imsg_buffer;
    pub mod ntohll;
    pub mod recallocarray;
    pub mod setproctitle;
    pub mod strtonum;
    pub mod systemd;
    pub mod unvis;
    pub mod utf8proc;
    pub mod vis;
} // mod compat
pub mod control;
pub mod control_notify;
pub mod environ;
pub mod events;
pub mod events_payload;
pub mod file;
pub mod format;
pub mod format_draw;
pub mod fuzzy;
pub mod grid;
pub use self::grid::reader as grid_reader;
pub use self::grid::view as grid_view;
pub mod hooks;
pub mod hyperlinks;
pub mod input;
pub mod input_keys;
pub mod job;
pub mod json;
pub mod key_bindings;
pub mod key_string;
pub mod layout;
pub use self::layout::custom as layout_custom;
pub use self::layout::set as layout_set;
pub mod log;
pub mod menu;
pub mod mode_tree;
pub mod monitor;
pub mod names;
pub mod options;
pub mod options_parse;
pub mod options_table;
pub mod osdep_linux;
pub mod paste;
pub mod popup;
pub mod r#proc;
pub mod prompt;
pub mod prompt_history;
pub mod regsub;
pub mod resize;
pub mod screen;
pub mod screen_redraw;
pub mod screen_write;
pub mod server;
pub mod server_acl;
pub mod server_client;
pub mod server_fn;
pub mod session;
pub mod shared;
pub mod sort;
pub mod spawn;
pub mod status;
pub mod style;
pub mod text;
pub mod tmux;
pub mod tty;
pub mod tty_acs;
pub mod tty_draw;
pub mod tty_features;
pub mod tty_keys;
pub mod tty_term;
pub use self::text::utf8;
pub use self::text::utf8_combined;
pub use self::text::utf8_decode;
pub mod window;
pub mod window_border;
pub mod window_buffer;
pub mod window_client;
pub mod window_clock;
pub mod window_copy;
pub mod window_customize;
pub mod window_panes;
pub mod window_switch;
pub mod window_tree;
pub mod window_visible;
pub mod xmalloc;

pub mod reactor;
